DELETE FROM ui_info WHERE module_name='Gamma';
DELETE FROM ui_info_regmodule WHERE ui_module_name='Gamma';
DELETE FROM ui_info WHERE module_name='GammaGain';
DELETE FROM ui_info_regmodule WHERE ui_module_name='GammaGain';
INSERT INTO ui_info VALUES 
('Gamma', 'Gamma A', 0, 'r_pCurveAList[0]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 0, 'r_pCurveAList[0]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 0, 'r_pCurveAList[0]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 1, 'r_pCurveAList[1]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 1, 'r_pCurveAList[1]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 1, 'r_pCurveAList[1]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 2, 'r_pCurveAList[2]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 2, 'r_pCurveAList[2]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 2, 'r_pCurveAList[2]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 3, 'r_pCurveAList[3]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 3, 'r_pCurveAList[3]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 3, 'r_pCurveAList[3]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 4, 'r_pCurveAList[4]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 4, 'r_pCurveAList[4]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 4, 'r_pCurveAList[4]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 5, 'r_pCurveAList[5]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 5, 'r_pCurveAList[5]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 5, 'r_pCurveAList[5]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 6, 'r_pCurveAList[6]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 6, 'r_pCurveAList[6]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 6, 'r_pCurveAList[6]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 7, 'r_pCurveAList[7]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 7, 'r_pCurveAList[7]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 7, 'r_pCurveAList[7]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 8, 'r_pCurveAList[8]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 8, 'r_pCurveAList[8]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 8, 'r_pCurveAList[8]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 9, 'r_pCurveAList[9]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 9, 'r_pCurveAList[9]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 9, 'r_pCurveAList[9]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 10, 'r_pCurveAList[10]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 10, 'r_pCurveAList[10]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 10, 'r_pCurveAList[10]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 11, 'r_pCurveAList[11]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 11, 'r_pCurveAList[11]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 11, 'r_pCurveAList[11]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 12, 'r_pCurveAList[12]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 12, 'r_pCurveAList[12]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 12, 'r_pCurveAList[12]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 13, 'r_pCurveAList[13]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 13, 'r_pCurveAList[13]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 13, 'r_pCurveAList[13]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 14, 'r_pCurveAList[14]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 14, 'r_pCurveAList[14]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 14, 'r_pCurveAList[14]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 15, 'r_pCurveAList[15]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 15, 'r_pCurveAList[15]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 15, 'r_pCurveAList[15]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 16, 'r_pCurveAList[16]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 16, 'r_pCurveAList[16]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 16, 'r_pCurveAList[16]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 17, 'r_pCurveAList[17]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 17, 'r_pCurveAList[17]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 17, 'r_pCurveAList[17]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 18, 'r_pCurveAList[18]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 18, 'r_pCurveAList[18]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 18, 'r_pCurveAList[18]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 19, 'r_pCurveAList[19]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 19, 'r_pCurveAList[19]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 19, 'r_pCurveAList[19]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 20, 'r_pCurveAList[20]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 20, 'r_pCurveAList[20]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 20, 'r_pCurveAList[20]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 21, 'r_pCurveAList[21]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 21, 'r_pCurveAList[21]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 21, 'r_pCurveAList[21]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 22, 'r_pCurveAList[22]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 22, 'r_pCurveAList[22]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 22, 'r_pCurveAList[22]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 23, 'r_pCurveAList[23]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 23, 'r_pCurveAList[23]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 23, 'r_pCurveAList[23]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 24, 'r_pCurveAList[24]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 24, 'r_pCurveAList[24]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 24, 'r_pCurveAList[24]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 25, 'r_pCurveAList[25]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 25, 'r_pCurveAList[25]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 25, 'r_pCurveAList[25]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 26, 'r_pCurveAList[26]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 26, 'r_pCurveAList[26]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 26, 'r_pCurveAList[26]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 27, 'r_pCurveAList[27]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 27, 'r_pCurveAList[27]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 27, 'r_pCurveAList[27]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 28, 'r_pCurveAList[28]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 28, 'r_pCurveAList[28]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 28, 'r_pCurveAList[28]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 29, 'r_pCurveAList[29]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 29, 'r_pCurveAList[29]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 29, 'r_pCurveAList[29]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 30, 'r_pCurveAList[30]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 30, 'r_pCurveAList[30]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 30, 'r_pCurveAList[30]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 31, 'r_pCurveAList[31]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 31, 'r_pCurveAList[31]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 31, 'r_pCurveAList[31]', NULL, 'Administrator'),
('Gamma', 'Gamma A', 32, 'r_pCurveAList[32]', NULL, 'Administrator'),
('Gamma', 'Gamma A IR_AB', 32, 'r_pCurveAList[32]', NULL, 'Administrator'),
('Gamma', 'Gamma A RGB_AB', 32, 'r_pCurveAList[32]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 0, 'r_pCurveBList[0]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 0, 'r_pCurveBList[0]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 0, 'r_pCurveBList[0]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 1, 'r_pCurveBList[1]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 1, 'r_pCurveBList[1]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 1, 'r_pCurveBList[1]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 2, 'r_pCurveBList[2]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 2, 'r_pCurveBList[2]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 2, 'r_pCurveBList[2]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 3, 'r_pCurveBList[3]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 3, 'r_pCurveBList[3]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 3, 'r_pCurveBList[3]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 4, 'r_pCurveBList[4]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 4, 'r_pCurveBList[4]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 4, 'r_pCurveBList[4]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 5, 'r_pCurveBList[5]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 5, 'r_pCurveBList[5]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 5, 'r_pCurveBList[5]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 6, 'r_pCurveBList[6]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 6, 'r_pCurveBList[6]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 6, 'r_pCurveBList[6]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 7, 'r_pCurveBList[7]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 7, 'r_pCurveBList[7]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 7, 'r_pCurveBList[7]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 8, 'r_pCurveBList[8]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 8, 'r_pCurveBList[8]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 8, 'r_pCurveBList[8]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 9, 'r_pCurveBList[9]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 9, 'r_pCurveBList[9]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 9, 'r_pCurveBList[9]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 10, 'r_pCurveBList[10]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 10, 'r_pCurveBList[10]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 10, 'r_pCurveBList[10]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 11, 'r_pCurveBList[11]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 11, 'r_pCurveBList[11]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 11, 'r_pCurveBList[11]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 12, 'r_pCurveBList[12]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 12, 'r_pCurveBList[12]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 12, 'r_pCurveBList[12]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 13, 'r_pCurveBList[13]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 13, 'r_pCurveBList[13]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 13, 'r_pCurveBList[13]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 14, 'r_pCurveBList[14]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 14, 'r_pCurveBList[14]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 14, 'r_pCurveBList[14]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 15, 'r_pCurveBList[15]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 15, 'r_pCurveBList[15]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 15, 'r_pCurveBList[15]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 16, 'r_pCurveBList[16]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 16, 'r_pCurveBList[16]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 16, 'r_pCurveBList[16]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 17, 'r_pCurveBList[17]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 17, 'r_pCurveBList[17]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 17, 'r_pCurveBList[17]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 18, 'r_pCurveBList[18]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 18, 'r_pCurveBList[18]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 18, 'r_pCurveBList[18]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 19, 'r_pCurveBList[19]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 19, 'r_pCurveBList[19]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 19, 'r_pCurveBList[19]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 20, 'r_pCurveBList[20]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 20, 'r_pCurveBList[20]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 20, 'r_pCurveBList[20]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 21, 'r_pCurveBList[21]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 21, 'r_pCurveBList[21]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 21, 'r_pCurveBList[21]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 22, 'r_pCurveBList[22]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 22, 'r_pCurveBList[22]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 22, 'r_pCurveBList[22]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 23, 'r_pCurveBList[23]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 23, 'r_pCurveBList[23]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 23, 'r_pCurveBList[23]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 24, 'r_pCurveBList[24]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 24, 'r_pCurveBList[24]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 24, 'r_pCurveBList[24]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 25, 'r_pCurveBList[25]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 25, 'r_pCurveBList[25]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 25, 'r_pCurveBList[25]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 26, 'r_pCurveBList[26]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 26, 'r_pCurveBList[26]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 26, 'r_pCurveBList[26]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 27, 'r_pCurveBList[27]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 27, 'r_pCurveBList[27]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 27, 'r_pCurveBList[27]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 28, 'r_pCurveBList[28]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 28, 'r_pCurveBList[28]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 28, 'r_pCurveBList[28]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 29, 'r_pCurveBList[29]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 29, 'r_pCurveBList[29]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 29, 'r_pCurveBList[29]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 30, 'r_pCurveBList[30]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 30, 'r_pCurveBList[30]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 30, 'r_pCurveBList[30]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 31, 'r_pCurveBList[31]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 31, 'r_pCurveBList[31]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 31, 'r_pCurveBList[31]', NULL, 'Administrator'),
('Gamma', 'Gamma B', 32, 'r_pCurveBList[32]', NULL, 'Administrator'),
('Gamma', 'Gamma B IR_AB', 32, 'r_pCurveBList[32]', NULL, 'Administrator'),
('Gamma', 'Gamma B RGB_AB', 32, 'r_pCurveBList[32]', NULL, 'Administrator'),
('Gamma', 'Current Gain', 0, 'current L Gain', NULL, 'Administrator'),
('Gamma', 'Curve Thre1', 0, 'r_nCurveThre1', NULL, 'Administrator'),
('Gamma', 'Curve Thre1 IR_AB', 0, 'r_nCurveThre1', NULL, 'Administrator'),
('Gamma', 'Curve Thre1 RGB_AB', 0, 'r_nCurveThre1', NULL, 'Administrator'),
('Gamma', 'Curve Thre2', 0, 'r_nCurveThre2', NULL, 'Administrator'),
('Gamma', 'Curve Thre2 IR_AB', 0, 'r_nCurveThre2', NULL, 'Administrator'),
('Gamma', 'Curve Thre2 RGB_AB', 0, 'r_nCurveThre2', NULL, 'Administrator'),
('Gamma', 'GamEnable', 0, 'r_gma_en', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 0, 'r_pCurveGainA[0]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 0, 'r_pCurveGainA[0]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 0, 'r_pCurveGainA[0]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 1, 'r_pCurveGainA[1]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 1, 'r_pCurveGainA[1]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 1, 'r_pCurveGainA[1]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 2, 'r_pCurveGainA[2]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 2, 'r_pCurveGainA[2]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 2, 'r_pCurveGainA[2]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 3, 'r_pCurveGainA[3]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 3, 'r_pCurveGainA[3]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 3, 'r_pCurveGainA[3]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 4, 'r_pCurveGainA[4]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 4, 'r_pCurveGainA[4]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 4, 'r_pCurveGainA[4]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 5, 'r_pCurveGainA[5]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 5, 'r_pCurveGainA[5]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 5, 'r_pCurveGainA[5]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 6, 'r_pCurveGainA[6]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 6, 'r_pCurveGainA[6]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 6, 'r_pCurveGainA[6]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 7, 'r_pCurveGainA[7]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 7, 'r_pCurveGainA[7]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 7, 'r_pCurveGainA[7]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 8, 'r_pCurveGainA[8]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 8, 'r_pCurveGainA[8]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 8, 'r_pCurveGainA[8]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 9, 'r_pCurveGainA[9]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 9, 'r_pCurveGainA[9]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 9, 'r_pCurveGainA[9]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 10, 'r_pCurveGainA[10]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 10, 'r_pCurveGainA[10]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 10, 'r_pCurveGainA[10]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 11, 'r_pCurveGainA[11]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 11, 'r_pCurveGainA[11]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 11, 'r_pCurveGainA[11]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 12, 'r_pCurveGainA[12]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 12, 'r_pCurveGainA[12]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 12, 'r_pCurveGainA[12]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 13, 'r_pCurveGainA[13]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 13, 'r_pCurveGainA[13]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 13, 'r_pCurveGainA[13]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 14, 'r_pCurveGainA[14]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 14, 'r_pCurveGainA[14]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 14, 'r_pCurveGainA[14]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 15, 'r_pCurveGainA[15]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 15, 'r_pCurveGainA[15]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 15, 'r_pCurveGainA[15]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 16, 'r_pCurveGainA[16]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 16, 'r_pCurveGainA[16]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 16, 'r_pCurveGainA[16]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 17, 'r_pCurveGainA[17]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 17, 'r_pCurveGainA[17]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 17, 'r_pCurveGainA[17]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 18, 'r_pCurveGainA[18]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 18, 'r_pCurveGainA[18]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 18, 'r_pCurveGainA[18]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 19, 'r_pCurveGainA[19]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 19, 'r_pCurveGainA[19]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 19, 'r_pCurveGainA[19]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 20, 'r_pCurveGainA[20]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 20, 'r_pCurveGainA[20]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 20, 'r_pCurveGainA[20]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 21, 'r_pCurveGainA[21]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 21, 'r_pCurveGainA[21]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 21, 'r_pCurveGainA[21]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 22, 'r_pCurveGainA[22]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 22, 'r_pCurveGainA[22]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 22, 'r_pCurveGainA[22]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 23, 'r_pCurveGainA[23]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 23, 'r_pCurveGainA[23]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 23, 'r_pCurveGainA[23]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 24, 'r_pCurveGainA[24]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 24, 'r_pCurveGainA[24]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 24, 'r_pCurveGainA[24]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 25, 'r_pCurveGainA[25]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 25, 'r_pCurveGainA[25]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 25, 'r_pCurveGainA[25]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 26, 'r_pCurveGainA[26]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 26, 'r_pCurveGainA[26]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 26, 'r_pCurveGainA[26]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 27, 'r_pCurveGainA[27]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 27, 'r_pCurveGainA[27]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 27, 'r_pCurveGainA[27]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 28, 'r_pCurveGainA[28]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 28, 'r_pCurveGainA[28]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 28, 'r_pCurveGainA[28]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 29, 'r_pCurveGainA[29]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 29, 'r_pCurveGainA[29]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 29, 'r_pCurveGainA[29]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 30, 'r_pCurveGainA[30]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 30, 'r_pCurveGainA[30]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 30, 'r_pCurveGainA[30]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 31, 'r_pCurveGainA[31]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 31, 'r_pCurveGainA[31]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 31, 'r_pCurveGainA[31]', NULL, 'Administrator'),
('GammaGain', 'Gamma A', 32, 'r_pCurveGainA[32]', NULL, 'Administrator'),
('GammaGain', 'Gamma A IR_AB', 32, 'r_pCurveGainA[32]', NULL, 'Administrator'),
('GammaGain', 'Gamma A RGB_AB', 32, 'r_pCurveGainA[32]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 0, 'r_pCurveGainB[0]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 0, 'r_pCurveGainB[0]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 0, 'r_pCurveGainB[0]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 1, 'r_pCurveGainB[1]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 1, 'r_pCurveGainB[1]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 1, 'r_pCurveGainB[1]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 2, 'r_pCurveGainB[2]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 2, 'r_pCurveGainB[2]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 2, 'r_pCurveGainB[2]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 3, 'r_pCurveGainB[3]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 3, 'r_pCurveGainB[3]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 3, 'r_pCurveGainB[3]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 4, 'r_pCurveGainB[4]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 4, 'r_pCurveGainB[4]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 4, 'r_pCurveGainB[4]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 5, 'r_pCurveGainB[5]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 5, 'r_pCurveGainB[5]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 5, 'r_pCurveGainB[5]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 6, 'r_pCurveGainB[6]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 6, 'r_pCurveGainB[6]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 6, 'r_pCurveGainB[6]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 7, 'r_pCurveGainB[7]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 7, 'r_pCurveGainB[7]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 7, 'r_pCurveGainB[7]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 8, 'r_pCurveGainB[8]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 8, 'r_pCurveGainB[8]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 8, 'r_pCurveGainB[8]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 9, 'r_pCurveGainB[9]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 9, 'r_pCurveGainB[9]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 9, 'r_pCurveGainB[9]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 10, 'r_pCurveGainB[10]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 10, 'r_pCurveGainB[10]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 10, 'r_pCurveGainB[10]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 11, 'r_pCurveGainB[11]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 11, 'r_pCurveGainB[11]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 11, 'r_pCurveGainB[11]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 12, 'r_pCurveGainB[12]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 12, 'r_pCurveGainB[12]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 12, 'r_pCurveGainB[12]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 13, 'r_pCurveGainB[13]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 13, 'r_pCurveGainB[13]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 13, 'r_pCurveGainB[13]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 14, 'r_pCurveGainB[14]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 14, 'r_pCurveGainB[14]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 14, 'r_pCurveGainB[14]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 15, 'r_pCurveGainB[15]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 15, 'r_pCurveGainB[15]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 15, 'r_pCurveGainB[15]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 16, 'r_pCurveGainB[16]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 16, 'r_pCurveGainB[16]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 16, 'r_pCurveGainB[16]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 17, 'r_pCurveGainB[17]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 17, 'r_pCurveGainB[17]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 17, 'r_pCurveGainB[17]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 18, 'r_pCurveGainB[18]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 18, 'r_pCurveGainB[18]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 18, 'r_pCurveGainB[18]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 19, 'r_pCurveGainB[19]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 19, 'r_pCurveGainB[19]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 19, 'r_pCurveGainB[19]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 20, 'r_pCurveGainB[20]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 20, 'r_pCurveGainB[20]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 20, 'r_pCurveGainB[20]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 21, 'r_pCurveGainB[21]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 21, 'r_pCurveGainB[21]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 21, 'r_pCurveGainB[21]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 22, 'r_pCurveGainB[22]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 22, 'r_pCurveGainB[22]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 22, 'r_pCurveGainB[22]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 23, 'r_pCurveGainB[23]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 23, 'r_pCurveGainB[23]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 23, 'r_pCurveGainB[23]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 24, 'r_pCurveGainB[24]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 24, 'r_pCurveGainB[24]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 24, 'r_pCurveGainB[24]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 25, 'r_pCurveGainB[25]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 25, 'r_pCurveGainB[25]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 25, 'r_pCurveGainB[25]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 26, 'r_pCurveGainB[26]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 26, 'r_pCurveGainB[26]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 26, 'r_pCurveGainB[26]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 27, 'r_pCurveGainB[27]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 27, 'r_pCurveGainB[27]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 27, 'r_pCurveGainB[27]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 28, 'r_pCurveGainB[28]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 28, 'r_pCurveGainB[28]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 28, 'r_pCurveGainB[28]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 29, 'r_pCurveGainB[29]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 29, 'r_pCurveGainB[29]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 29, 'r_pCurveGainB[29]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 30, 'r_pCurveGainB[30]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 30, 'r_pCurveGainB[30]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 30, 'r_pCurveGainB[30]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 31, 'r_pCurveGainB[31]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 31, 'r_pCurveGainB[31]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 31, 'r_pCurveGainB[31]', NULL, 'Administrator'),
('GammaGain', 'Gamma B', 32, 'r_pCurveGainB[32]', NULL, 'Administrator'),
('GammaGain', 'Gamma B IR_AB', 32, 'r_pCurveGainB[32]', NULL, 'Administrator'),
('GammaGain', 'Gamma B RGB_AB', 32, 'r_pCurveGainB[32]', NULL, 'Administrator'),
('GammaGain', 'Current Gain', 0, 'current L Gain', NULL, 'Administrator'),
('GammaGain', 'Curve Thre1', 0, 'r_nCurveThre1', NULL, 'Administrator'),
('GammaGain', 'Curve Thre1 IR_AB', 0, 'r_nCurveThre1', NULL, 'Administrator'),
('GammaGain', 'Curve Thre1 RGB_AB', 0, 'r_nCurveThre1', NULL, 'Administrator'),
('GammaGain', 'Curve Thre2', 0, 'r_nCurveThre2', NULL, 'Administrator'),
('GammaGain', 'Curve Thre2 IR_AB', 0, 'r_nCurveThre2', NULL, 'Administrator'),
('GammaGain', 'Curve Thre2 RGB_AB', 0, 'r_nCurveThre2', NULL, 'Administrator'),
('GammaGain', 'Apply_h_en', 0, 'r_apply_h_en', NULL, 'Administrator');

INSERT INTO ui_info_regmodule VALUES 
('Gamma', 'Gamma A', 'CURVE', 1),
('Gamma', 'Gamma B', 'CURVE', 1),
('Gamma', 'Current Gain', 'PipeCtrl', 1),
('Gamma', 'Curve Thre1', 'CURVE', 1),
('Gamma', 'Curve Thre2', 'CURVE', 1),
('Gamma', 'GamEnable', 'CCurveFilter_V60_HW', 0),
('GammaGain', 'Gamma A', 'CURVE', 1),
('GammaGain', 'Gamma B', 'CURVE', 1),
('GammaGain', 'Current Gain', 'PipeCtrl', 1),
('GammaGain', 'Curve Thre1', 'CURVE', 1),
('GammaGain', 'Curve Thre2', 'CURVE', 1),
('GammaGain', 'Apply_h_en', 'CCurveFilter_V60_HW', 0);
