DELETE FROM ui_info WHERE module_name='GBalance-S';
DELETE FROM ui_info_regmodule WHERE ui_module_name='GBalance-S';
DELETE FROM ui_info WHERE module_name='GBalance-LFS';
DELETE FROM ui_info_regmodule WHERE ui_module_name='GBalance-LFS';
INSERT INTO ui_info VALUES 
('GBalance-S', 'GBalCoe[0]', 0, 'r_nGBalCoe[0]', NULL, 'Administrator'),
('GBalance-S', 'GBalCoe[1]', 0, 'r_nGBalCoe[1]', NULL, 'Administrator'),
('GBalance-S', 'GBalCoe[2]', 0, 'r_nGBalCoe[2]', NULL, 'Administrator'),
('GBalance-S', 'GBalCoe[3]', 0, 'r_nGBalCoe[3]', NULL, 'Administrator'),
('GBalance-S', 'GBalCoe[4]', 0, 'r_nGBalCoe[4]', NULL, 'Administrator'),
('GBalance-S', 'GBalCoe[5]', 0, 'r_nGBalCoe[5]', NULL, 'Administrator'),
('GBalance-S', 'GBalCoe[6]', 0, 'r_nGBalCoe[6]', NULL, 'Administrator'),
('GBalance-S', 'GBalCoe[7]', 0, 'r_nGBalCoe[7]', NULL, 'Administrator'),
('GBalance-S', 'GBalInt[0]', 0, 'r_nGBalInt[0]', NULL, 'Administrator'),
('GBalance-S', 'GBalInt[1]', 0, 'r_nGBalInt[1]', NULL, 'Administrator'),
('GBalance-S', 'GBalInt[2]', 0, 'r_nGBalInt[2]', NULL, 'Administrator'),
('GBalance-S', 'GBalInt[3]', 0, 'r_nGBalInt[3]', NULL, 'Administrator'),
('GBalance-S', 'GBalInt[4]', 0, 'r_nGBalInt[4]', NULL, 'Administrator'),
('GBalance-S', 'GBalInt[5]', 0, 'r_nGBalInt[5]', NULL, 'Administrator'),
('GBalance-S', 'GBalInt[6]', 0, 'r_nGBalInt[6]', NULL, 'Administrator'),
('GBalance-S', 'GBalInt[7]', 0, 'r_nGBalInt[7]', NULL, 'Administrator'),
('GBalance-S', 'GainNode[0]', 0, 'r_nGainNode[0]', NULL, 'Administrator'),
('GBalance-S', 'GainNode[1]', 0, 'r_nGainNode[1]', NULL, 'Administrator'),
('GBalance-S', 'GainNode[2]', 0, 'r_nGainNode[2]', NULL, 'Administrator'),
('GBalance-S', 'GainNode[3]', 0, 'r_nGainNode[3]', NULL, 'Administrator'),
('GBalance-S', 'GainNode[4]', 0, 'r_nGainNode[4]', NULL, 'Administrator'),
('GBalance-S', 'GainNode[5]', 0, 'r_nGainNode[5]', NULL, 'Administrator'),
('GBalance-S', 'GainNode[6]', 0, 'r_nGainNode[6]', NULL, 'Administrator'),
('GBalance-S', 'GainNode[7]', 0, 'r_nGainNode[7]', NULL, 'Administrator'),
('GBalance-LFS', 'GBalCoe[0]', 0, 'r_nGBalCoe[0]', NULL, 'Administrator'),
('GBalance-LFS', 'GBalCoe[1]', 0, 'r_nGBalCoe[1]', NULL, 'Administrator'),
('GBalance-LFS', 'GBalCoe[2]', 0, 'r_nGBalCoe[2]', NULL, 'Administrator'),
('GBalance-LFS', 'GBalCoe[3]', 0, 'r_nGBalCoe[3]', NULL, 'Administrator'),
('GBalance-LFS', 'GBalCoe[4]', 0, 'r_nGBalCoe[4]', NULL, 'Administrator'),
('GBalance-LFS', 'GBalCoe[5]', 0, 'r_nGBalCoe[5]', NULL, 'Administrator'),
('GBalance-LFS', 'GBalCoe[6]', 0, 'r_nGBalCoe[6]', NULL, 'Administrator'),
('GBalance-LFS', 'GBalCoe[7]', 0, 'r_nGBalCoe[7]', NULL, 'Administrator'),
('GBalance-LFS', 'GBalInt[0]', 0, 'r_nGBalInt[0]', NULL, 'Administrator'),
('GBalance-LFS', 'GBalInt[1]', 0, 'r_nGBalInt[1]', NULL, 'Administrator'),
('GBalance-LFS', 'GBalInt[2]', 0, 'r_nGBalInt[2]', NULL, 'Administrator'),
('GBalance-LFS', 'GBalInt[3]', 0, 'r_nGBalInt[3]', NULL, 'Administrator'),
('GBalance-LFS', 'GBalInt[4]', 0, 'r_nGBalInt[4]', NULL, 'Administrator'),
('GBalance-LFS', 'GBalInt[5]', 0, 'r_nGBalInt[5]', NULL, 'Administrator'),
('GBalance-LFS', 'GBalInt[6]', 0, 'r_nGBalInt[6]', NULL, 'Administrator'),
('GBalance-LFS', 'GBalInt[7]', 0, 'r_nGBalInt[7]', NULL, 'Administrator'),
('GBalance-LFS', 'GainNode[0]', 0, 'r_nGainNode[0]', NULL, 'Administrator'),
('GBalance-LFS', 'GainNode[1]', 0, 'r_nGainNode[1]', NULL, 'Administrator'),
('GBalance-LFS', 'GainNode[2]', 0, 'r_nGainNode[2]', NULL, 'Administrator'),
('GBalance-LFS', 'GainNode[3]', 0, 'r_nGainNode[3]', NULL, 'Administrator'),
('GBalance-LFS', 'GainNode[4]', 0, 'r_nGainNode[4]', NULL, 'Administrator'),
('GBalance-LFS', 'GainNode[5]', 0, 'r_nGainNode[5]', NULL, 'Administrator'),
('GBalance-LFS', 'GainNode[6]', 0, 'r_nGainNode[6]', NULL, 'Administrator'),
('GBalance-LFS', 'GainNode[7]', 0, 'r_nGainNode[7]', NULL, 'Administrator');

INSERT INTO ui_info_regmodule VALUES 
('GBalance-S', 'GBalCoe[0]', 'CIP_S', 1),
('GBalance-S', 'GBalCoe[1]', 'CIP_S', 1),
('GBalance-S', 'GBalCoe[2]', 'CIP_S', 1),
('GBalance-S', 'GBalCoe[3]', 'CIP_S', 1),
('GBalance-S', 'GBalCoe[4]', 'CIP_S', 1),
('GBalance-S', 'GBalCoe[5]', 'CIP_S', 1),
('GBalance-S', 'GBalCoe[6]', 'CIP_S', 1),
('GBalance-S', 'GBalCoe[7]', 'CIP_S', 1),
('GBalance-S', 'GBalInt[0]', 'CIP_S', 1),
('GBalance-S', 'GBalInt[1]', 'CIP_S', 1),
('GBalance-S', 'GBalInt[2]', 'CIP_S', 1),
('GBalance-S', 'GBalInt[3]', 'CIP_S', 1),
('GBalance-S', 'GBalInt[4]', 'CIP_S', 1),
('GBalance-S', 'GBalInt[5]', 'CIP_S', 1),
('GBalance-S', 'GBalInt[6]', 'CIP_S', 1),
('GBalance-S', 'GBalInt[7]', 'CIP_S', 1),
('GBalance-S', 'GainNode[0]', 'CIP_S', 1),
('GBalance-S', 'GainNode[1]', 'CIP_S', 1),
('GBalance-S', 'GainNode[2]', 'CIP_S', 1),
('GBalance-S', 'GainNode[3]', 'CIP_S', 1),
('GBalance-S', 'GainNode[4]', 'CIP_S', 1),
('GBalance-S', 'GainNode[5]', 'CIP_S', 1),
('GBalance-S', 'GainNode[6]', 'CIP_S', 1),
('GBalance-S', 'GainNode[7]', 'CIP_S', 1),
('GBalance-LFS', 'GBalCoe[0]', 'CIP_V', 1),
('GBalance-LFS', 'GBalCoe[1]', 'CIP_V', 1),
('GBalance-LFS', 'GBalCoe[2]', 'CIP_V', 1),
('GBalance-LFS', 'GBalCoe[3]', 'CIP_V', 1),
('GBalance-LFS', 'GBalCoe[4]', 'CIP_V', 1),
('GBalance-LFS', 'GBalCoe[5]', 'CIP_V', 1),
('GBalance-LFS', 'GBalCoe[6]', 'CIP_V', 1),
('GBalance-LFS', 'GBalCoe[7]', 'CIP_V', 1),
('GBalance-LFS', 'GBalInt[0]', 'CIP_V', 1),
('GBalance-LFS', 'GBalInt[1]', 'CIP_V', 1),
('GBalance-LFS', 'GBalInt[2]', 'CIP_V', 1),
('GBalance-LFS', 'GBalInt[3]', 'CIP_V', 1),
('GBalance-LFS', 'GBalInt[4]', 'CIP_V', 1),
('GBalance-LFS', 'GBalInt[5]', 'CIP_V', 1),
('GBalance-LFS', 'GBalInt[6]', 'CIP_V', 1),
('GBalance-LFS', 'GBalInt[7]', 'CIP_V', 1),
('GBalance-LFS', 'GainNode[0]', 'CIP_V', 1),
('GBalance-LFS', 'GainNode[1]', 'CIP_V', 1),
('GBalance-LFS', 'GainNode[2]', 'CIP_V', 1),
('GBalance-LFS', 'GainNode[3]', 'CIP_V', 1),
('GBalance-LFS', 'GainNode[4]', 'CIP_V', 1),
('GBalance-LFS', 'GainNode[5]', 'CIP_V', 1),
('GBalance-LFS', 'GainNode[6]', 'CIP_V', 1),
('GBalance-LFS', 'GainNode[7]', 'CIP_V', 1);
