DELETE FROM ui_info WHERE module_name='CAC_L';
DELETE FROM ui_info_regmodule WHERE ui_module_name='CAC_L';
INSERT INTO ui_info VALUES 
('CAC_L','CAC_Enable',0,'r_cac_enable',NULL,'Administrator'),
('CAC_L','Only_Over_Exposed',0,'r_only_over_exposed',NULL,'Administrator'),
('CAC_L','Yellow_Fringle',0,'r_yellow_fringe_enable',NULL,'Administrator'),
('CAC_L','CAC_Weight',0,'r_cac_weight',NULL,'Administrator'),
('CAC_L','Contrast_Low_Thre',0,'r_contrast_low_th',NULL,'Administrator'),
('CAC_L','Contrast_High_Thre',0,'r_contrast_high_th',NULL,'Administrator'),
('CAC_L','Contrast_Thre',0,'r_contrast_th',NULL,'Administrator'),
('CAC_L','Over_Exposure_Thre',0,'r_over_exposure_threshold',NULL,'Administrator'),
('CAC_L','Yellow_Sat_Thre',0,'r_yellow_sat_threshold',NULL,'Administrator'),
('CAC_L','Purple_Sat_Thre',0,'r_purple_sat_threshold',NULL,'Administrator'),
('CAC_L','hue_weight',0,'r_hue_weight[0]',NULL,'Administrator'),
('CAC_L','hue_weight',1,'r_hue_weight[1]',NULL,'Administrator'),
('CAC_L','hue_weight',2,'r_hue_weight[2]',NULL,'Administrator'),
('CAC_L','hue_weight',3,'r_hue_weight[3]',NULL,'Administrator'),
('CAC_L','hue_weight',4,'r_hue_weight[4]',NULL,'Administrator'),
('CAC_L','hue_weight',5,'r_hue_weight[5]',NULL,'Administrator'),
('CAC_L','hue_weight',6,'r_hue_weight[6]',NULL,'Administrator'),
('CAC_L','hue_weight',7,'r_hue_weight[7]',NULL,'Administrator'),
('CAC_L','hue_weight',8,'r_hue_weight[8]',NULL,'Administrator'),
('CAC_L','hue_weight',9,'r_hue_weight[9]',NULL,'Administrator'),
('CAC_L','hue_weight',10,'r_hue_weight[10]',NULL,'Administrator'),
('CAC_L','hue_weight',11,'r_hue_weight[11]',NULL,'Administrator'),
('CAC_L','hue_weight',12,'r_hue_weight[12]',NULL,'Administrator'),
('CAC_L','hue_weight',13,'r_hue_weight[13]',NULL,'Administrator'),
('CAC_L','hue_weight',14,'r_hue_weight[14]',NULL,'Administrator'),
('CAC_L','hue_weight',15,'r_hue_weight[15]',NULL,'Administrator'),
('CAC_L','hue_weight',16,'r_hue_weight[16]',NULL,'Administrator'),
('CAC_L','hue_weight',17,'r_hue_weight[17]',NULL,'Administrator'),
('CAC_L','hue_weight',18,'r_hue_weight[18]',NULL,'Administrator'),
('CAC_L','hue_weight',19,'r_hue_weight[19]',NULL,'Administrator'),
('CAC_L','hue_weight',20,'r_hue_weight[20]',NULL,'Administrator'),
('CAC_L','hue_weight',21,'r_hue_weight[21]',NULL,'Administrator'),
('CAC_L','hue_weight',22,'r_hue_weight[22]',NULL,'Administrator'),
('CAC_L','hue_weight',23,'r_hue_weight[23]',NULL,'Administrator'),
('CAC_L','hue_weight',24,'r_hue_weight[24]',NULL,'Administrator'),
('CAC_L','hue_weight',25,'r_hue_weight[25]',NULL,'Administrator'),
('CAC_L','hue_weight',26,'r_hue_weight[26]',NULL,'Administrator'),
('CAC_L','hue_weight',27,'r_hue_weight[27]',NULL,'Administrator'),
('CAC_L','hue_weight',28,'r_hue_weight[28]',NULL,'Administrator'),
('CAC_L','hue_weight',29,'r_hue_weight[29]',NULL,'Administrator'),
('CAC_L','hue_weight',30,'r_hue_weight[30]',NULL,'Administrator'),
('CAC_L','hue_weight',31,'r_hue_weight[31]',NULL,'Administrator'),
('CAC_L','hue_weight',32,'r_hue_weight[32]',NULL,'Administrator'),
('CAC_L','hue_weight',33,'r_hue_weight[33]',NULL,'Administrator'),
('CAC_L','hue_weight',34,'r_hue_weight[34]',NULL,'Administrator'),
('CAC_L','hue_weight',35,'r_hue_weight[35]',NULL,'Administrator'),
('CAC_L','hue_weight',36,'r_hue_weight[36]',NULL,'Administrator'),
('CAC_L','hue_weight',37,'r_hue_weight[37]',NULL,'Administrator'),
('CAC_L','hue_weight',38,'r_hue_weight[38]',NULL,'Administrator'),
('CAC_L','hue_weight',39,'r_hue_weight[39]',NULL,'Administrator'),
('CAC_L','hue_weight',40,'r_hue_weight[40]',NULL,'Administrator'),
('CAC_L','hue_weight',41,'r_hue_weight[41]',NULL,'Administrator'),
('CAC_L','hue_weight',42,'r_hue_weight[42]',NULL,'Administrator'),
('CAC_L','hue_weight',43,'r_hue_weight[43]',NULL,'Administrator'),
('CAC_L','hue_weight',44,'r_hue_weight[44]',NULL,'Administrator'),
('CAC_L','hue_weight',45,'r_hue_weight[45]',NULL,'Administrator'),
('CAC_L','hue_weight',46,'r_hue_weight[46]',NULL,'Administrator'),
('CAC_L','hue_weight',47,'r_hue_weight[47]',NULL,'Administrator'),
('CAC_L','hue_weight',48,'r_hue_weight[48]',NULL,'Administrator'),
('CAC_L','hue_weight',49,'r_hue_weight[49]',NULL,'Administrator'),
('CAC_L','hue_weight',50,'r_hue_weight[50]',NULL,'Administrator'),
('CAC_L','hue_weight',51,'r_hue_weight[51]',NULL,'Administrator'),
('CAC_L','hue_weight',52,'r_hue_weight[52]',NULL,'Administrator'),
('CAC_L','hue_weight',53,'r_hue_weight[53]',NULL,'Administrator'),
('CAC_L','hue_weight',54,'r_hue_weight[54]',NULL,'Administrator'),
('CAC_L','hue_weight',55,'r_hue_weight[55]',NULL,'Administrator'),
('CAC_L','hue_weight',56,'r_hue_weight[56]',NULL,'Administrator'),
('CAC_L','hue_weight',57,'r_hue_weight[57]',NULL,'Administrator'),
('CAC_L','hue_weight',58,'r_hue_weight[58]',NULL,'Administrator'),
('CAC_L','hue_weight',59,'r_hue_weight[59]',NULL,'Administrator'),
('CAC_L','hue_weight',60,'r_hue_weight[60]',NULL,'Administrator'),
('CAC_L','hue_weight',61,'r_hue_weight[61]',NULL,'Administrator'),
('CAC_L','hue_weight',62,'r_hue_weight[62]',NULL,'Administrator'),
('CAC_L','hue_weight',63,'r_hue_weight[63]',NULL,'Administrator'),
('CAC_L','Color_Weight[0]',0,'r_color_weight[0]',NULL,'Administrator'),
('CAC_L','Color_Weight[1]',0,'r_color_weight[1]',NULL,'Administrator'),
('CAC_L','Color_Weight[2]',0,'r_color_weight[2]',NULL,'Administrator');


INSERT INTO ui_info_regmodule VALUES
('CAC_L','CAC_Enable','RAWDNS_V65_HW_RAWL',0),
('CAC_L','Only_Over_Exposed','RAWDNS_V65_HW_RAWL',0),
('CAC_L','Yellow_Fringle','RAWDNS_V65_HW_RAWL',0),
('CAC_L','CAC_Weight','RAWDNS_V65_HW_RAWL',0),
('CAC_L','Contrast_Low_Thre','RAWDNS_V65_HW_RAWL',0),
('CAC_L','Contrast_High_Thre','RAWDNS_V65_HW_RAWL',0),
('CAC_L','Contrast_Thre','RAWDNS_V65_HW_RAWL',0),
('CAC_L','Over_Exposure_Thre','RAWDNS_V65_HW_RAWL',0),
('CAC_L','Yellow_Sat_Thre','RAWDNS_V65_HW_RAWL',0),
('CAC_L','Purple_Sat_Thre','RAWDNS_V65_HW_RAWL',0),
('CAC_L','hue_weight','RAWDNS_V65_HW_RAWL',0),
('CAC_L','Color_Weight[0]','RAWDNS_V65_HW_RAWL',0),
('CAC_L','Color_Weight[1]','RAWDNS_V65_HW_RAWL',0),
('CAC_L','Color_Weight[2]','RAWDNS_V65_HW_RAWL',0);


DELETE FROM ui_info WHERE module_name='CAC_M';
DELETE FROM ui_info_regmodule WHERE ui_module_name='CAC_M';
INSERT INTO ui_info VALUES 
('CAC_M','CAC_Enable',0,'r_cac_enable',NULL,'Administrator'),
('CAC_M','Only_Over_Exposed',0,'r_only_over_exposed',NULL,'Administrator'),
('CAC_M','Yellow_Fringle',0,'r_yellow_fringe_enable',NULL,'Administrator'),
('CAC_M','CAC_Weight',0,'r_cac_weight',NULL,'Administrator'),
('CAC_M','Contrast_Low_Thre',0,'r_contrast_low_th',NULL,'Administrator'),
('CAC_M','Contrast_High_Thre',0,'r_contrast_high_th',NULL,'Administrator'),
('CAC_M','Contrast_Thre',0,'r_contrast_th',NULL,'Administrator'),
('CAC_M','Over_Exposure_Thre',0,'r_over_exposure_threshold',NULL,'Administrator'),
('CAC_M','Yellow_Sat_Thre',0,'r_yellow_sat_threshold',NULL,'Administrator'),
('CAC_M','Purple_Sat_Thre',0,'r_purple_sat_threshold',NULL,'Administrator'),
('CAC_M','hue_weight',0,'r_hue_weight[0]',NULL,'Administrator'),
('CAC_M','hue_weight',1,'r_hue_weight[1]',NULL,'Administrator'),
('CAC_M','hue_weight',2,'r_hue_weight[2]',NULL,'Administrator'),
('CAC_M','hue_weight',3,'r_hue_weight[3]',NULL,'Administrator'),
('CAC_M','hue_weight',4,'r_hue_weight[4]',NULL,'Administrator'),
('CAC_M','hue_weight',5,'r_hue_weight[5]',NULL,'Administrator'),
('CAC_M','hue_weight',6,'r_hue_weight[6]',NULL,'Administrator'),
('CAC_M','hue_weight',7,'r_hue_weight[7]',NULL,'Administrator'),
('CAC_M','hue_weight',8,'r_hue_weight[8]',NULL,'Administrator'),
('CAC_M','hue_weight',9,'r_hue_weight[9]',NULL,'Administrator'),
('CAC_M','hue_weight',10,'r_hue_weight[10]',NULL,'Administrator'),
('CAC_M','hue_weight',11,'r_hue_weight[11]',NULL,'Administrator'),
('CAC_M','hue_weight',12,'r_hue_weight[12]',NULL,'Administrator'),
('CAC_M','hue_weight',13,'r_hue_weight[13]',NULL,'Administrator'),
('CAC_M','hue_weight',14,'r_hue_weight[14]',NULL,'Administrator'),
('CAC_M','hue_weight',15,'r_hue_weight[15]',NULL,'Administrator'),
('CAC_M','hue_weight',16,'r_hue_weight[16]',NULL,'Administrator'),
('CAC_M','hue_weight',17,'r_hue_weight[17]',NULL,'Administrator'),
('CAC_M','hue_weight',18,'r_hue_weight[18]',NULL,'Administrator'),
('CAC_M','hue_weight',19,'r_hue_weight[19]',NULL,'Administrator'),
('CAC_M','hue_weight',20,'r_hue_weight[20]',NULL,'Administrator'),
('CAC_M','hue_weight',21,'r_hue_weight[21]',NULL,'Administrator'),
('CAC_M','hue_weight',22,'r_hue_weight[22]',NULL,'Administrator'),
('CAC_M','hue_weight',23,'r_hue_weight[23]',NULL,'Administrator'),
('CAC_M','hue_weight',24,'r_hue_weight[24]',NULL,'Administrator'),
('CAC_M','hue_weight',25,'r_hue_weight[25]',NULL,'Administrator'),
('CAC_M','hue_weight',26,'r_hue_weight[26]',NULL,'Administrator'),
('CAC_M','hue_weight',27,'r_hue_weight[27]',NULL,'Administrator'),
('CAC_M','hue_weight',28,'r_hue_weight[28]',NULL,'Administrator'),
('CAC_M','hue_weight',29,'r_hue_weight[29]',NULL,'Administrator'),
('CAC_M','hue_weight',30,'r_hue_weight[30]',NULL,'Administrator'),
('CAC_M','hue_weight',31,'r_hue_weight[31]',NULL,'Administrator'),
('CAC_M','hue_weight',32,'r_hue_weight[32]',NULL,'Administrator'),
('CAC_M','hue_weight',33,'r_hue_weight[33]',NULL,'Administrator'),
('CAC_M','hue_weight',34,'r_hue_weight[34]',NULL,'Administrator'),
('CAC_M','hue_weight',35,'r_hue_weight[35]',NULL,'Administrator'),
('CAC_M','hue_weight',36,'r_hue_weight[36]',NULL,'Administrator'),
('CAC_M','hue_weight',37,'r_hue_weight[37]',NULL,'Administrator'),
('CAC_M','hue_weight',38,'r_hue_weight[38]',NULL,'Administrator'),
('CAC_M','hue_weight',39,'r_hue_weight[39]',NULL,'Administrator'),
('CAC_M','hue_weight',40,'r_hue_weight[40]',NULL,'Administrator'),
('CAC_M','hue_weight',41,'r_hue_weight[41]',NULL,'Administrator'),
('CAC_M','hue_weight',42,'r_hue_weight[42]',NULL,'Administrator'),
('CAC_M','hue_weight',43,'r_hue_weight[43]',NULL,'Administrator'),
('CAC_M','hue_weight',44,'r_hue_weight[44]',NULL,'Administrator'),
('CAC_M','hue_weight',45,'r_hue_weight[45]',NULL,'Administrator'),
('CAC_M','hue_weight',46,'r_hue_weight[46]',NULL,'Administrator'),
('CAC_M','hue_weight',47,'r_hue_weight[47]',NULL,'Administrator'),
('CAC_M','hue_weight',48,'r_hue_weight[48]',NULL,'Administrator'),
('CAC_M','hue_weight',49,'r_hue_weight[49]',NULL,'Administrator'),
('CAC_M','hue_weight',50,'r_hue_weight[50]',NULL,'Administrator'),
('CAC_M','hue_weight',51,'r_hue_weight[51]',NULL,'Administrator'),
('CAC_M','hue_weight',52,'r_hue_weight[52]',NULL,'Administrator'),
('CAC_M','hue_weight',53,'r_hue_weight[53]',NULL,'Administrator'),
('CAC_M','hue_weight',54,'r_hue_weight[54]',NULL,'Administrator'),
('CAC_M','hue_weight',55,'r_hue_weight[55]',NULL,'Administrator'),
('CAC_M','hue_weight',56,'r_hue_weight[56]',NULL,'Administrator'),
('CAC_M','hue_weight',57,'r_hue_weight[57]',NULL,'Administrator'),
('CAC_M','hue_weight',58,'r_hue_weight[58]',NULL,'Administrator'),
('CAC_M','hue_weight',59,'r_hue_weight[59]',NULL,'Administrator'),
('CAC_M','hue_weight',60,'r_hue_weight[60]',NULL,'Administrator'),
('CAC_M','hue_weight',61,'r_hue_weight[61]',NULL,'Administrator'),
('CAC_M','hue_weight',62,'r_hue_weight[62]',NULL,'Administrator'),
('CAC_M','hue_weight',63,'r_hue_weight[63]',NULL,'Administrator'),
('CAC_M','Color_Weight[0]',0,'r_color_weight[0]',NULL,'Administrator'),
('CAC_M','Color_Weight[1]',0,'r_color_weight[1]',NULL,'Administrator'),
('CAC_M','Color_Weight[2]',0,'r_color_weight[2]',NULL,'Administrator');


INSERT INTO ui_info_regmodule VALUES
('CAC_M','CAC_Enable','RAWDNS_V65_HW_RAWM',0),
('CAC_M','Only_Over_Exposed','RAWDNS_V65_HW_RAWM',0),
('CAC_M','Yellow_Fringle','RAWDNS_V65_HW_RAWM',0),
('CAC_M','CAC_Weight','RAWDNS_V65_HW_RAWM',0),
('CAC_M','Contrast_Low_Thre','RAWDNS_V65_HW_RAWM',0),
('CAC_M','Contrast_High_Thre','RAWDNS_V65_HW_RAWM',0),
('CAC_M','Contrast_Thre','RAWDNS_V65_HW_RAWM',0),
('CAC_M','Over_Exposure_Thre','RAWDNS_V65_HW_RAWM',0),
('CAC_M','Yellow_Sat_Thre','RAWDNS_V65_HW_RAWM',0),
('CAC_M','Purple_Sat_Thre','RAWDNS_V65_HW_RAWM',0),
('CAC_M','hue_weight','RAWDNS_V65_HW_RAWM',0),
('CAC_M','Color_Weight[0]','RAWDNS_V65_HW_RAWM',0),
('CAC_M','Color_Weight[1]','RAWDNS_V65_HW_RAWM',0),
('CAC_M','Color_Weight[2]','RAWDNS_V65_HW_RAWM',0);


DELETE FROM ui_info WHERE module_name='CAC_S';
DELETE FROM ui_info_regmodule WHERE ui_module_name='CAC_S';
INSERT INTO ui_info VALUES 
('CAC_S','CAC_Enable',0,'r_bCACEnable',NULL,'Administrator'),
('CAC_S','Hue_Enable',0,'r_bCACHueEnable',NULL,'Administrator'),
('CAC_S','Over_Exposure_Thre',0,'r_oe_thr',NULL,'Administrator'),
('CAC_S','Over_Expo_Rat',0,'r_oe_rat',NULL,'Administrator'),
('CAC_S','Contrast_Coe[0]',0,'r_nContrastCoe[0]',NULL,'Administrator'),
('CAC_S','Contrast_Coe[1]',0,'r_nContrastCoe[1]',NULL,'Administrator'),
('CAC_S','Contrast_Coe[2]',0,'r_nContrastCoe[2]',NULL,'Administrator'),
('CAC_S','Contrast_Coe[3]',0,'r_nContrastCoe[3]',NULL,'Administrator'),
('CAC_S','Contrast_Coe[4]',0,'r_nContrastCoe[4]',NULL,'Administrator'),
('CAC_S','Contrast_Coe[5]',0,'r_nContrastCoe[5]',NULL,'Administrator'),
('CAC_S','Contrast_Coe[6]',0,'r_nContrastCoe[6]',NULL,'Administrator'),
('CAC_S','Contrast_Coe[7]',0,'r_nContrastCoe[7]',NULL,'Administrator'),
('CAC_S','Contrast_Int[0]',0,'r_nContrastInt[0]',NULL,'Administrator'),
('CAC_S','Contrast_Int[1]',0,'r_nContrastInt[1]',NULL,'Administrator'),
('CAC_S','Contrast_Int[2]',0,'r_nContrastInt[2]',NULL,'Administrator'),
('CAC_S','Contrast_Int[3]',0,'r_nContrastInt[3]',NULL,'Administrator'),
('CAC_S','Contrast_Int[4]',0,'r_nContrastInt[4]',NULL,'Administrator'),
('CAC_S','Contrast_Int[5]',0,'r_nContrastInt[5]',NULL,'Administrator'),
('CAC_S','Contrast_Int[6]',0,'r_nContrastInt[6]',NULL,'Administrator'),
('CAC_S','Contrast_Int[7]',0,'r_nContrastInt[7]',NULL,'Administrator'),
('CAC_S','Contrast_Rat[0]',0,'r_nContrastRat[0]',NULL,'Administrator'),
('CAC_S','Contrast_Rat[1]',0,'r_nContrastRat[1]',NULL,'Administrator'),
('CAC_S','Contrast_Rat[2]',0,'r_nContrastRat[2]',NULL,'Administrator'),
('CAC_S','Contrast_Rat[3]',0,'r_nContrastRat[3]',NULL,'Administrator'),
('CAC_S','Contrast_Rat[4]',0,'r_nContrastRat[4]',NULL,'Administrator'),
('CAC_S','Contrast_Rat[5]',0,'r_nContrastRat[5]',NULL,'Administrator'),
('CAC_S','Contrast_Rat[6]',0,'r_nContrastRat[6]',NULL,'Administrator'),
('CAC_S','Contrast_Rat[7]',0,'r_nContrastRat[7]',NULL,'Administrator'),
('CAC_S','Hue_Rat',0,'r_hue_rat',NULL,'Administrator'),
('CAC_S','CAC_Rat',0,'r_cac_rat',NULL,'Administrator'),
('CAC_S', 'Gain_Node[0]', 0, 'r_nGainNode[0]', NULL, 'Administrator'),
('CAC_S', 'Gain_Node[1]', 0, 'r_nGainNode[1]', NULL, 'Administrator'),
('CAC_S', 'Gain_Node[2]', 0, 'r_nGainNode[2]', NULL, 'Administrator'),
('CAC_S', 'Gain_Node[3]', 0, 'r_nGainNode[3]', NULL, 'Administrator'),
('CAC_S', 'Gain_Node[4]', 0, 'r_nGainNode[4]', NULL, 'Administrator'),
('CAC_S', 'Gain_Node[5]', 0, 'r_nGainNode[5]', NULL, 'Administrator'),
('CAC_S', 'Gain_Node[6]', 0, 'r_nGainNode[6]', NULL, 'Administrator'),
('CAC_S', 'Gain_Node[7]', 0, 'r_nGainNode[7]', NULL, 'Administrator');

INSERT INTO ui_info_regmodule VALUES
('CAC_S','CAC_Enable','CIP_S',1),
('CAC_S','Hue_Enable','CIP_S',1),
('CAC_S','Over_Exposure_Thre','CBAYERCIP_V60_HW_RAWS',0),
('CAC_S','Over_Expo_Rat','CBAYERCIP_V60_HW_RAWS',0),
('CAC_S','Contrast_Coe[0]','CIP_S',1),
('CAC_S','Contrast_Coe[1]','CIP_S',1),
('CAC_S','Contrast_Coe[2]','CIP_S',1),
('CAC_S','Contrast_Coe[3]','CIP_S',1),
('CAC_S','Contrast_Coe[4]','CIP_S',1),
('CAC_S','Contrast_Coe[5]','CIP_S',1),
('CAC_S','Contrast_Coe[6]','CIP_S',1),
('CAC_S','Contrast_Coe[7]','CIP_S',1),
('CAC_S','Contrast_Int[0]','CIP_S',1),
('CAC_S','Contrast_Int[1]','CIP_S',1),
('CAC_S','Contrast_Int[2]','CIP_S',1),
('CAC_S','Contrast_Int[3]','CIP_S',1),
('CAC_S','Contrast_Int[4]','CIP_S',1),
('CAC_S','Contrast_Int[5]','CIP_S',1),
('CAC_S','Contrast_Int[6]','CIP_S',1),
('CAC_S','Contrast_Int[7]','CIP_S',1),
('CAC_S','Contrast_Rat[0]','CIP_S',1),
('CAC_S','Contrast_Rat[1]','CIP_S',1),
('CAC_S','Contrast_Rat[2]','CIP_S',1),
('CAC_S','Contrast_Rat[3]','CIP_S',1),
('CAC_S','Contrast_Rat[4]','CIP_S',1),
('CAC_S','Contrast_Rat[5]','CIP_S',1),
('CAC_S','Contrast_Rat[6]','CIP_S',1),
('CAC_S','Contrast_Rat[7]','CIP_S',1),
('CAC_S','Hue_Rat','CBAYERCIP_V60_HW_RAWS',0),
('CAC_S','CAC_Rat','CBAYERCIP_V60_HW_RAWS',0),
('CAC_S','Gain_Node[0]','CIP_S',1),
('CAC_S','Gain_Node[1]','CIP_S',1),
('CAC_S','Gain_Node[2]','CIP_S',1),
('CAC_S','Gain_Node[3]','CIP_S',1),
('CAC_S','Gain_Node[4]','CIP_S',1),
('CAC_S','Gain_Node[5]','CIP_S',1),
('CAC_S','Gain_Node[6]','CIP_S',1),
('CAC_S','Gain_Node[7]','CIP_S',1);


DELETE FROM ui_info WHERE module_name='CAC_LFS';
DELETE FROM ui_info_regmodule WHERE ui_module_name='CAC_LFS';
INSERT INTO ui_info VALUES 
('CAC_LFS','CAC_Enable',0,'r_bCACEnable',NULL,'Administrator'),
('CAC_LFS','Hue_Enable',0,'r_bCACHueEnable',NULL,'Administrator'),
('CAC_LFS','Over_Exposure_Thre',0,'r_oe_thr',NULL,'Administrator'),
('CAC_LFS','Over_Expo_Rat',0,'r_oe_rat',NULL,'Administrator'),
('CAC_LFS','Contrast_Coe[0]',0,'r_nContrastCoe[0]',NULL,'Administrator'),
('CAC_LFS','Contrast_Coe[1]',0,'r_nContrastCoe[1]',NULL,'Administrator'),
('CAC_LFS','Contrast_Coe[2]',0,'r_nContrastCoe[2]',NULL,'Administrator'),
('CAC_LFS','Contrast_Coe[3]',0,'r_nContrastCoe[3]',NULL,'Administrator'),
('CAC_LFS','Contrast_Coe[4]',0,'r_nContrastCoe[4]',NULL,'Administrator'),
('CAC_LFS','Contrast_Coe[5]',0,'r_nContrastCoe[5]',NULL,'Administrator'),
('CAC_LFS','Contrast_Coe[6]',0,'r_nContrastCoe[6]',NULL,'Administrator'),
('CAC_LFS','Contrast_Coe[7]',0,'r_nContrastCoe[7]',NULL,'Administrator'),
('CAC_LFS','Contrast_Int[0]',0,'r_nContrastInt[0]',NULL,'Administrator'),
('CAC_LFS','Contrast_Int[1]',0,'r_nContrastInt[1]',NULL,'Administrator'),
('CAC_LFS','Contrast_Int[2]',0,'r_nContrastInt[2]',NULL,'Administrator'),
('CAC_LFS','Contrast_Int[3]',0,'r_nContrastInt[3]',NULL,'Administrator'),
('CAC_LFS','Contrast_Int[4]',0,'r_nContrastInt[4]',NULL,'Administrator'),
('CAC_LFS','Contrast_Int[5]',0,'r_nContrastInt[5]',NULL,'Administrator'),
('CAC_LFS','Contrast_Int[6]',0,'r_nContrastInt[6]',NULL,'Administrator'),
('CAC_LFS','Contrast_Int[7]',0,'r_nContrastInt[7]',NULL,'Administrator'),
('CAC_LFS','Contrast_Rat[0]',0,'r_nContrastRat[0]',NULL,'Administrator'),
('CAC_LFS','Contrast_Rat[1]',0,'r_nContrastRat[1]',NULL,'Administrator'),
('CAC_LFS','Contrast_Rat[2]',0,'r_nContrastRat[2]',NULL,'Administrator'),
('CAC_LFS','Contrast_Rat[3]',0,'r_nContrastRat[3]',NULL,'Administrator'),
('CAC_LFS','Contrast_Rat[4]',0,'r_nContrastRat[4]',NULL,'Administrator'),
('CAC_LFS','Contrast_Rat[5]',0,'r_nContrastRat[5]',NULL,'Administrator'),
('CAC_LFS','Contrast_Rat[6]',0,'r_nContrastRat[6]',NULL,'Administrator'),
('CAC_LFS','Contrast_Rat[7]',0,'r_nContrastRat[7]',NULL,'Administrator'),
('CAC_LFS','Hue_Rat',0,'r_hue_rat',NULL,'Administrator'),
('CAC_LFS','CAC_Rat',0,'r_cac_rat',NULL,'Administrator'),
('CAC_LFS', 'Gain_Node[0]', 0, 'r_nGainNode[0]', NULL, 'Administrator'),
('CAC_LFS', 'Gain_Node[1]', 0, 'r_nGainNode[1]', NULL, 'Administrator'),
('CAC_LFS', 'Gain_Node[2]', 0, 'r_nGainNode[2]', NULL, 'Administrator'),
('CAC_LFS', 'Gain_Node[3]', 0, 'r_nGainNode[3]', NULL, 'Administrator'),
('CAC_LFS', 'Gain_Node[4]', 0, 'r_nGainNode[4]', NULL, 'Administrator'),
('CAC_LFS', 'Gain_Node[5]', 0, 'r_nGainNode[5]', NULL, 'Administrator'),
('CAC_LFS', 'Gain_Node[6]', 0, 'r_nGainNode[6]', NULL, 'Administrator'),
('CAC_LFS', 'Gain_Node[7]', 0, 'r_nGainNode[7]', NULL, 'Administrator');

INSERT INTO ui_info_regmodule VALUES
('CAC_LFS','CAC_Enable','CIP_V',1),
('CAC_LFS','Hue_Enable','CIP_V',1),
('CAC_LFS','Over_Exposure_Thre','CBAYERCIP_V60_HW_RAWV',0),
('CAC_LFS','Over_Expo_Rat','CBAYERCIP_V60_HW_RAWV',0),
('CAC_LFS','Contrast_Coe[0]','CIP_V',1),
('CAC_LFS','Contrast_Coe[1]','CIP_V',1),
('CAC_LFS','Contrast_Coe[2]','CIP_V',1),
('CAC_LFS','Contrast_Coe[3]','CIP_V',1),
('CAC_LFS','Contrast_Coe[4]','CIP_V',1),
('CAC_LFS','Contrast_Coe[5]','CIP_V',1),
('CAC_LFS','Contrast_Coe[6]','CIP_V',1),
('CAC_LFS','Contrast_Coe[7]','CIP_V',1),
('CAC_LFS','Contrast_Int[0]','CIP_V',1),
('CAC_LFS','Contrast_Int[1]','CIP_V',1),
('CAC_LFS','Contrast_Int[2]','CIP_V',1),
('CAC_LFS','Contrast_Int[3]','CIP_V',1),
('CAC_LFS','Contrast_Int[4]','CIP_V',1),
('CAC_LFS','Contrast_Int[5]','CIP_V',1),
('CAC_LFS','Contrast_Int[6]','CIP_V',1),
('CAC_LFS','Contrast_Int[7]','CIP_V',1),
('CAC_LFS','Contrast_Rat[0]','CIP_V',1),
('CAC_LFS','Contrast_Rat[1]','CIP_V',1),
('CAC_LFS','Contrast_Rat[2]','CIP_V',1),
('CAC_LFS','Contrast_Rat[3]','CIP_V',1),
('CAC_LFS','Contrast_Rat[4]','CIP_V',1),
('CAC_LFS','Contrast_Rat[5]','CIP_V',1),
('CAC_LFS','Contrast_Rat[6]','CIP_V',1),
('CAC_LFS','Contrast_Rat[7]','CIP_V',1),
('CAC_LFS','Hue_Rat','CBAYERCIP_V60_HW_RAWV',0),
('CAC_LFS','CAC_Rat','CBAYERCIP_V60_HW_RAWV',0),
('CAC_LFS','Gain_Node[0]','CIP_V',1),
('CAC_LFS','Gain_Node[1]','CIP_V',1),
('CAC_LFS','Gain_Node[2]','CIP_V',1),
('CAC_LFS','Gain_Node[3]','CIP_V',1),
('CAC_LFS','Gain_Node[4]','CIP_V',1),
('CAC_LFS','Gain_Node[5]','CIP_V',1),
('CAC_LFS','Gain_Node[6]','CIP_V',1),
('CAC_LFS','Gain_Node[7]','CIP_V',1);
