DELETE FROM ui_info WHERE module_name='Saturation';
DELETE FROM ui_info_regmodule WHERE ui_module_name='Saturation';
INSERT INTO ui_info VALUES 
('Saturation','GainSatEnable', 0,'r_bGainSatEnable',NULL,'Administrator'),
('Saturation','Saturation', 0,'r_nSaturation',NULL,'Administrator'),
('Saturation','SatISOList[0]', 0,'r_pSatIsoList[0]',NULL,'Administrator'),
('Saturation','SatISOList[1]', 0,'r_pSatIsoList[1]',NULL,'Administrator'),
('Saturation','SatISOList[2]', 0,'r_pSatIsoList[2]',NULL,'Administrator'),
('Saturation','SatISOList[3]', 0,'r_pSatIsoList[3]',NULL,'Administrator'),
('Saturation','SatISOList[4]', 0,'r_pSatIsoList[4]',NULL,'Administrator'),
('Saturation','SatISOList[5]', 0,'r_pSatIsoList[5]',NULL,'Administrator'),
('Saturation','SatISOList[6]', 0,'r_pSatIsoList[6]',NULL,'Administrator'),
('Saturation','SatISOList[7]', 0,'r_pSatIsoList[7]',NULL,'Administrator'),
('Saturation','SatStrList', 0,'r_pSatStrList[0]',NULL,'Administrator'),
('Saturation','SatStrList', 1,'r_pSatStrList[1]',NULL,'Administrator'),
('Saturation','SatStrList', 2,'r_pSatStrList[2]',NULL,'Administrator'),
('Saturation','SatStrList', 3,'r_pSatStrList[3]',NULL,'Administrator'),
('Saturation','SatStrList', 4,'r_pSatStrList[4]',NULL,'Administrator'),
('Saturation','SatStrList', 5,'r_pSatStrList[5]',NULL,'Administrator'),
('Saturation','SatStrList', 6,'r_pSatStrList[6]',NULL,'Administrator'),
('Saturation','SatStrList', 7,'r_pSatStrList[7]',NULL,'Administrator'),
('Saturation','GainNode[0]', 0,'r_nGainNode_0',NULL,'Administrator'),
('Saturation','GainNode[1]', 0,'r_nGainNode_1',NULL,'Administrator'),
('Saturation','GainNode[2]', 0,'r_nGainNode_2',NULL,'Administrator'),
('Saturation','GainNode[3]', 0,'r_nGainNode_3',NULL,'Administrator'),
('Saturation','GainNode[4]', 0,'r_nGainNode_4',NULL,'Administrator'),
('Saturation','GainNode[4]_IR_AB', 0,'r_nGainNode_4',NULL,'Administrator'),
('Saturation','GainNode[4]_RGB_AB', 0,'r_nGainNode_4',NULL,'Administrator'),
('Saturation','GainNode[5]', 0,'r_nGainNode_5',NULL,'Administrator'),
('Saturation','GainNode[5]_IR_AB', 0,'r_nGainNode_5',NULL,'Administrator'),
('Saturation','GainNode[5]_RGB_AB', 0,'r_nGainNode_5',NULL,'Administrator'),
('Saturation','GainNode[6]', 0,'r_nGainNode_6',NULL,'Administrator'),
('Saturation','GainNode[6]_IR_AB', 0,'r_nGainNode_6',NULL,'Administrator'),
('Saturation','GainNode[6]_RGB_AB', 0,'r_nGainNode_6',NULL,'Administrator'),
('Saturation','GainNode[7]', 0,'r_nGainNode_7',NULL,'Administrator'),
('Saturation','GainNode[7]_IR_AB', 0,'r_nGainNode_7',NULL,'Administrator'),
('Saturation','GainNode[7]_RGB_AB', 0,'r_nGainNode_7',NULL,'Administrator'),
('Saturation','SatLTH', 0,'r_nSatLTH_0',NULL,'Administrator'),
('Saturation','SatLTH', 1,'r_nSatLTH_1',NULL,'Administrator'),
('Saturation','SatLTH', 2,'r_nSatLTH_2',NULL,'Administrator'),
('Saturation','SatLTH', 3,'r_nSatLTH_3',NULL,'Administrator'),
('Saturation','SatLTH', 4,'r_nSatLTH_4',NULL,'Administrator'),
('Saturation','SatLTH', 5,'r_nSatLTH_5',NULL,'Administrator'),
('Saturation','SatLTH', 6,'r_nSatLTH_6',NULL,'Administrator'),
('Saturation','SatLTH', 7,'r_nSatLTH_7',NULL,'Administrator'),
('Saturation','SatHTH', 0,'r_nSatHTH_0',NULL,'Administrator'),
('Saturation','SatHTH', 1,'r_nSatHTH_1',NULL,'Administrator'),
('Saturation','SatHTH', 2,'r_nSatHTH_2',NULL,'Administrator'),
('Saturation','SatHTH', 3,'r_nSatHTH_3',NULL,'Administrator'),
('Saturation','SatHTH', 4,'r_nSatHTH_4',NULL,'Administrator'),
('Saturation','SatHTH', 5,'r_nSatHTH_5',NULL,'Administrator'),
('Saturation','SatHTH', 6,'r_nSatHTH_6',NULL,'Administrator'),
('Saturation','SatHTH', 7,'r_nSatHTH_7',NULL,'Administrator'),
('Saturation','SatLTar', 0,'r_nSatLTar_0',NULL,'Administrator'),
('Saturation','SatLTar', 1,'r_nSatLTar_1',NULL,'Administrator'),
('Saturation','SatLTar', 2,'r_nSatLTar_2',NULL,'Administrator'),
('Saturation','SatLTar', 3,'r_nSatLTar_3',NULL,'Administrator'),
('Saturation','SatLTar', 4,'r_nSatLTar_4',NULL,'Administrator'),
('Saturation','SatLTar', 5,'r_nSatLTar_5',NULL,'Administrator'),
('Saturation','SatLTar', 6,'r_nSatLTar_6',NULL,'Administrator'),
('Saturation','SatLTar', 7,'r_nSatLTar_7',NULL,'Administrator'),
('Saturation','SatHTar', 0,'r_nSatHTar_0',NULL,'Administrator'),
('Saturation','SatHTar', 1,'r_nSatHTar_1',NULL,'Administrator'),
('Saturation','SatHTar', 2,'r_nSatHTar_2',NULL,'Administrator'),
('Saturation','SatHTar', 3,'r_nSatHTar_3',NULL,'Administrator'),
('Saturation','SatHTar', 4,'r_nSatHTar_4',NULL,'Administrator'),
('Saturation','SatHTar', 5,'r_nSatHTar_5',NULL,'Administrator'),
('Saturation','SatHTar', 6,'r_nSatHTar_6',NULL,'Administrator'),
('Saturation','SatHTar', 7,'r_nSatHTar_7',NULL,'Administrator'),
('Saturation','SatRate', 0,'r_nSatRate_0',NULL,'Administrator'),
('Saturation','SatRate', 1,'r_nSatRate_1',NULL,'Administrator'),
('Saturation','SatRate', 2,'r_nSatRate_2',NULL,'Administrator'),
('Saturation','SatRate', 3,'r_nSatRate_3',NULL,'Administrator'),
('Saturation','SatRate', 4,'r_nSatRate_4',NULL,'Administrator'),
('Saturation','SatRate', 5,'r_nSatRate_5',NULL,'Administrator'),
('Saturation','SatRate', 6,'r_nSatRate_6',NULL,'Administrator'),
('Saturation','SatRate', 7,'r_nSatRate_7',NULL,'Administrator'),
('Saturation', 'CurGain', 0, 'current L Gain', NULL, 'Administrator'),
('Saturation', 'SatAdjEnable', 0, 'r_bSatAdjEnable', NULL, 'Administrator'),
('Saturation','Current Gain L',0,'current L Gain',NULL,'Administrator'),
('Saturation','Current Expo L',0,'current L Expo',NULL,'Administrator');

INSERT INTO ui_info_regmodule VALUES
('Saturation','GainSatEnable','CURVE',1),
('Saturation','Saturation','CURVE',1),
('Saturation','SatISOList[0]', 'CURVE',1),
('Saturation','SatISOList[1]', 'CURVE',1),
('Saturation','SatISOList[2]', 'CURVE',1),
('Saturation','SatISOList[3]', 'CURVE',1),
('Saturation','SatISOList[4]', 'CURVE',1),
('Saturation','SatISOList[5]', 'CURVE',1),
('Saturation','SatISOList[6]', 'CURVE',1),
('Saturation','SatISOList[7]', 'CURVE',1),
('Saturation','SatStrList[8]', 'CURVE',1),
('Saturation','SatStrList','CURVE',1),
('Saturation','GainNode[0]','YUVDNS',1),
('Saturation','GainNode[1]','YUVDNS',1),
('Saturation','GainNode[2]','YUVDNS',1),
('Saturation','GainNode[3]','YUVDNS',1),
('Saturation','GainNode[4]','YUVDNS',1),
('Saturation','GainNode[4]_IR_AB','YUVDNS_IR_AB',1),
('Saturation','GainNode[4]_RGB_AB','YUVDNS_RGB_AB',1),
('Saturation','GainNode[5]','YUVDNS',1),
('Saturation','GainNode[5]_IR_AB','YUVDNS_IR_AB',1),
('Saturation','GainNode[5]_RGB_AB','YUVDNS_RGB_AB',1),
('Saturation','GainNode[6]','YUVDNS',1),
('Saturation','GainNode[6]_IR_AB','YUVDNS_IR_AB',1),
('Saturation','GainNode[6]_RGB_AB','YUVDNS_RGB_AB',1),
('Saturation','GainNode[7]','YUVDNS',1),
('Saturation','GainNode[7]_IR_AB','YUVDNS_IR_AB',1),
('Saturation','GainNode[7]_RGB_AB','YUVDNS_RGB_AB',1),
('Saturation','SatLTH','YUVDNS',1),
('Saturation','SatHTH','YUVDNS',1),
('Saturation','SatLTar','YUVDNS',1),
('Saturation','SatHTar','YUVDNS',1),
('Saturation','CurGain','PipeCtrl',1),
('Saturation','SatRate','YUVDNS',1),
('Saturation','SatAdjEnable','YUVDNS',1),
('Saturation','Current Gain L','PipeCtrl',1),
('Saturation','Current Expo L','PipeCtrl',1);
