DELETE FROM ui_info WHERE module_name='PreCCM';
DELETE FROM ui_info_regmodule WHERE ui_module_name='PreCCM';
INSERT INTO ui_info VALUES 
('PreCCM', 'PreCCMEnableS', 0, 'bPreCCMEnable[0]', NULL, 'Administrator'),
('PreCCM', 'PreCCMEnableV', 0, 'bPreCCMEnable[1]', NULL, 'Administrator'),
('PreCCM', 'pCT[0]S', 0, 'r_pCT[0]', NULL, 'Administrator'),
('PreCCM', 'pCT[1]S', 0, 'r_pCT[1]', NULL, 'Administrator'),
('PreCCM', 'pCT[2]S', 0, 'r_pCT[2]', NULL, 'Administrator'),
('PreCCM', 'pCT[3]S', 0, 'r_pCT[3]', NULL, 'Administrator'),
('PreCCM', 'pCT[0]V', 0, 'r_pCT[0]', NULL, 'Administrator'),
('PreCCM', 'pCT[1]V', 0, 'r_pCT[1]', NULL, 'Administrator'),
('PreCCM', 'pCT[2]V', 0, 'r_pCT[2]', NULL, 'Administrator'),
('PreCCM', 'pCT[3]V', 0, 'r_pCT[3]', NULL, 'Administrator'),
('PreCCM', 'A21S', 0, 'r_pCCMatrixA[0]', NULL, 'Administrator'),
('PreCCM', 'A20S', 0, 'r_pCCMatrixA[1]', NULL, 'Administrator'),
('PreCCM', 'A12S', 0, 'r_pCCMatrixA[2]', NULL, 'Administrator'),
('PreCCM', 'A10S', 0, 'r_pCCMatrixA[3]', NULL, 'Administrator'),
('PreCCM', 'A02S', 0, 'r_pCCMatrixA[4]', NULL, 'Administrator'),
('PreCCM', 'A01S', 0, 'r_pCCMatrixA[5]', NULL, 'Administrator'),
('PreCCM', 'B21S', 0, 'r_pCCMatrixB[0]', NULL, 'Administrator'),
('PreCCM', 'B20S', 0, 'r_pCCMatrixB[1]', NULL, 'Administrator'),
('PreCCM', 'B12S', 0, 'r_pCCMatrixB[2]', NULL, 'Administrator'),
('PreCCM', 'B10S', 0, 'r_pCCMatrixB[3]', NULL, 'Administrator'),
('PreCCM', 'B02S', 0, 'r_pCCMatrixB[4]', NULL, 'Administrator'),
('PreCCM', 'B01S', 0, 'r_pCCMatrixB[5]', NULL, 'Administrator'),
('PreCCM', 'C21S', 0, 'r_pCCMatrixC[0]', NULL, 'Administrator'),
('PreCCM', 'C20S', 0, 'r_pCCMatrixC[1]', NULL, 'Administrator'),
('PreCCM', 'C12S', 0, 'r_pCCMatrixC[2]', NULL, 'Administrator'),
('PreCCM', 'C10S', 0, 'r_pCCMatrixC[3]', NULL, 'Administrator'),
('PreCCM', 'C02S', 0, 'r_pCCMatrixC[4]', NULL, 'Administrator'),
('PreCCM', 'C01S', 0, 'r_pCCMatrixC[5]', NULL, 'Administrator'),
('PreCCM', 'Current21S', 0, 'r_pCurrentCCM[0]', NULL, 'Administrator'),
('PreCCM', 'Current20S', 0, 'r_pCurrentCCM[1]', NULL, 'Administrator'),
('PreCCM', 'Current12S', 0, 'r_pCurrentCCM[2]', NULL, 'Administrator'),
('PreCCM', 'Current10S', 0, 'r_pCurrentCCM[3]', NULL, 'Administrator'),
('PreCCM', 'Current02S', 0, 'r_pCurrentCCM[4]', NULL, 'Administrator'),
('PreCCM', 'Current01S', 0, 'r_pCurrentCCM[5]', NULL, 'Administrator'),
('PreCCM', 'A21V', 0, 'r_pCCMatrixA[0]', NULL, 'Administrator'),
('PreCCM', 'A20V', 0, 'r_pCCMatrixA[1]', NULL, 'Administrator'),
('PreCCM', 'A12V', 0, 'r_pCCMatrixA[2]', NULL, 'Administrator'),
('PreCCM', 'A10V', 0, 'r_pCCMatrixA[3]', NULL, 'Administrator'),
('PreCCM', 'A02V', 0, 'r_pCCMatrixA[4]', NULL, 'Administrator'),
('PreCCM', 'A01V', 0, 'r_pCCMatrixA[5]', NULL, 'Administrator'),
('PreCCM', 'B21V', 0, 'r_pCCMatrixB[0]', NULL, 'Administrator'),
('PreCCM', 'B20V', 0, 'r_pCCMatrixB[1]', NULL, 'Administrator'),
('PreCCM', 'B12V', 0, 'r_pCCMatrixB[2]', NULL, 'Administrator'),
('PreCCM', 'B10V', 0, 'r_pCCMatrixB[3]', NULL, 'Administrator'),
('PreCCM', 'B02V', 0, 'r_pCCMatrixB[4]', NULL, 'Administrator'),
('PreCCM', 'B01V', 0, 'r_pCCMatrixB[5]', NULL, 'Administrator'),
('PreCCM', 'C21V', 0, 'r_pCCMatrixC[0]', NULL, 'Administrator'),
('PreCCM', 'C20V', 0, 'r_pCCMatrixC[1]', NULL, 'Administrator'),
('PreCCM', 'C12V', 0, 'r_pCCMatrixC[2]', NULL, 'Administrator'),
('PreCCM', 'C10V', 0, 'r_pCCMatrixC[3]', NULL, 'Administrator'),
('PreCCM', 'C02V', 0, 'r_pCCMatrixC[4]', NULL, 'Administrator'),
('PreCCM', 'C01V', 0, 'r_pCCMatrixC[5]', NULL, 'Administrator'),
('PreCCM', 'Current21V', 0, 'r_pCurrentCCM[0]', NULL, 'Administrator'),
('PreCCM', 'Current20V', 0, 'r_pCurrentCCM[1]', NULL, 'Administrator'),
('PreCCM', 'Current12V', 0, 'r_pCurrentCCM[2]', NULL, 'Administrator'),
('PreCCM', 'Current10V', 0, 'r_pCurrentCCM[3]', NULL, 'Administrator'),
('PreCCM', 'Current02V', 0, 'r_pCurrentCCM[4]', NULL, 'Administrator'),
('PreCCM', 'Current01V', 0, 'r_pCurrentCCM[5]', NULL, 'Administrator'),
('PreCCM','Current Gain B',0,'current B Gain',NULL,'Administrator'),
('PreCCM','Current Gain R',0,'current R Gain',NULL,'Administrator');
INSERT INTO ui_info_regmodule VALUES
('PreCCM','Current Gain B','PipeCtrl',1),
('PreCCM','Current Gain R','PipeCtrl',1);