DELETE FROM ui_info WHERE module_name='AWB';
DELETE FROM ui_info_regmodule WHERE ui_module_name='AWB';
INSERT INTO ui_info VALUES 
('AWB', 'Manual AWB', 0, 'bManualAWB', NULL, 'Administrator'),
('AWB', 'StepChange Enable', 0, 'bStepChangeEn', NULL, 'Administrator'),
('AWB', 'Man B Gain', 0, 'pManualAWBGain[0]', NULL, 'Administrator'),
('AWB', 'Man G Gain', 0, 'pManualAWBGain[1]', NULL, 'Administrator'),
('AWB', 'Man R Gain', 0, 'pManualAWBGain[2]', NULL, 'Administrator'),
('AWB', 'MaxAWBGain 0', 0, 'pMaxAWBGain[0]', NULL, 'Administrator'),
('AWB', 'MaxAWBGain 1', 0, 'pMaxAWBGain[1]', NULL, 'Administrator'),
('AWB', 'MinAWBGain 0', 0, 'pMinAWBGain[0]', NULL, 'Administrator'),
('AWB', 'MinAWBGain 1', 0, 'pMinAWBGain[1]', NULL, 'Administrator'),
('AWB', 'Freeze AWB', 0, 'bFreezeAWB', NULL, 'Administrator'),
('AWB', 'Convergence', 0, 'ENG0_nConvergence', NULL, 'Administrator'),
('AWB', 'ROI Left', 0, 'r_border[0]', NULL, 'Administrator'),
('AWB', 'ROI Right', 0, 'r_border[1]', NULL, 'Administrator'),
('AWB', 'ROI Top', 0, 'r_border[2]', NULL, 'Administrator'),
('AWB', 'ROI Bottom', 0, 'r_border[3]', NULL, 'Administrator'),
('AWB', 'GreenOption Enable', 0, 'ENG0_bGreenOption', NULL, 'Administrator'),
('AWB', 'SkyOption Enable', 0, 'ENG0_bSkyOption', NULL, 'Administrator'),
('AWB', 'Green Luma 0', 0, 'ENG0_pGreenLuma[0]', NULL, 'Administrator'),
('AWB', 'Green Luma 1', 0, 'ENG0_pGreenLuma[1]', NULL, 'Administrator'),
('AWB', 'Green Luma 2', 0, 'ENG0_pGreenLuma[2]', NULL, 'Administrator'),
('AWB', 'Green Luma 3', 0, 'ENG0_pGreenLuma[3]', NULL, 'Administrator'),
('AWB', 'Sky BG', 0, 'ENG0_nSkyBG', NULL, 'Administrator'),
('AWB', 'GreenCountRatioThr', 0, 'ENG0_nGreenCountRatioThr', NULL, 'Administrator'),
('AWB', 'Green FixedBG 0', 0, 'ENG0_pGreenFixedBG[0]', NULL, 'Administrator'),
('AWB', 'Green FixedBG 1', 0, 'ENG0_pGreenFixedBG[1]', NULL, 'Administrator'),
('AWB', 'Green FixedBG 2', 0, 'ENG0_pGreenFixedBG[2]', NULL, 'Administrator'),
('AWB', 'Green FixedBG 3', 0, 'ENG0_pGreenFixedBG[3]', NULL, 'Administrator'),
('AWB', 'SkyLuma Thr', 0, 'ENG0_nSkyLumaThre', NULL, 'Administrator'),
('AWB', 'Sky RG', 0, 'ENG0_nSkyRG', NULL, 'Administrator'),
('AWB', 'Green FixedRG 0', 0, 'ENG0_pGreenFixedRG[0]', NULL, 'Administrator'),
('AWB', 'Green FixedRG 1', 0, 'ENG0_pGreenFixedRG[1]', NULL, 'Administrator'),
('AWB', 'Green FixedRG 2', 0, 'ENG0_pGreenFixedRG[2]', NULL, 'Administrator'),
('AWB', 'Green FixedRG 3', 0, 'ENG0_pGreenFixedRG[3]', NULL, 'Administrator'),
('AWB', 'FixLowCT Enable', 0, 'ENG0_bFixLowCTOption', NULL, 'Administrator'),
('AWB', 'LowCTLumaThr', 0, 'ENG0_nLowCTLumaThre', NULL, 'Administrator'),
('AWB', 'FixLowCTList 0', 0, 'ENG0_pFixLowCTList[0]', NULL, 'Administrator'),
('AWB', 'FixLowCTList 1', 0, 'ENG0_pFixLowCTList[1]', NULL, 'Administrator'),
('AWB', 'FixLowCTList 2', 0, 'ENG0_pFixLowCTList[2]', NULL, 'Administrator'),
('AWB', 'FixLowCTList 3', 0, 'ENG0_pFixLowCTList[3]', NULL, 'Administrator'),
('AWB', 'FixLowCTList 4', 0, 'ENG0_pFixLowCTList[4]', NULL, 'Administrator'),
('AWB', 'FixLowBGList 0', 0, 'ENG0_pFixLowBGList[0]', NULL, 'Administrator'),
('AWB', 'FixLowBGList 1', 0, 'ENG0_pFixLowBGList[1]', NULL, 'Administrator'),
('AWB', 'FixLowBGList 2', 0, 'ENG0_pFixLowBGList[2]', NULL, 'Administrator'),
('AWB', 'FixLowBGList 3', 0, 'ENG0_pFixLowBGList[3]', NULL, 'Administrator'),
('AWB', 'FixLowBGList 4', 0, 'ENG0_pFixLowBGList[4]', NULL, 'Administrator'),
('AWB', 'FixLowRGList 0', 0, 'ENG0_pFixLowRGList[0]', NULL, 'Administrator'),
('AWB', 'FixLowRGList 1', 0, 'ENG0_pFixLowRGList[1]', NULL, 'Administrator'),
('AWB', 'FixLowRGList 2', 0, 'ENG0_pFixLowRGList[2]', NULL, 'Administrator'),
('AWB', 'FixLowRGList 3', 0, 'ENG0_pFixLowRGList[3]', NULL, 'Administrator'),
('AWB', 'FixLowRGList 4', 0, 'ENG0_pFixLowRGList[4]', NULL, 'Administrator'),
('AWB', 'StyleCTList 0', 0, 'ENG0_pStyleCTList[0]', NULL, 'Administrator'),
('AWB', 'StyleCTList 1', 0, 'ENG0_pStyleCTList[1]', NULL, 'Administrator'),
('AWB', 'StyleBG 0', 0, 'ENG0_pStyleBG[0]', NULL, 'Administrator'),
('AWB', 'StyleBG 1', 0, 'ENG0_pStyleBG[1]', NULL, 'Administrator'),
('AWB', 'StyleRG 0', 0, 'ENG0_pStyleRG[0]', NULL, 'Administrator'),
('AWB', 'StyleRG 1', 0, 'ENG0_pStyleRG[1]', NULL, 'Administrator'),
('AWB', 'LFSTransMode', 0, 'nLFSTransMode', NULL, 'Administrator'),
('AWB', 'ManualAWB En', 0, 'bManualAWB', NULL, 'Administrator'),
('AWB', 'Man B GainV', 0, 'pManualLFSGain[0]', NULL, 'Administrator'),
('AWB', 'Man G GainV', 0, 'pManualLFSGain[1]', NULL, 'Administrator'),
('AWB', 'Man R GainV', 0, 'pManualLFSGain[2]', NULL, 'Administrator'),
('AWB', 'MaxAWBGain 0V', 0, 'pMaxLFSGain[0]', NULL, 'Administrator'),
('AWB', 'MaxAWBGain 1V', 0, 'pMaxLFSGain[1]', NULL, 'Administrator'),
('AWB', 'MinAWBGain 0V', 0, 'pMinLFSGain[0]', NULL, 'Administrator'),
('AWB', 'MinAWBGain 1V', 0, 'pMinLFSGain[1]', NULL, 'Administrator'),
('AWB', 'LFSTransCTList 0V', 0, 'pLFSTransCTList[0]', NULL, 'Administrator'),
('AWB', 'LFSTransCTList 1V', 0, 'pLFSTransCTList[1]', NULL, 'Administrator'),
('AWB', 'LFSTransCTList 2V', 0, 'pLFSTransCTList[2]', NULL, 'Administrator'),
('AWB', 'LFSTransCTList 3V', 0, 'pLFSTransCTList[3]', NULL, 'Administrator'),
('AWB', 'LFSTransBGList 0V', 0, 'pLFSTransBGList[0]', NULL, 'Administrator'),
('AWB', 'LFSTransBGList 1V', 0, 'pLFSTransBGList[1]', NULL, 'Administrator'),
('AWB', 'LFSTransBGList 2V', 0, 'pLFSTransBGList[2]', NULL, 'Administrator'),
('AWB', 'LFSTransBGList 3V', 0, 'pLFSTransBGList[3]', NULL, 'Administrator'),
('AWB', 'BGRatioList 0V', 0, 'pLFSTransBGRatioList[0]', NULL, 'Administrator'),
('AWB', 'BGRatioList 1V', 0, 'pLFSTransBGRatioList[1]', NULL, 'Administrator'),
('AWB', 'BGRatioList 2V', 0, 'pLFSTransBGRatioList[2]', NULL, 'Administrator'),
('AWB', 'BGRatioList 3V', 0, 'pLFSTransBGRatioList[3]', NULL, 'Administrator'),
('AWB', 'LFSTransRGList 0V', 0, 'pLFSTransRGList[0]', NULL, 'Administrator'),
('AWB', 'LFSTransRGList 1V', 0, 'pLFSTransRGList[1]', NULL, 'Administrator'),
('AWB', 'LFSTransRGList 2V', 0, 'pLFSTransRGList[2]', NULL, 'Administrator'),
('AWB', 'LFSTransRGList 3V', 0, 'pLFSTransRGList[3]', NULL, 'Administrator'),
('AWB', 'RGRatioList 0V', 0, 'pLFSTransRGRatioList[0]', NULL, 'Administrator'),
('AWB', 'RGRatioList 1V', 0, 'pLFSTransRGRatioList[1]', NULL, 'Administrator'),
('AWB', 'RGRatioList 2V', 0, 'pLFSTransRGRatioList[2]', NULL, 'Administrator'),
('AWB', 'RGRatioList 3V', 0, 'pLFSTransRGRatioList[3]', NULL, 'Administrator'),
('AWB', 'Current Gain B',0,'current B Gain',NULL,'Administrator'),
('AWB', 'Current Gain R',0,'current R Gain',NULL,'Administrator'),
('AWB', 'Current Gain L',0,'current L Gain',NULL,'Administrator'),
('AWB', 'Current Expo L',0,'current L Expo',NULL,'Administrator');

INSERT INTO ui_info_regmodule VALUES
('AWB','Current Gain L','PipeCtrl',1),
('AWB','Current Expo L','PipeCtrl',1),
('AWB','Current Gain B','PipeCtrl',1),
('AWB','Current Gain R','PipeCtrl',1);