DELETE FROM ui_info WHERE module_name = 'ImgFmt';
DELETE FROM ui_info_regmodule WHERE ui_module_name='ImgFmt';
INSERT INTO ui_info VALUES 
('ImgFmt', 'Width', 0, 'nWidth', NULL, 'Administrator'),
('ImgFmt', 'Height', 0, 'nHeight', NULL, 'Administrator'),
('ImgFmt', 'BLC', 0, 'nBLC', NULL, 'Administrator'),
('ImgFmt', 'HDRMode', 0, 'bFPNCEnable', NULL, 'Administrator'),
('ImgFmt', 'HDRMode', 1, 'bKPCEnable', NULL, 'Administrator'),
('ImgFmt', 'HDRMode', 2, 'pRGBIRCIPEnable[0]', NULL, 'Administrator'),
('ImgFmt', 'HDRMode', 3, 'pRGBIRCIPEnable[1]', NULL, 'Administrator'),
('ImgFmt', 'HDRMode', 4, 'pWGBEnable[0]', NULL, 'Administrator'),
('ImgFmt', 'RGBIR', 0, 'pRGBIRCIPEnable[0]', NULL, 'Administrator'),
('ImgFmt', 'RGBIR', 1, 'pRGBIRCIPEnable[1]', NULL, 'Administrator'),
('ImgFmt', 'KPC', 0, 'bKPCEnable', NULL, 'Administrator'),
('ImgFmt', 'AEC', 0, 'bAECUpdateEnable', NULL, 'Administrator'),
('ImgFmt', 'AWB', 0, 'bAWBUpdateEnable', NULL, 'Administrator'),
('ImgFmt', 'RawDNS', 0, 'pRAWDNSEnable[0]', NULL, 'Administrator'),
('ImgFmt', 'RawDNS', 1, 'pRAWDNSEnable[1]', NULL, 'Administrator'),
('ImgFmt', 'YUVDNS', 0, 'r_bDnsEnable', NULL, 'Administrator'),
('ImgFmt', 'Sharpness', 0, 'r_bShpEnable', NULL, 'Administrator'),
('ImgFmt', 'DPC', 0, 'pDPCEnable[0]', NULL, 'Administrator'),
('ImgFmt', 'DPC', 1, 'pDPCEnable[1]', NULL, 'Administrator'),
('ImgFmt', 'DPC', 2, 'pDPCEnable[2]', NULL, 'Administrator'),
('ImgFmt', 'DPC', 3, 'pDPCEnable[3]', NULL, 'Administrator'),
('ImgFmt', 'Combine', 0, 'bCombineEnable', NULL, 'Administrator'),
('ImgFmt', 'TM', 0, 'bTMEnable', NULL, 'Administrator'),
('ImgFmt', 'Curve', 0, 'bCurveEnable[0]', NULL, 'Administrator'),
('ImgFmt', 'PreCCM', 0, 'bPreCCMEnable[0]', NULL, 'Administrator'),
('ImgFmt', 'PreCCM', 1, 'bPreCCMEnable[1]', NULL, 'Administrator'),
('ImgFmt', 'GBalance', 0, 'r_bGBalanceEnable', NULL, 'Administrator'),
('ImgFmt', 'BLCH', 0, 'r_blt', NULL, 'Administrator'),
('ImgFmt', 'AECH', 0, 'r_aec_en', NULL, 'Administrator'),
('ImgFmt', 'AWBH', 0, 'r_awb_en', NULL, 'Administrator'),
('ImgFmt', 'AWBH', 1, 'r_mwb_en_m', NULL, 'Administrator'),
('ImgFmt', 'AWBH', 2, 'r_mwb_en_l', NULL, 'Administrator'),
('ImgFmt', 'RawDNSH', 0, 'r_2ddns_en_m', NULL, 'Administrator'),
('ImgFmt', 'RGBIRH', 0, 'r_rgbir_en_m', NULL, 'Administrator'),
('ImgFmt', 'YUVDNSH', 0, 'r_dns_en', NULL, 'Administrator'),
('ImgFmt', 'SharpnessH', 0, 'r_shp_en', NULL, 'Administrator'),
('ImgFmt', 'DPC-mainH', 0, 'r_dpc65_en_m', NULL, 'Administrator'),
('ImgFmt', 'DPC-liteH', 0, 'r_dpc60_en_l', NULL, 'Administrator'),
('ImgFmt', 'CAC-LH', 0, 'r_cac_enable', NULL, 'Administrator'),
('ImgFmt', 'CAC-MH', 0, 'r_cac_enable', NULL, 'Administrator'),
('ImgFmt', 'CombineH', 0, 'r_comb_en', NULL, 'Administrator'),
('ImgFmt', 'TMH', 0, 'r_ltm_en', NULL, 'Administrator'),
('ImgFmt', 'CCMH', 0, 'r_ccm_en', NULL, 'Administrator'),
('ImgFmt', 'GammaH', 0, 'r_gma_en', NULL, 'Administrator'),
('ImgFmt', 'GammaGainH', 0, 'r_apply_h_en', NULL, 'Administrator'),
('ImgFmt', 'CurveH', 0, 'r_curve_en', NULL, 'Administrator'),
('ImgFmt', 'PreCCMH', 0, 'r_preccm_en', NULL, 'Administrator'),
('ImgFmt', 'Saturation', 0, 'r_bGainSatEnable', NULL, 'Administrator'),
('ImgFmt', 'Saturation0', 0, 'r_bGainSatEnable', NULL, 'Administrator'),
('ImgFmt', 'HDR Mode', 0, 'nISPMode', NULL, 'Administrator'),
('ImgFmt', 'HDR ModeH', 0, 'r_hdr_mode', NULL, 'Administrator'),
('ImgFmt', 'KPCH', 0, 'r_kpc_en_m', NULL, 'Administrator'),
('ImgFmt', 'CurTempH', 0, 'r_nCurTemp', NULL, 'Administrator'),
('ImgFmt', 'LSCH', 0, 'r_lenc_en_m', NULL, 'Administrator'),
('ImgFmt', 'FPNCH', 0, 'r_b_fpnc_en', NULL, 'Administrator');

INSERT INTO ui_info_regmodule VALUES
('ImgFmt', 'CurTempH', 'NewFuncPatch_ImgFmt', 0);