DELETE FROM ui_info WHERE module_name='DPC-L&M';
DELETE FROM ui_info_regmodule WHERE ui_module_name='DPC-L&M';
DELETE FROM ui_info WHERE module_name='DPC-S';
DELETE FROM ui_info_regmodule WHERE ui_module_name='DPC-S';
DELETE FROM ui_info WHERE module_name='DPC-LFS';
DELETE FROM ui_info_regmodule WHERE ui_module_name='DPC-LFS';
INSERT INTO ui_info VALUES 
('DPC-L&M', 'WPC_EnableL', 0, 'r_w_bp_en', NULL, 'Administrator'),
('DPC-L&M', 'WPC_EnableM', 0, 'r_w_bp_en', NULL, 'Administrator'),
('DPC-L&M', 'BPC_EnableL', 0, 'r_b_bp_en', NULL, 'Administrator'),
('DPC-L&M', 'BPC_EnableM', 0, 'r_b_bp_en', NULL, 'Administrator'),
('DPC-L&M', 'BW_Enable', 0, 'r_bManualmode', NULL, 'Administrator'),
('DPC-L&M', 'GainThre[0]', 0, 'r_pGainThre[0]', NULL, 'Administrator'),
('DPC-L&M', 'GainThre[1]', 0, 'r_pGainThre[1]', NULL, 'Administrator'),
('DPC-L&M', 'GainSwitch', 0, 'r_nGainSwitch', NULL, 'Administrator'),
('DPC-L&M', 'Cur Gain L', 0, 'current L Gain', NULL, 'Administrator'),  
('DPC-L&M', 'DpcTableInfo', 0, 'r_pWThresList[0]', NULL, 'Administrator'),
('DPC-L&M', 'DpcTableInfo', 1, 'r_pWThresList[1]', NULL, 'Administrator'),
('DPC-L&M', 'DpcTableInfo', 2, 'r_pWThresList[2]', NULL, 'Administrator'),
('DPC-L&M', 'DpcTableInfo', 3, 'r_pWRatioList[0]', NULL, 'Administrator'),
('DPC-L&M', 'DpcTableInfo', 4, 'r_pWRatioList[1]', NULL, 'Administrator'),
('DPC-L&M', 'DpcTableInfo', 5, 'r_pWRatioList[2]', NULL, 'Administrator'),
('DPC-L&M', 'DpcTableInfo', 6, 'r_pBThresList[0]', NULL, 'Administrator'),
('DPC-L&M', 'DpcTableInfo', 7, 'r_pBThresList[1]', NULL, 'Administrator'),
('DPC-L&M', 'DpcTableInfo', 8, 'r_pBThresList[2]', NULL, 'Administrator'),
('DPC-L&M', 'DpcTableInfo', 9, 'r_pBRatioList[0]', NULL, 'Administrator'),
('DPC-L&M', 'DpcTableInfo', 10, 'r_pBRatioList[1]', NULL, 'Administrator'),
('DPC-L&M', 'DpcTableInfo', 11, 'r_pBRatioList[2]', NULL, 'Administrator'),
('DPC-S', 'WPC_Enable', 0, 'r_w_bp_en', NULL, 'Administrator'),
('DPC-S', 'BPC_Enable', 0, 'r_b_bp_en', NULL, 'Administrator'),
('DPC-S', 'BW_Enable', 0, 'r_mono_en', NULL, 'Administrator'),
('DPC-S', 'GainPivot[0]', 0, 'r_pGainPivot[0]', NULL, 'Administrator'),
('DPC-S', 'GainPivot[1]', 0, 'r_pGainPivot[1]', NULL, 'Administrator'),
('DPC-S', 'GainMargin', 0, 'r_nGainMargin', NULL, 'Administrator'),
('DPC-S', 'DpcTableInfo', 0, 'r_pWThresList[0]', NULL, 'Administrator'),
('DPC-S', 'DpcTableInfo', 1, 'r_pWThresList[1]', NULL, 'Administrator'),
('DPC-S', 'DpcTableInfo', 2, 'r_pWThresList[2]', NULL, 'Administrator'),
('DPC-S', 'DpcTableInfo', 3, 'r_pWSlopeList[0]', NULL, 'Administrator'),
('DPC-S', 'DpcTableInfo', 4, 'r_pWSlopeList[1]', NULL, 'Administrator'),
('DPC-S', 'DpcTableInfo', 5, 'r_pWSlopeList[2]', NULL, 'Administrator'),
('DPC-S', 'DpcTableInfo', 6, 'r_pBThresList[0]', NULL, 'Administrator'),
('DPC-S', 'DpcTableInfo', 7, 'r_pBThresList[1]', NULL, 'Administrator'),
('DPC-S', 'DpcTableInfo', 8, 'r_pBThresList[2]', NULL, 'Administrator'),
('DPC-S', 'DpcTableInfo', 9, 'r_pBSlopeList[0]', NULL, 'Administrator'),
('DPC-S', 'DpcTableInfo', 10, 'r_pBSlopeList[1]', NULL, 'Administrator'),
('DPC-S', 'DpcTableInfo', 11, 'r_pBSlopeList[2]', NULL, 'Administrator'),
('DPC-LFS', 'WPC_Enable', 0, 'r_w_bp_en', NULL, 'Administrator'),
('DPC-LFS', 'BPC_Enable', 0, 'r_b_bp_en', NULL, 'Administrator'),
('DPC-LFS', 'BW_Enable', 0, 'r_mono_en', NULL, 'Administrator'),
('DPC-LFS', 'GainPivot[0]', 0, 'r_pGainPivot[0]', NULL, 'Administrator'),
('DPC-LFS', 'GainPivot[1]', 0, 'r_pGainPivot[1]', NULL, 'Administrator'),
('DPC-LFS', 'GainMargin', 0, 'r_nGainMargin', NULL, 'Administrator'),
('DPC-LFS', 'DpcTableInfo', 0, 'r_pWThresList[0]', NULL, 'Administrator'),
('DPC-LFS', 'DpcTableInfo', 1, 'r_pWThresList[1]', NULL, 'Administrator'),
('DPC-LFS', 'DpcTableInfo', 2, 'r_pWThresList[2]', NULL, 'Administrator'),
('DPC-LFS', 'DpcTableInfo', 3, 'r_pWSlopeList[0]', NULL, 'Administrator'),
('DPC-LFS', 'DpcTableInfo', 4, 'r_pWSlopeList[1]', NULL, 'Administrator'),
('DPC-LFS', 'DpcTableInfo', 5, 'r_pWSlopeList[2]', NULL, 'Administrator'),
('DPC-LFS', 'DpcTableInfo', 6, 'r_pBThresList[0]', NULL, 'Administrator'),
('DPC-LFS', 'DpcTableInfo', 7, 'r_pBThresList[1]', NULL, 'Administrator'),
('DPC-LFS', 'DpcTableInfo', 8, 'r_pBThresList[2]', NULL, 'Administrator'),
('DPC-LFS', 'DpcTableInfo', 9, 'r_pBSlopeList[0]', NULL, 'Administrator'),
('DPC-LFS', 'DpcTableInfo', 10, 'r_pBSlopeList[1]', NULL, 'Administrator'),
('DPC-LFS', 'DpcTableInfo', 11, 'r_pBSlopeList[2]', NULL, 'Administrator');

INSERT INTO ui_info_regmodule VALUES 
('DPC-L&M', 'WPC_EnableL', 'CDPC_V65_HW_RAWL', 0),
('DPC-L&M', 'WPC_EnableM', 'CDPC_V65_HW_RAWM', 0),
('DPC-L&M', 'BPC_EnableL', 'CDPC_V65_HW_RAWL', 0),
('DPC-L&M', 'BPC_EnableM', 'CDPC_V65_HW_RAWM', 0),
('DPC-L&M', 'BW_Enable', 'DPC_LM', 1),
('DPC-L&M', 'GainThre[0]', 'DPC_LM', 1),
('DPC-L&M', 'GainThre[1]', 'DPC_LM', 1),
('DPC-L&M', 'GainSwitch', 'DPC_LM', 1),
('DPC-L&M', 'Cur Gain L', 'PipeCtrl', 1),
('DPC-L&M', 'DpcTableInfo', 'DPC_LM', 1),
('DPC-S', 'WPC_Enable', 'CDPC_V60_HW_RAWS', 0),
('DPC-S', 'BPC_Enable', 'CDPC_V60_HW_RAWS', 0),
('DPC-S', 'BW_Enable', 'CDPC_V60_HW_RAWS', 0),
('DPC-S', 'GainPivot[0]', 'DPC_S', 1),
('DPC-S', 'GainPivot[1]', 'DPC_S', 1),
('DPC-S', 'GainMargin', 'DPC_S', 1),
('DPC-S', 'DpcTableInfo', 'DPC_S', 1),
('DPC-LFS', 'WPC_Enable', 'CDPC_V60_HW_RAWV', 0),
('DPC-LFS', 'BPC_Enable', 'CDPC_V60_HW_RAWV', 0),
('DPC-LFS', 'BW_Enable', 'CDPC_V60_HW_RAWV', 0),
('DPC-LFS', 'GainPivot[0]', 'DPC_V', 1),
('DPC-LFS', 'GainPivot[1]', 'DPC_V', 1),
('DPC-LFS', 'GainMargin', 'DPC_V', 1),
('DPC-LFS', 'DpcTableInfo', 'DPC_V', 1);
