DELETE FROM ui_info WHERE module_name='TM';
DELETE FROM ui_info_regmodule WHERE ui_module_name='TM';
INSERT INTO ui_info VALUES 
('TM', 'TM Option', 0, 'nToneMappingOption', NULL, 'Administrator'),
('TM', 'Manual DR Mode', 0, 'bManualDRMode', NULL, 'Administrator'),
('TM', 'Manual DR', 0, 'nManualDR', NULL, 'Administrator'),
('TM', 'DR List[0]', 0, 'pDynamicRangeList[0]', NULL, 'Administrator'),
('TM', 'DR List[1]', 0, 'pDynamicRangeList[1]', NULL, 'Administrator'),
('TM', 'DR List[2]', 0, 'pDynamicRangeList[2]', NULL, 'Administrator'),
('TM', 'DR List[3]', 0, 'pDynamicRangeList[3]', NULL, 'Administrator'),
('TM', 'DR List[4]', 0, 'pDynamicRangeList[4]', NULL, 'Administrator'),
('TM', 'UpDateGTM',0,'bUpDateGTM',NULL, 'Administrator'),
('TM', 'HistEQEnable',0,'bHistEQEnable',NULL, 'Administrator'),
('TM', 'HistEQList',0,'pHistEQList[0]',NULL, 'Administrator'),
('TM', 'HistEQList',1,'pHistEQList[1]',NULL, 'Administrator'),
('TM', 'HistEQList',2,'pHistEQList[2]',NULL, 'Administrator'),
('TM', 'HistEQList',3,'pHistEQList[3]',NULL, 'Administrator'),
('TM', 'HistEQList',4,'pHistEQList[4]',NULL, 'Administrator'),
('TM', 'HistEQList',5,'pHistEQList[5]',NULL, 'Administrator'),
('TM', 'HistEQList',6,'pHistEQList[6]',NULL, 'Administrator'),
('TM', 'HistEQList',7,'pHistEQList[7]',NULL, 'Administrator'),
('TM', 'HistEQList',8,'pHistEQList[8]',NULL, 'Administrator'),
('TM', 'HistEQList',9,'pHistEQList[9]',NULL, 'Administrator'),
('TM', 'HistEQList',10,'pHistEQList[10]',NULL, 'Administrator'),
('TM', 'HistEQList',11,'pHistEQList[11]',NULL, 'Administrator'),
('TM', 'HistEQList',12,'pHistEQList[12]',NULL, 'Administrator'),
('TM', 'HistEQList',13,'pHistEQList[13]',NULL, 'Administrator'),
('TM', 'HistEQList',14,'pHistEQList[14]',NULL, 'Administrator'),
('TM', 'HistEQList',15,'pHistEQList[15]',NULL, 'Administrator'),
('TM', 'HistEQList',16,'pHistEQList[16]',NULL, 'Administrator'),
('TM', 'HistEQList',17,'pHistEQList[17]',NULL, 'Administrator'),
('TM', 'HistEQList',18,'pHistEQList[18]',NULL, 'Administrator'),
('TM', 'HistEQList',19,'pHistEQList[19]',NULL, 'Administrator'),
('TM', 'HistEQList',20,'pHistEQList[20]',NULL, 'Administrator'),
('TM', 'HistEQList',21,'pHistEQList[21]',NULL, 'Administrator'),
('TM', 'HistEQList',22,'pHistEQList[22]',NULL, 'Administrator'),
('TM', 'HistEQList',23,'pHistEQList[23]',NULL, 'Administrator'),
('TM', 'HistEQList',24,'pHistEQList[24]',NULL, 'Administrator'),
('TM', 'HistEQList',25,'pHistEQList[25]',NULL, 'Administrator'),
('TM', 'HistEQList',26,'pHistEQList[26]',NULL, 'Administrator'),
('TM', 'HistEQList',27,'pHistEQList[27]',NULL, 'Administrator'),
('TM', 'HistEQList',28,'pHistEQList[28]',NULL, 'Administrator'),
('TM', 'HistEQList',29,'pHistEQList[29]',NULL, 'Administrator'),
('TM', 'HistEQList',30,'pHistEQList[30]',NULL, 'Administrator'),
('TM', 'HistPointStepList[0]',0,'pHistPointStepList[0]',NULL, 'Administrator'),
('TM', 'HistPointStepList[1]',0,'pHistPointStepList[1]',NULL, 'Administrator'),
('TM', 'HistPointStepList[2]',0,'pHistPointStepList[2]',NULL, 'Administrator'),
('TM', 'HistPointStepList[3]',0,'pHistPointStepList[3]',NULL, 'Administrator'),
('TM', 'HistPointStepList[4]',0,'pHistPointStepList[4]',NULL, 'Administrator'),
('TM', 'GainThre1',0,'nGainThre1',NULL, 'Administrator'),
('TM', 'GainThre2',0,'nGainThre2',NULL, 'Administrator'),
('TM', 'CurveStep1',0,'pCurveStep1[0]',NULL, 'Administrator'),
('TM', 'CurveStep1',1,'pCurveStep1[1]',NULL, 'Administrator'),
('TM', 'CurveStep1',2,'pCurveStep1[2]',NULL, 'Administrator'),
('TM', 'CurveStep1',3,'pCurveStep1[3]',NULL, 'Administrator'),
('TM', 'CurveStep1',4,'pCurveStep1[4]',NULL, 'Administrator'),
('TM', 'CurveStep1',5,'pCurveStep1[5]',NULL, 'Administrator'),
('TM', 'CurveStep1',6,'pCurveStep1[6]',NULL, 'Administrator'),
('TM', 'CurveStep1',7,'pCurveStep1[7]',NULL, 'Administrator'),
('TM', 'CurveStep1',8,'pCurveStep1[8]',NULL, 'Administrator'),
('TM', 'CurveStep1',9,'pCurveStep1[9]',NULL, 'Administrator'),
('TM', 'CurveStep1',10,'pCurveStep1[10]',NULL, 'Administrator'),
('TM', 'CurveStep1',11,'pCurveStep1[11]',NULL, 'Administrator'),
('TM', 'CurveStep1',12,'pCurveStep1[12]',NULL, 'Administrator'),
('TM', 'CurveStep1',13,'pCurveStep1[13]',NULL, 'Administrator'),
('TM', 'CurveStep1',14,'pCurveStep1[14]',NULL, 'Administrator'),
('TM', 'CurveStep1',15,'pCurveStep1[15]',NULL, 'Administrator'),
('TM', 'CurveStep1',16,'pCurveStep1[16]',NULL, 'Administrator'),
('TM', 'CurveStep1',17,'pCurveStep1[17]',NULL, 'Administrator'),
('TM', 'CurveStep1',18,'pCurveStep1[18]',NULL, 'Administrator'),
('TM', 'CurveStep1',19,'pCurveStep1[19]',NULL, 'Administrator'),
('TM', 'CurveStep1',20,'pCurveStep1[20]',NULL, 'Administrator'),
('TM', 'CurveStep1',21,'pCurveStep1[21]',NULL, 'Administrator'),
('TM', 'CurveStep1',22,'pCurveStep1[22]',NULL, 'Administrator'),
('TM', 'CurveStep1',23,'pCurveStep1[23]',NULL, 'Administrator'),
('TM', 'CurveStep1',24,'pCurveStep1[24]',NULL, 'Administrator'),
('TM', 'CurveStep1',25,'pCurveStep1[25]',NULL, 'Administrator'),
('TM', 'CurveStep1',26,'pCurveStep1[26]',NULL, 'Administrator'),
('TM', 'CurveStep1',27,'pCurveStep1[27]',NULL, 'Administrator'),
('TM', 'CurveStep1',28,'pCurveStep1[28]',NULL, 'Administrator'),
('TM', 'CurveStep1',29,'pCurveStep1[29]',NULL, 'Administrator'),
('TM', 'CurveStep1',30,'pCurveStep1[30]',NULL, 'Administrator'),
('TM', 'CurveStep2',0,'pCurveStep2[0]',NULL, 'Administrator'),
('TM', 'CurveStep2',1,'pCurveStep2[1]',NULL, 'Administrator'),
('TM', 'CurveStep2',2,'pCurveStep2[2]',NULL, 'Administrator'),
('TM', 'CurveStep2',3,'pCurveStep2[3]',NULL, 'Administrator'),
('TM', 'CurveStep2',4,'pCurveStep2[4]',NULL, 'Administrator'),
('TM', 'CurveStep2',5,'pCurveStep2[5]',NULL, 'Administrator'),
('TM', 'CurveStep2',6,'pCurveStep2[6]',NULL, 'Administrator'),
('TM', 'CurveStep2',7,'pCurveStep2[7]',NULL, 'Administrator'),
('TM', 'CurveStep2',8,'pCurveStep2[8]',NULL, 'Administrator'),
('TM', 'CurveStep2',9,'pCurveStep2[9]',NULL, 'Administrator'),
('TM', 'CurveStep2',10,'pCurveStep2[10]',NULL, 'Administrator'),
('TM', 'CurveStep2',11,'pCurveStep2[11]',NULL, 'Administrator'),
('TM', 'CurveStep2',12,'pCurveStep2[12]',NULL, 'Administrator'),
('TM', 'CurveStep2',13,'pCurveStep2[13]',NULL, 'Administrator'),
('TM', 'CurveStep2',14,'pCurveStep2[14]',NULL, 'Administrator'),
('TM', 'CurveStep2',15,'pCurveStep2[15]',NULL, 'Administrator'),
('TM', 'CurveStep2',16,'pCurveStep2[16]',NULL, 'Administrator'),
('TM', 'CurveStep2',17,'pCurveStep2[17]',NULL, 'Administrator'),
('TM', 'CurveStep2',18,'pCurveStep2[18]',NULL, 'Administrator'),
('TM', 'CurveStep2',19,'pCurveStep2[19]',NULL, 'Administrator'),
('TM', 'CurveStep2',20,'pCurveStep2[20]',NULL, 'Administrator'),
('TM', 'CurveStep2',21,'pCurveStep2[21]',NULL, 'Administrator'),
('TM', 'CurveStep2',22,'pCurveStep2[22]',NULL, 'Administrator'),
('TM', 'CurveStep2',23,'pCurveStep2[23]',NULL, 'Administrator'),
('TM', 'CurveStep2',24,'pCurveStep2[24]',NULL, 'Administrator'),
('TM', 'CurveStep2',25,'pCurveStep2[25]',NULL, 'Administrator'),
('TM', 'CurveStep2',26,'pCurveStep2[26]',NULL, 'Administrator'),
('TM', 'CurveStep2',27,'pCurveStep2[27]',NULL, 'Administrator'),
('TM', 'CurveStep2',28,'pCurveStep2[28]',NULL, 'Administrator'),
('TM', 'CurveStep2',29,'pCurveStep2[29]',NULL, 'Administrator'),
('TM', 'CurveStep2',30,'pCurveStep2[30]',NULL, 'Administrator'),
('TM', 'CurveAlpha[0]',0,'pCurveAlpha[0]',NULL, 'Administrator'),
('TM', 'CurveAlpha[1]',0,'pCurveAlpha[1]',NULL, 'Administrator'),
('TM', 'CurveAlpha[2]',0,'pCurveAlpha[2]',NULL, 'Administrator'),
('TM', 'CurveAlpha[3]',0,'pCurveAlpha[3]',NULL, 'Administrator'),
('TM', 'CurveAlpha[4]',0,'pCurveAlpha[4]',NULL, 'Administrator'),
('TM', 'LTMEnable',0,'bLocalTMEnable',NULL, 'Administrator'),
('TM', 'UpDateLTM',0,'bUpDateLTM',NULL, 'Administrator'),
('TM', 'SmoothOption',0,'nSmoothOption',NULL, 'Administrator'),
('TM', 'ClipLogGain',0,'bClipLogGain',NULL, 'Administrator'),
('TM', 'LogGainCursLimit',0,'nLogGainCursLimit',NULL, 'Administrator'),
('TM', 'LogGainLimit',0,'nLogGainLimit',NULL, 'Administrator'),
('TM', 'LTMAlpha2',0,'nLTMAlpha2',NULL, 'Administrator'),
('TM', 'LocalGammaAlphaList[0]',0,'pLocalGammaAlphaList[0]',NULL, 'Administrator'),
('TM', 'LocalGammaAlphaList[1]',0,'pLocalGammaAlphaList[1]',NULL, 'Administrator'),
('TM', 'LocalGammaAlphaList[2]',0,'pLocalGammaAlphaList[2]',NULL, 'Administrator'),
('TM', 'LocalGammaAlphaList[3]',0,'pLocalGammaAlphaList[3]',NULL, 'Administrator'),
('TM', 'LocalGammaAlphaList[4]',0,'pLocalGammaAlphaList[4]',NULL, 'Administrator'),
('TM', 'LocalGammaStepList[0]',0,'pLocalGammaStepList[0]',NULL, 'Administrator'),
('TM', 'LocalGammaStepList[1]',0,'pLocalGammaStepList[1]',NULL, 'Administrator'),
('TM', 'LocalGammaStepList[2]',0,'pLocalGammaStepList[2]',NULL, 'Administrator'),
('TM', 'LocalGammaStepList[3]',0,'pLocalGammaStepList[3]',NULL, 'Administrator'),
('TM', 'LocalGammaStepList[4]',0,'pLocalGammaStepList[4]',NULL, 'Administrator'),
('TM', 'GammaAdjustEnable',0,'bGammaAdjustEnable',NULL, 'Administrator'),
('TM', 'GlobalGammaList[0]',0,'pGlobalGammaList[0]',NULL, 'Administrator'),
('TM', 'GlobalGammaList[1]',0,'pGlobalGammaList[1]',NULL, 'Administrator'),
('TM', 'GlobalGammaList[2]',0,'pGlobalGammaList[2]',NULL, 'Administrator'),
('TM', 'GlobalGammaList[3]',0,'pGlobalGammaList[3]',NULL, 'Administrator'),
('TM', 'GlobalGammaList[4]',0,'pGlobalGammaList[4]',NULL, 'Administrator'),
('TM', 'GammaAdjustThre',0,'nGammaAdjustThre',NULL, 'Administrator'),
('TM', 'MaxGammaList[0]',0,'pMaxGammaList[0]',NULL, 'Administrator'),
('TM', 'MaxGammaList[1]',0,'pMaxGammaList[1]',NULL, 'Administrator'),
('TM', 'MaxGammaList[2]',0,'pMaxGammaList[2]',NULL, 'Administrator'),
('TM', 'MaxGammaList[3]',0,'pMaxGammaList[3]',NULL, 'Administrator'),
('TM', 'MaxGammaList[4]',0,'pMaxGammaList[4]',NULL, 'Administrator'),
('TM', 'MinGammaList[0]',0,'pMinGammaList[0]',NULL, 'Administrator'),
('TM', 'MinGammaList[1]',0,'pMinGammaList[1]',NULL, 'Administrator'),
('TM', 'MinGammaList[2]',0,'pMinGammaList[2]',NULL, 'Administrator'),
('TM', 'MinGammaList[3]',0,'pMinGammaList[3]',NULL, 'Administrator'),
('TM', 'MinGammaList[4]',0,'pMinGammaList[4]',NULL, 'Administrator'),
('TM', 'LogTarget',0,'nLogTarget',NULL, 'Administrator'),
('TM', 'TargetStep',0,'nTargetStep',NULL, 'Administrator'),
('TM', 'GammaAdjustStep',0,'nGammaAdjustStep',NULL, 'Administrator'),
('TM', 'MotionOpt',0,'nMotionOpt',NULL, 'Administrator'),
('TM', 'MotionStartFrame',0,'nMotionStartFrame',NULL, 'Administrator'),
('TM', 'MotionCoeff[0]',0,'pMotionCoeff[0]',NULL, 'Administrator'),
('TM', 'MotionCoeff[1]',0,'pMotionCoeff[1]',NULL, 'Administrator'),
('TM', 'MotionCoeff[2]',0,'pMotionCoeff[2]',NULL, 'Administrator'),
('TM', 'MotionCoeff[3]',0,'pMotionCoeff[3]',NULL, 'Administrator'),
('TM', 'MotionCoeff[4]',0,'pMotionCoeff[4]',NULL, 'Administrator'),
('TM', 'MotionWeight[0]',0,'pMotionWeight[0]',NULL, 'Administrator'),
('TM', 'MotionWeight[1]',0,'pMotionWeight[1]',NULL, 'Administrator'),
('TM', 'MotionWeight[2]',0,'pMotionWeight[2]',NULL, 'Administrator'),
('TM', 'MotionWeight[3]',0,'pMotionWeight[3]',NULL, 'Administrator'),
('TM', 'MotionWeight[4]',0,'pMotionWeight[4]',NULL, 'Administrator'),
('TM', 'MotionGammaStep[0]',0,'pMotionGammaStep[0]',NULL, 'Administrator'),
('TM', 'MotionGammaStep[1]',0,'pMotionGammaStep[1]',NULL, 'Administrator'),
('TM', 'MotionGammaStep[2]',0,'pMotionGammaStep[2]',NULL, 'Administrator'),
('TM', 'MotionThre',0,'nMotionThre',NULL, 'Administrator'),
('TM', 'Fish Len Opt',0,'r_fish_lens_opt',NULL, 'Administrator'),
('TM', 'Fisheye Radius',0,'r_fish_eye_radius',NULL, 'Administrator'),
('TM', 'Fisheye Center X',0,'r_fish_eye_center_x',NULL, 'Administrator'),
('TM', 'Fisheye Center Y',0,'r_fish_eye_center_y',NULL, 'Administrator');

INSERT INTO ui_info_regmodule VALUES
('TM', 'TM Option', 'TM', 1),
('TM', 'Manual DR Mode', 'TM', 1),
('TM', 'Manual DR', 'TM', 1),
('TM', 'DR List[0]', 'TM', 1),
('TM', 'DR List[1]', 'TM', 1),
('TM', 'DR List[2]', 'TM', 1),
('TM', 'DR List[3]', 'TM', 1),
('TM', 'DR List[4]', 'TM', 1),
('TM', 'LTMEnable','TM',1),
('TM', 'UpDateGTM','TM',1),
('TM', 'HistEQEnable','TM',1),
('TM', 'HistEQList','TM',1),
('TM', 'HistPointStepList[0]','TM',1),
('TM', 'HistPointStepList[1]','TM',1),
('TM', 'HistPointStepList[2]','TM',1),
('TM', 'HistPointStepList[3]','TM',1),
('TM', 'HistPointStepList[4]','TM',1),
('TM', 'GainThre1','TM',1),
('TM', 'GainThre2','TM',1),
('TM', 'CurveStep1','TM',1),
('TM', 'CurveStep2','TM',1),
('TM', 'CurveAlpha[0]','TM',1),
('TM', 'CurveAlpha[1]','TM',1),
('TM', 'CurveAlpha[2]','TM',1),
('TM', 'CurveAlpha[3]','TM',1),
('TM', 'CurveAlpha[4]','TM',1),
('TM', 'LocalTMEnable','TM',1),
('TM', 'UpDateLTM','TM',1),
('TM', 'SmoothOption','TM',1),
('TM', 'ClipLogGain','TM',1),
('TM', 'LogGainCursLimit','TM',1),
('TM', 'LogGainLimit','TM',1),
('TM', 'LTMAlpha2','TM',1),
('TM', 'LocalGammaAlphaList[0]','TM',1),
('TM', 'LocalGammaAlphaList[1]','TM',1),
('TM', 'LocalGammaAlphaList[2]','TM',1),
('TM', 'LocalGammaAlphaList[3]','TM',1),
('TM', 'LocalGammaAlphaList[4]','TM',1),
('TM', 'LocalGammaStepList[0]','TM',1),
('TM', 'LocalGammaStepList[1]','TM',1),
('TM', 'LocalGammaStepList[2]','TM',1),
('TM', 'LocalGammaStepList[3]','TM',1),
('TM', 'LocalGammaStepList[4]','TM',1),
('TM', 'GammaAdjustEnable','TM',1),
('TM', 'GlobalGammaList[0]','TM',1),
('TM', 'GlobalGammaList[1]','TM',1),
('TM', 'GlobalGammaList[2]','TM',1),
('TM', 'GlobalGammaList[3]','TM',1),
('TM', 'GlobalGammaList[4]','TM',1),
('TM', 'GammaAdjustThre','TM',1),
('TM', 'MaxGammaList[0]','TM',1),
('TM', 'MaxGammaList[1]','TM',1),
('TM', 'MaxGammaList[2]','TM',1),
('TM', 'MaxGammaList[3]','TM',1),
('TM', 'MaxGammaList[4]','TM',1),
('TM', 'MinGammaList[0]','TM',1),
('TM', 'MinGammaList[1]','TM',1),
('TM', 'MinGammaList[2]','TM',1),
('TM', 'MinGammaList[3]','TM',1),
('TM', 'MinGammaList[4]','TM',1),
('TM', 'LogTarget','TM',1),
('TM', 'TargetStep','TM',1),
('TM', 'GammaAdjustStep','TM',1),
('TM', 'MotionOpt','TM',1),
('TM', 'MotionStartFrame','TM',1),
('TM', 'MotionCoeff[0]','TM',1),
('TM', 'MotionCoeff[1]','TM',1),
('TM', 'MotionCoeff[2]','TM',1),
('TM', 'MotionCoeff[3]','TM',1),
('TM', 'MotionCoeff[4]','TM',1),
('TM', 'MotionWeight[0]','TM',1),
('TM', 'MotionWeight[1]','TM',1),
('TM', 'MotionWeight[2]','TM',1),
('TM', 'MotionWeight[3]','TM',1),
('TM', 'MotionWeight[4]','TM',1),
('TM', 'MotionGammaStep[0]','TM',1),
('TM', 'MotionGammaStep[1]','TM',1),
('TM', 'MotionGammaStep[2]','TM',1),
('TM', 'MotionThre','TM',1),
('TM', 'Fish Len Opt','CTM_HW_V60',0),
('TM', 'Fisheye Radius','CTM_HW_V60',0),
('TM', 'Fisheye Center X','CTM_HW_V60',0),
('TM', 'Fisheye Center Y','CTM_HW_V60',0);