DELETE FROM ui_info WHERE module_name = 'Combine';
DELETE FROM ui_info_regmodule WHERE ui_module_name = 'Combine';

INSERT INTO ui_info VALUES 
('Combine', 'Data Sel', 0, 'r_data_sel', NULL, 'Administrator'),
('Combine', 'Data SelCombine', 0, 'r_curve_en', NULL, 'Administrator'),
('Combine', 'High Margin', 0, 'r_high_margin', NULL, 'Administrator'),
('Combine', 'Blooming_mode_en', 0, 'r_blooming_mode_en', NULL, 'Administrator'),
('Combine', 'Blooming_shift1', 0, 'r_blooming_shift', NULL, 'Administrator'),
('Combine', 'Blooming_shift2', 0, 'r_blooming_shift2', NULL, 'Administrator'),
('Combine', 'ISOList0', 0, 'r_pISOList[0]', NULL, 'Administrator'),
('Combine', 'ISOList1', 0, 'r_pISOList[1]', NULL, 'Administrator'),
('Combine', 'Hist10[0]', 0, 'r_pHist10[0]', NULL, 'Administrator'),
('Combine', 'Hist10[1]', 0, 'r_pHist10[1]', NULL, 'Administrator'),
('Combine', 'Hist10[2]', 0, 'r_pHist10[2]', NULL, 'Administrator'),
('Combine', 'Hist11[0]', 0, 'r_pHist11[0]', NULL, 'Administrator'),
('Combine', 'Hist11[1]', 0, 'r_pHist11[1]', NULL, 'Administrator'),
('Combine', 'Hist11[2]', 0, 'r_pHist11[2]', NULL, 'Administrator'),
('Combine', 'Hist20[0]', 0, 'r_pHist20[0]', NULL, 'Administrator'),
('Combine', 'Hist20[1]', 0, 'r_pHist20[1]', NULL, 'Administrator'),
('Combine', 'Hist20[2]', 0, 'r_pHist20[2]', NULL, 'Administrator'),
('Combine', 'Hist21[0]', 0, 'r_pHist21[0]', NULL, 'Administrator'),
('Combine', 'Hist21[1]', 0, 'r_pHist21[1]', NULL, 'Administrator'),
('Combine', 'Hist21[2]', 0, 'r_pHist21[2]', NULL, 'Administrator'),
('Combine', 'Hist30[0]', 0, 'r_pHist30[0]', NULL, 'Administrator'),
('Combine', 'Hist30[1]', 0, 'r_pHist30[1]', NULL, 'Administrator'),
('Combine', 'Hist30[2]', 0, 'r_pHist30[2]', NULL, 'Administrator'),
('Combine', 'Hist31[0]', 0, 'r_pHist31[0]', NULL, 'Administrator'),
('Combine', 'Hist31[1]', 0, 'r_pHist31[1]', NULL, 'Administrator'),
('Combine', 'Hist31[2]', 0, 'r_pHist31[2]', NULL, 'Administrator'),
('Combine', 'Bright[0]', 0, 'r_hist_bright[0]', NULL, 'Administrator'),
('Combine', 'Bright[1]', 0, 'r_hist_bright[1]', NULL, 'Administrator'),
('Combine', 'Bright[2]', 0, 'r_hist_bright[2]', NULL, 'Administrator'),
('Combine', 'Dark[0]', 0, 'r_hist_dark[0]', NULL, 'Administrator'),
('Combine', 'Dark[1]', 0, 'r_hist_dark[1]', NULL, 'Administrator'),
('Combine', 'Dark[2]', 0, 'r_hist_dark[2]', NULL, 'Administrator'),
('Combine', 'CompS_en', 0, 'r_comps_en', NULL, 'Administrator'),
('Combine', 'CompS0[0]', 0, 'r_pCompS0[0]', NULL, 'Administrator'),
('Combine', 'CompS0[1]', 0, 'r_pCompS0[1]', NULL, 'Administrator'),
('Combine', 'CompS0[2]', 0, 'r_pCompS0[2]', NULL, 'Administrator'),
('Combine', 'CompS0[3]', 0, 'r_pCompS0[3]', NULL, 'Administrator'),
('Combine', 'CompS0[4]', 0, 'r_pCompS0[4]', NULL, 'Administrator'),
('Combine', 'CompS0[5]', 0, 'r_pCompS0[5]', NULL, 'Administrator'),
('Combine', 'CompS0[6]', 0, 'r_pCompS0[6]', NULL, 'Administrator'),
('Combine', 'CompS0[7]', 0, 'r_pCompS0[7]', NULL, 'Administrator'),
('Combine', 'CompS1[0]', 0, 'r_pCompS1[0]', NULL, 'Administrator'),
('Combine', 'CompS1[1]', 0, 'r_pCompS1[1]', NULL, 'Administrator'),
('Combine', 'CompS1[2]', 0, 'r_pCompS1[2]', NULL, 'Administrator'),
('Combine', 'CompS1[3]', 0, 'r_pCompS1[3]', NULL, 'Administrator'),
('Combine', 'CompS1[4]', 0, 'r_pCompS1[4]', NULL, 'Administrator'),
('Combine', 'CompS1[5]', 0, 'r_pCompS1[5]', NULL, 'Administrator'),
('Combine', 'CompS1[6]', 0, 'r_pCompS1[6]', NULL, 'Administrator'),
('Combine', 'CompS1[7]', 0, 'r_pCompS1[7]', NULL, 'Administrator'),
('Combine', 'ManualCompS', 0, 'r_bManualCompS', NULL, 'Administrator'),
('Combine', 'Dark_color_en', 0, 'r_dark_color_en', NULL, 'Administrator'),
('Combine', 'Dark_color_h_en', 0, 'r_dark_color_h_en', NULL, 'Administrator'),
('Combine', 'Dark_color_maxw', 0, 'r_dark_color_maxw', NULL, 'Administrator'),
('Combine', 'Dark_color_thrw', 0, 'r_dark_color_thrw', NULL, 'Administrator'),
('Combine', 'DarkColorGainStart', 0, 'r_nDarkColorGainStart', NULL, 'Administrator'),
('Combine', 'DarkColorGainEnd', 0, 'r_nDarkColorGainEnd', NULL, 'Administrator'),
('Combine', 'Lamp_edge_en', 0, 'r_lamp_edge_en', NULL, 'Administrator'),
('Combine', 'Lamp_edge2_en', 0, 'r_lamp_edge2_en', NULL, 'Administrator'),
('Combine', 'Lamp_hf_en', 0, 'r_lamp_hf_en', NULL, 'Administrator'),
('Combine', 'Lamp_hf2_en', 0, 'r_lamp_hf2_en', NULL, 'Administrator'),
('Combine', 'I_thr', 0, 'r_l_thr', NULL, 'Administrator'),
('Combine', 'I_thr2', 0, 'r_l_thr2', NULL, 'Administrator'),
('Combine', 'DoubleEdgeGainStart', 0, 'r_nDoubleEdgeGainStart', NULL, 'Administrator'),
('Combine', 'DoubleEdgeGainEnd', 0, 'r_nDoubleEdgeGainEnd', NULL, 'Administrator'),
('Combine', 'DoubleEdgeHFMaxThr', 0, 'r_nDoubleEdgeHFMaxThr', NULL, 'Administrator'),
('Combine', 'Lamp_w', 0, 'r_lamp_w', NULL, 'Administrator'),
('Combine', 'Lhf_thr', 0, 'r_lhf_thr', NULL, 'Administrator'),
('Combine', 'Lhf_thr2', 0, 'r_lhf_thr2', NULL, 'Administrator'),
('Combine', 'Ghost_en', 0, 'r_ghost_en', NULL, 'Administrator'),
('Combine', 'Ghost_opt2_en', 0, 'r_ghost_opt2_en', NULL, 'Administrator'),
('Combine', 'Ghostcheckl_en', 0, 'r_ghostcheckl_en', NULL, 'Administrator'),
('Combine', 'Ghost_thr', 0, 'r_ghost_thr', NULL, 'Administrator'),
('Combine', 'Ghost_thr2', 0, 'r_ghost_thr2', NULL, 'Administrator'),
('Combine', 'Ghost_slop', 0, 'r_ghost_slop', NULL, 'Administrator'),
('Combine', 'Ghost_Ithr', 0, 'r_ghost_lthr', NULL, 'Administrator'),
('Combine', 'Ghost_Ithr2', 0, 'r_ghost_lthr2', NULL, 'Administrator'),
('Combine', 'Ghost_Ithr3', 0, 'r_ghost_lthr3', NULL, 'Administrator'),
('Combine', 'Ghost_lslop', 0, 'r_ghost_lslope', NULL, 'Administrator'),
('Combine', 'Ghost_opt', 0, 'r_ghost_opt', NULL, 'Administrator'),
('Combine', 'Ghost_mode2', 0, 'r_ghost_mode2', NULL, 'Administrator'),
('Combine', 'Blooming_en', 0, 'r_lfs_blooming_en', NULL, 'Administrator'),
('Combine', 'AdjustLFSWeight', 0, 'r_bAdjustLFSWeight', NULL, 'Administrator'),
('Combine', 'Thr1', 0, 'r_lfs_thr1', NULL, 'Administrator'),
('Combine', 'Thr2', 0, 'r_lfs_thr2', NULL, 'Administrator'),
('Combine', 'Thr3', 0, 'r_lfs_thr3', NULL, 'Administrator'),
('Combine', 'Thr4', 0, 'r_lfs_thr4', NULL, 'Administrator'),
('Combine', 'Thr7', 0, 'r_lfs_thr7', NULL, 'Administrator'),
('Combine', 'ThrH_HCG[0]', 0, 'r_pLFSThrH_HCG[0]', NULL, 'Administrator'),
('Combine', 'ThrH_HCG[1]', 0, 'r_pLFSThrH_HCG[1]', NULL, 'Administrator'),
('Combine', 'ThrH_HCG[2]', 0, 'r_pLFSThrH_HCG[2]', NULL, 'Administrator'),
('Combine', 'ThrL_HCG[0]', 0, 'r_pLFSThrL_HCG[0]', NULL, 'Administrator'),
('Combine', 'ThrL_HCG[1]', 0, 'r_pLFSThrL_HCG[1]', NULL, 'Administrator'),
('Combine', 'ThrL_HCG[2]', 0, 'r_pLFSThrL_HCG[2]', NULL, 'Administrator'),
('Combine', 'ThrH_LCG[0]', 0, 'r_pLFSThrH_LCG[0]', NULL, 'Administrator'),
('Combine', 'ThrH_LCG[1]', 0, 'r_pLFSThrH_LCG[1]', NULL, 'Administrator'),
('Combine', 'ThrH_LCG[2]', 0, 'r_pLFSThrH_LCG[2]', NULL, 'Administrator'),
('Combine', 'ThrL_LCG[0]', 0, 'r_pLFSThrL_LCG[0]', NULL, 'Administrator'),
('Combine', 'ThrL_LCG[1]', 0, 'r_pLFSThrL_LCG[1]', NULL, 'Administrator'),
('Combine', 'ThrL_LCG[2]', 0, 'r_pLFSThrL_LCG[2]', NULL, 'Administrator'),
('Combine', 'GainPoint0', 0, 'r_pGainPoint[0]', NULL, 'Administrator'),
('Combine', 'GainPoint1', 0, 'r_pGainPoint[1]', NULL, 'Administrator'),
('Combine', 'GainPoint2', 0, 'r_pGainPoint[2]', NULL, 'Administrator'),
('Combine', 'Weight Thr', 0, 'r_lfs_weight_thr', NULL, 'Administrator'),
('Combine', 'CountRat 0', 0, 'r_nLFSCountRat', NULL, 'Administrator'),
('Combine', 'CountRat 1', 0, 'r_nLFSCountRat1', NULL, 'Administrator'),
('Combine', 'CurGain', 0, 'current L Gain', NULL, 'Administrator'),
('Combine', 'Blooming_shift3', 0, 'r_blooming_shift3', NULL, 'Administrator'),
('Combine','Current Gain L',0,'current L Gain',NULL,'Administrator'),
('Combine','Current Expo L',0,'current L Expo',NULL,'Administrator');

INSERT INTO ui_info_regmodule VALUES
('Combine','ManualCompS','COMB',1),
('Combine','Current Gain L','PipeCtrl',1),
('Combine','Current Expo L','PipeCtrl',1);
