DELETE FROM ui_info WHERE module_name='AEC' or module_name like 'AEC_%';
DELETE FROM ui_info_regmodule WHERE ui_module_name='AEC' or ui_module_name like 'AEC_%';
INSERT INTO ui_info VALUES 
('AEC','BandEnable L',0,'r_pBandEnable[0]',NULL,'Administrator'),
('AEC','BandEnable M',0,'r_pBandEnable[1]',NULL,'Administrator'),
('AEC','OneBandLim L',0,'r_pOneBandLimEnable[0]',NULL,'Administrator'),
('AEC','OneBandLim M',0,'r_pOneBandLimEnable[1]',NULL,'Administrator'),
('AEC','Enable',0,'r_bGradedExpoLimEn',NULL,'Administrator'),
('AEC','ExpoLimNode',0,'r_nExpoLimNode',NULL,'Administrator'),
('AEC','GainLimNode',0,'r_nGainLimNode',NULL,'Administrator'),
('AEC','TargetL 0',0,'r_pTargetL[0]',NULL,'Administrator'),
('AEC','TargetL 0 IR_AB',0,'r_pTargetL[0]',NULL,'Administrator'),
('AEC','TargetL 0 RGB_AB',0,'r_pTargetL[0]',NULL,'Administrator'),
('AEC','TargetL 1',0,'r_pTargetL[1]',NULL,'Administrator'),
('AEC','TargetL 1 IR_AB',0,'r_pTargetL[1]',NULL,'Administrator'),
('AEC','TargetL 1 RGB_AB',0,'r_pTargetL[1]',NULL,'Administrator'),
('AEC','TargetL 2',0,'r_pTargetL[2]',NULL,'Administrator'),
('AEC','TargetL 2 IR_AB',0,'r_pTargetL[2]',NULL,'Administrator'),
('AEC','TargetL 2 RGB_AB',0,'r_pTargetL[2]',NULL,'Administrator'),
('AEC','TargetL 3',0,'r_pTargetL[3]',NULL,'Administrator'),
('AEC','TargetL 3 IR_AB',0,'r_pTargetL[3]',NULL,'Administrator'),
('AEC','TargetL 3 RGB_AB',0,'r_pTargetL[3]',NULL,'Administrator'),
('AEC','TargetL 4',0,'r_pTargetL[4]',NULL,'Administrator'),
('AEC','TargetL 4 IR_AB',0,'r_pTargetL[4]',NULL,'Administrator'),
('AEC','TargetL 4 RGB_AB',0,'r_pTargetL[4]',NULL,'Administrator'),
('AEC','TargetL 5',0,'r_pTargetL[5]',NULL,'Administrator'),
('AEC','TargetL 5 IR_AB',0,'r_pTargetL[5]',NULL,'Administrator'),
('AEC','TargetL 5 RGB_AB',0,'r_pTargetL[5]',NULL,'Administrator'),
('AEC','TargetL 6',0,'r_pTargetL[6]',NULL,'Administrator'),
('AEC','TargetL 6 IR_AB',0,'r_pTargetL[6]',NULL,'Administrator'),
('AEC','TargetL 6 RGB_AB',0,'r_pTargetL[6]',NULL,'Administrator'),
('AEC','TargetL 7',0,'r_pTargetL[7]',NULL,'Administrator'),
('AEC','TargetL 7 IR_AB',0,'r_pTargetL[7]',NULL,'Administrator'),
('AEC','TargetL 7 RGB_AB',0,'r_pTargetL[7]',NULL,'Administrator'),
('AEC','Gain L',0,'current L Gain',NULL,'Administrator'),
('AEC','Gain M',0,'current M Gain',NULL,'Administrator'),
('AEC','Gain S',0,'current S Gain',NULL,'Administrator'),
('AEC','Gain LFS',0,'current LFS Gain',NULL,'Administrator'),
('AEC','Expo L',0,'current L Expo',NULL,'Administrator'),
('AEC','Expo M',0,'current M Expo',NULL,'Administrator'),
('AEC','Expo S',0,'current S Expo',NULL,'Administrator'),
('AEC','Expo LFS',0,'current LFS Expo',NULL,'Administrator'),
('AEC','EVShift',0,'r_nEVShift',NULL,'Administrator'),
('AEC','EVThreL 0',0,'r_pEVThreL[0]',NULL,'Administrator'),
('AEC','EVThreL 0 IR_AB',0,'r_pEVThreL[0]',NULL,'Administrator'),
('AEC','EVThreL 0 RGB_AB',0,'r_pEVThreL[0]',NULL,'Administrator'),
('AEC','EVThreL 1',0,'r_pEVThreL[1]',NULL,'Administrator'),
('AEC','EVThreL 1 IR_AB',0,'r_pEVThreL[1]',NULL,'Administrator'),
('AEC','EVThreL 1 RGB_AB',0,'r_pEVThreL[1]',NULL,'Administrator'),
('AEC','EVThreL 2',0,'r_pEVThreL[2]',NULL,'Administrator'),
('AEC','EVThreL 2 IR_AB',0,'r_pEVThreL[2]',NULL,'Administrator'),
('AEC','EVThreL 2 RGB_AB',0,'r_pEVThreL[2]',NULL,'Administrator'),
('AEC','EVThreL 3',0,'r_pEVThreL[3]',NULL,'Administrator'),
('AEC','EVThreL 3 IR_AB',0,'r_pEVThreL[3]',NULL,'Administrator'),
('AEC','EVThreL 3 RGB_AB',0,'r_pEVThreL[3]',NULL,'Administrator'),
('AEC','EVThreL 4',0,'r_pEVThreL[4]',NULL,'Administrator'),
('AEC','EVThreL 4 IR_AB',0,'r_pEVThreL[4]',NULL,'Administrator'),
('AEC','EVThreL 4 RGB_AB',0,'r_pEVThreL[4]',NULL,'Administrator'),
('AEC','EVThreL 5',0,'r_pEVThreL[5]',NULL,'Administrator'),
('AEC','EVThreL 5 IR_AB',0,'r_pEVThreL[5]',NULL,'Administrator'),
('AEC','EVThreL 5 RGB_AB',0,'r_pEVThreL[5]',NULL,'Administrator'),
('AEC','EVThreL 6',0,'r_pEVThreL[6]',NULL,'Administrator'),
('AEC','EVThreL 6 IR_AB',0,'r_pEVThreL[6]',NULL,'Administrator'),
('AEC','EVThreL 6 RGB_AB',0,'r_pEVThreL[6]',NULL,'Administrator'),
('AEC','EVThreL 7',0,'r_pEVThreL[7]',NULL,'Administrator'),
('AEC','EVThreL 7 IR_AB',0,'r_pEVThreL[7]',NULL,'Administrator'),
('AEC','EVThreL 7 RGB_AB',0,'r_pEVThreL[7]',NULL,'Administrator'),
('AEC','TargetL M',0,'r_nTargetM',NULL,'Administrator'),
('AEC','MaxFastRatio 0',0,'r_pMaxFastRatio[0]',NULL,'Administrator'),
('AEC','MaxFastRatio 1',0,'r_pMaxFastRatio[1]',NULL,'Administrator'),
('AEC','MaxSlowRatio 0',0,'r_pMaxSlowRatio[0]',NULL,'Administrator'),
('AEC','MaxSlowRatio 1',0,'r_pMaxSlowRatio[1]',NULL,'Administrator'),
('AEC','FastStep 0',0,'r_pFastStep[0]',NULL,'Administrator'),
('AEC','FastStep 1',0,'r_pFastStep[1]',NULL,'Administrator'),
('AEC','SlowStep 0',0,'r_pSlowStep[0]',NULL,'Administrator'),
('AEC','SlowStep 1',0,'r_pSlowStep[1]',NULL,'Administrator'),
('AEC','SlowRange 0',0,'r_pSlowRange[0]',NULL,'Administrator'),
('AEC','SlowRange 1',0,'r_pSlowRange[1]',NULL,'Administrator'),
('AEC','StableRange 0-0',0,'r_pStableRange[0][0]',NULL,'Administrator'),
('AEC','StableRange 0-1',0,'r_pStableRange[0][1]',NULL,'Administrator'),
('AEC','StableRange 1-0',0,'r_pStableRange[1][0]',NULL,'Administrator'),
('AEC','StableRange 1-1',0,'r_pStableRange[1][1]',NULL,'Administrator'),
('AEC','PresetUp 0',0,'r_pPresetUp[0]',NULL,'Administrator'),
('AEC','PresetDown 0',0,'r_pPresetDown[0]',NULL,'Administrator'),
('AEC','PresetUp 1',0,'r_pPresetUp[1]',NULL,'Administrator'),
('AEC','PresetDown 1',0,'r_pPresetDown[1]',NULL,'Administrator'),
('AEC','MinExpo 0',0,'r_pMinExpo[0]',NULL,'Administrator'),
('AEC','MinExpo 0 IR_AB',0,'r_pMinExpo[0]', NULL, 'Administrator'),
('AEC','MinExpo 0 RGB_AB',0,'r_pMinExpo[0]', NULL, 'Administrator'),
('AEC','MinExpo 1',0,'r_pMinExpo[1]',NULL,'Administrator'),
('AEC','MinExpo 2',0,'r_pMinExpo[2]',NULL,'Administrator'),
('AEC','MinExpo 3',0,'r_pMinExpo[3]',NULL,'Administrator'),
('AEC','MaxExpo 0',0,'r_pMaxExpo[0]',NULL,'Administrator'),
('AEC','MaxExpo 0 IR_AB',0,'r_pMaxExpo[0]', NULL, 'Administrator'),
('AEC','MaxExpo 0 RGB_AB',0,'r_pMaxExpo[0]', NULL, 'Administrator'),
('AEC','MaxExpo 1',0,'r_pMaxExpo[1]',NULL,'Administrator'),
('AEC','MaxExpo 2',0,'r_pMaxExpo[2]',NULL,'Administrator'),
('AEC','MaxExpo 3',0,'r_pMaxExpo[3]',NULL,'Administrator'),
('AEC','MinGain 0',0,'r_pMinGain[0]',NULL,'Administrator'),
('AEC','MinGain 0 IR_AB',0,'r_pMinGain[0]', NULL, 'Administrator'),
('AEC','MinGain 0 RGB_AB',0,'r_pMinGain[0]', NULL, 'Administrator'),
('AEC','MinGain 1',0,'r_pMinGain[1]',NULL,'Administrator'),
('AEC','MinGain 2',0,'r_pMinGain[2]',NULL,'Administrator'),
('AEC','MinGain 3',0,'r_pMinGain[3]',NULL,'Administrator'),
('AEC','MaxGain 0',0,'r_pMaxGain[0]',NULL,'Administrator'),
('AEC','MaxGain 0 IR_AB',0,'r_pMaxGain[0]', NULL, 'Administrator'),
('AEC','MaxGain 0 RGB_AB',0,'r_pMaxGain[0]', NULL, 'Administrator'),
('AEC','MaxGain 1',0,'r_pMaxGain[1]',NULL,'Administrator'),
('AEC','MaxGain 2',0,'r_pMaxGain[2]',NULL,'Administrator'),
('AEC','MaxGain 3',0,'r_pMaxGain[3]',NULL,'Administrator'),
('AEC','AECManEnable',0,'r_bAECManEnable',NULL,'Administrator'),
('AEC','Expo 0',0,'r_pManExpo[0]',NULL,'Administrator'),
('AEC','Expo 1',0,'r_pManExpo[1]',NULL,'Administrator'),
('AEC','Expo 2',0,'r_pManExpo[2]',NULL,'Administrator'),
('AEC','Expo 3',0,'r_pManExpo[3]',NULL,'Administrator'),
('AEC','Gain 0',0,'r_pManGain[0]',NULL,'Administrator'),
('AEC','Gain 1',0,'r_pManGain[1]',NULL,'Administrator'),
('AEC','Gain 2',0,'r_pManGain[2]',NULL,'Administrator'),
('AEC','Gain 3',0,'r_pManGain[3]',NULL,'Administrator'),
('AEC','PresetExp',0,'r_nPresetExp',NULL,'Administrator'),
('AEC','PresetGain',0,'r_nPresetGain',NULL,'Administrator'),
('AEC_L','roi_weight_en',0,'r_roi_weight_en',NULL,'Administrator'),
('AEC_L','Left',0,'r_left',NULL,'Administrator'),
('AEC_L','Top',0,'r_top',NULL,'Administrator'),
('AEC_L','Right',0,'r_right',NULL,'Administrator'),
('AEC_L','Bottom',0,'r_bottom',NULL,'Administrator'),
('AEC_L','roi_width',0,'r_roi_width',NULL,'Administrator'),
('AEC_L','roi_height',0,'r_roi_height',NULL,'Administrator'),
('AEC_L','sclh',0,'r_sclh',NULL,'Administrator'),
('AEC_L','sclv',0,'r_sclv',NULL,'Administrator'),
('AEC_L','roi_blk_w',0,'r_roi_blk_w[0]',NULL,'Administrator'),
('AEC_L','roi_blk_w',1,'r_roi_blk_w[1]',NULL,'Administrator'),
('AEC_L','roi_blk_w',2,'r_roi_blk_w[2]',NULL,'Administrator'),
('AEC_L','roi_blk_w',3,'r_roi_blk_w[3]',NULL,'Administrator'),
('AEC_L','roi_blk_w',4,'r_roi_blk_w[4]',NULL,'Administrator'),
('AEC_L','roi_blk_w',5,'r_roi_blk_w[5]',NULL,'Administrator'),
('AEC_L','roi_blk_w',6,'r_roi_blk_w[6]',NULL,'Administrator'),
('AEC_L','roi_blk_w',7,'r_roi_blk_w[7]',NULL,'Administrator'),
('AEC_L','roi_blk_w',8,'r_roi_blk_w[8]',NULL,'Administrator'),
('AEC_L','roi_blk_w',9,'r_roi_blk_w[9]',NULL,'Administrator'),
('AEC_L','roi_blk_w',10,'r_roi_blk_w[10]',NULL,'Administrator'),
('AEC_L','roi_blk_w',11,'r_roi_blk_w[11]',NULL,'Administrator'),
('AEC_L','roi_blk_w',12,'r_roi_blk_w[12]',NULL,'Administrator'),
('AEC_L','roi_blk_w',13,'r_roi_blk_w[13]',NULL,'Administrator'),
('AEC_L','roi_blk_w',14,'r_roi_blk_w[14]',NULL,'Administrator'),
('AEC_L','roi_blk_w',15,'r_roi_blk_w[15]',NULL,'Administrator'),
('AEC_L','roi_blk_w',16,'r_roi_blk_w[16]',NULL,'Administrator'),
('AEC_L','roi_blk_w',17,'r_roi_blk_w[17]',NULL,'Administrator'),
('AEC_L','roi_blk_w',18,'r_roi_blk_w[18]',NULL,'Administrator'),
('AEC_L','roi_blk_w',19,'r_roi_blk_w[19]',NULL,'Administrator'),
('AEC_L','roi_blk_w',20,'r_roi_blk_w[20]',NULL,'Administrator'),
('AEC_L','roi_blk_w',21,'r_roi_blk_w[21]',NULL,'Administrator'),
('AEC_L','roi_blk_w',22,'r_roi_blk_w[22]',NULL,'Administrator'),
('AEC_L','roi_blk_w',23,'r_roi_blk_w[23]',NULL,'Administrator'),
('AEC_L','roi_blk_w',24,'r_roi_blk_w[24]',NULL,'Administrator'),
('AEC_L','roi_blk_w',25,'r_roi_blk_w[25]',NULL,'Administrator'),
('AEC_L','roi_blk_w',26,'r_roi_blk_w[26]',NULL,'Administrator'),
('AEC_L','roi_blk_w',27,'r_roi_blk_w[27]',NULL,'Administrator'),
('AEC_L','roi_blk_w',28,'r_roi_blk_w[28]',NULL,'Administrator'),
('AEC_L','roi_blk_w',29,'r_roi_blk_w[29]',NULL,'Administrator'),
('AEC_L','roi_blk_w',30,'r_roi_blk_w[30]',NULL,'Administrator'),
('AEC_L','roi_blk_w',31,'r_roi_blk_w[31]',NULL,'Administrator'),
('AEC_L','roi_blk_w',32,'r_roi_blk_w[32]',NULL,'Administrator'),
('AEC_L','roi_blk_w',33,'r_roi_blk_w[33]',NULL,'Administrator'),
('AEC_L','roi_blk_w',34,'r_roi_blk_w[34]',NULL,'Administrator'),
('AEC_L','roi_blk_w',35,'r_roi_blk_w[35]',NULL,'Administrator'),
('AEC_L','roi_blk_w',36,'r_roi_blk_w[36]',NULL,'Administrator'),
('AEC_L','roi_blk_w',37,'r_roi_blk_w[37]',NULL,'Administrator'),
('AEC_L','roi_blk_w',38,'r_roi_blk_w[38]',NULL,'Administrator'),
('AEC_L','roi_blk_w',39,'r_roi_blk_w[39]',NULL,'Administrator'),
('AEC_L','roi_blk_w',40,'r_roi_blk_w[40]',NULL,'Administrator'),
('AEC_L','roi_blk_w',41,'r_roi_blk_w[41]',NULL,'Administrator'),
('AEC_L','roi_blk_w',42,'r_roi_blk_w[42]',NULL,'Administrator'),
('AEC_L','roi_blk_w',43,'r_roi_blk_w[43]',NULL,'Administrator'),
('AEC_L','roi_blk_w',44,'r_roi_blk_w[44]',NULL,'Administrator'),
('AEC_L','roi_blk_w',45,'r_roi_blk_w[45]',NULL,'Administrator'),
('AEC_L','roi_blk_w',46,'r_roi_blk_w[46]',NULL,'Administrator'),
('AEC_L','roi_blk_w',47,'r_roi_blk_w[47]',NULL,'Administrator'),
('AEC_L','roi_blk_w',48,'r_roi_blk_w[48]',NULL,'Administrator'),
('AEC_L','roi_blk_w',49,'r_roi_blk_w[49]',NULL,'Administrator'),
('AEC_L','roi_blk_w',50,'r_roi_blk_w[50]',NULL,'Administrator'),
('AEC_L','roi_blk_w',51,'r_roi_blk_w[51]',NULL,'Administrator'),
('AEC_L','roi_blk_w',52,'r_roi_blk_w[52]',NULL,'Administrator'),
('AEC_L','roi_blk_w',53,'r_roi_blk_w[53]',NULL,'Administrator'),
('AEC_L','roi_blk_w',54,'r_roi_blk_w[54]',NULL,'Administrator'),
('AEC_L','roi_blk_w',55,'r_roi_blk_w[55]',NULL,'Administrator'),
('AEC_L','roi_blk_w',56,'r_roi_blk_w[56]',NULL,'Administrator'),
('AEC_L','roi_blk_w',57,'r_roi_blk_w[57]',NULL,'Administrator'),
('AEC_L','roi_blk_w',58,'r_roi_blk_w[58]',NULL,'Administrator'),
('AEC_L','roi_blk_w',59,'r_roi_blk_w[59]',NULL,'Administrator'),
('AEC_L','roi_blk_w',60,'r_roi_blk_w[60]',NULL,'Administrator'),
('AEC_L','roi_blk_w',61,'r_roi_blk_w[61]',NULL,'Administrator'),
('AEC_L','roi_blk_w',62,'r_roi_blk_w[62]',NULL,'Administrator'),
('AEC_L','roi_blk_w',63,'r_roi_blk_w[63]',NULL,'Administrator'),
('AEC_L','roi_blk_w',64,'r_roi_blk_w[64]',NULL,'Administrator'),
('AEC_L','roi_blk_w',65,'r_roi_blk_w[65]',NULL,'Administrator'),
('AEC_L','roi_blk_w',66,'r_roi_blk_w[66]',NULL,'Administrator'),
('AEC_L','roi_blk_w',67,'r_roi_blk_w[67]',NULL,'Administrator'),
('AEC_L','roi_blk_w',68,'r_roi_blk_w[68]',NULL,'Administrator'),
('AEC_L','roi_blk_w',69,'r_roi_blk_w[69]',NULL,'Administrator'),
('AEC_L','roi_blk_w',70,'r_roi_blk_w[70]',NULL,'Administrator'),
('AEC_L','roi_blk_w',71,'r_roi_blk_w[71]',NULL,'Administrator'),
('AEC_L','roi_blk_w',72,'r_roi_blk_w[72]',NULL,'Administrator'),
('AEC_L','roi_blk_w',73,'r_roi_blk_w[73]',NULL,'Administrator'),
('AEC_L','roi_blk_w',74,'r_roi_blk_w[74]',NULL,'Administrator'),
('AEC_L','roi_blk_w',75,'r_roi_blk_w[75]',NULL,'Administrator'),
('AEC_L','roi_blk_w',76,'r_roi_blk_w[76]',NULL,'Administrator'),
('AEC_L','roi_blk_w',77,'r_roi_blk_w[77]',NULL,'Administrator'),
('AEC_L','roi_blk_w',78,'r_roi_blk_w[78]',NULL,'Administrator'),
('AEC_L','roi_blk_w',79,'r_roi_blk_w[79]',NULL,'Administrator'),
('AEC_L','roi_blk_w',80,'r_roi_blk_w[80]',NULL,'Administrator'),
('AEC_L','roi_blk_w',81,'r_roi_blk_w[81]',NULL,'Administrator'),
('AEC_L','roi_blk_w',82,'r_roi_blk_w[82]',NULL,'Administrator'),
('AEC_L','roi_blk_w',83,'r_roi_blk_w[83]',NULL,'Administrator'),
('AEC_L','roi_blk_w',84,'r_roi_blk_w[84]',NULL,'Administrator'),
('AEC_L','roi_blk_w',85,'r_roi_blk_w[85]',NULL,'Administrator'),
('AEC_L','roi_blk_w',86,'r_roi_blk_w[86]',NULL,'Administrator'),
('AEC_L','roi_blk_w',87,'r_roi_blk_w[87]',NULL,'Administrator'),
('AEC_L','roi_blk_w',88,'r_roi_blk_w[88]',NULL,'Administrator'),
('AEC_L','roi_blk_w',89,'r_roi_blk_w[89]',NULL,'Administrator'),
('AEC_L','roi_blk_w',90,'r_roi_blk_w[90]',NULL,'Administrator'),
('AEC_L','roi_blk_w',91,'r_roi_blk_w[91]',NULL,'Administrator'),
('AEC_L','roi_blk_w',92,'r_roi_blk_w[92]',NULL,'Administrator'),
('AEC_L','roi_blk_w',93,'r_roi_blk_w[93]',NULL,'Administrator'),
('AEC_L','roi_blk_w',94,'r_roi_blk_w[94]',NULL,'Administrator'),
('AEC_L','roi_blk_w',95,'r_roi_blk_w[95]',NULL,'Administrator'),
('AEC_L','roi_blk_w',96,'r_roi_blk_w[96]',NULL,'Administrator'),
('AEC_L','roi_blk_w',97,'r_roi_blk_w[97]',NULL,'Administrator'),
('AEC_L','roi_blk_w',98,'r_roi_blk_w[98]',NULL,'Administrator'),
('AEC_L','roi_blk_w',99,'r_roi_blk_w[99]',NULL,'Administrator'),
('AEC_L','roi_blk_w',100,'r_roi_blk_w[100]',NULL,'Administrator'),
('AEC_L','roi_blk_w',101,'r_roi_blk_w[101]',NULL,'Administrator'),
('AEC_L','roi_blk_w',102,'r_roi_blk_w[102]',NULL,'Administrator'),
('AEC_L','roi_blk_w',103,'r_roi_blk_w[103]',NULL,'Administrator'),
('AEC_L','roi_blk_w',104,'r_roi_blk_w[104]',NULL,'Administrator'),
('AEC_L','roi_blk_w',105,'r_roi_blk_w[105]',NULL,'Administrator'),
('AEC_L','roi_blk_w',106,'r_roi_blk_w[106]',NULL,'Administrator'),
('AEC_L','roi_blk_w',107,'r_roi_blk_w[107]',NULL,'Administrator'),
('AEC_L','roi_blk_w',108,'r_roi_blk_w[108]',NULL,'Administrator'),
('AEC_L','roi_blk_w',109,'r_roi_blk_w[109]',NULL,'Administrator'),
('AEC_L','roi_blk_w',110,'r_roi_blk_w[110]',NULL,'Administrator'),
('AEC_L','roi_blk_w',111,'r_roi_blk_w[111]',NULL,'Administrator'),
('AEC_L','roi_blk_w',112,'r_roi_blk_w[112]',NULL,'Administrator'),
('AEC_L','roi_blk_w',113,'r_roi_blk_w[113]',NULL,'Administrator'),
('AEC_L','roi_blk_w',114,'r_roi_blk_w[114]',NULL,'Administrator'),
('AEC_L','roi_blk_w',115,'r_roi_blk_w[115]',NULL,'Administrator'),
('AEC_L','roi_blk_w',116,'r_roi_blk_w[116]',NULL,'Administrator'),
('AEC_L','roi_blk_w',117,'r_roi_blk_w[117]',NULL,'Administrator'),
('AEC_L','roi_blk_w',118,'r_roi_blk_w[118]',NULL,'Administrator'),
('AEC_L','roi_blk_w',119,'r_roi_blk_w[119]',NULL,'Administrator'),
('AEC_L','roi_blk_w',120,'r_roi_blk_w[120]',NULL,'Administrator'),
('AEC_L','roi_blk_w',121,'r_roi_blk_w[121]',NULL,'Administrator'),
('AEC_L','roi_blk_w',122,'r_roi_blk_w[122]',NULL,'Administrator'),
('AEC_L','roi_blk_w',123,'r_roi_blk_w[123]',NULL,'Administrator'),
('AEC_L','roi_blk_w',124,'r_roi_blk_w[124]',NULL,'Administrator'),
('AEC_L','roi_blk_w',125,'r_roi_blk_w[125]',NULL,'Administrator'),
('AEC_L','roi_blk_w',126,'r_roi_blk_w[126]',NULL,'Administrator'),
('AEC_L','roi_blk_w',127,'r_roi_blk_w[127]',NULL,'Administrator'),
('AEC_L','roi_blk_w',128,'r_roi_blk_w[128]',NULL,'Administrator'),
('AEC_L','roi_blk_w',129,'r_roi_blk_w[129]',NULL,'Administrator'),
('AEC_L','roi_blk_w',130,'r_roi_blk_w[130]',NULL,'Administrator'),
('AEC_L','roi_blk_w',131,'r_roi_blk_w[131]',NULL,'Administrator'),
('AEC_L','roi_blk_w',132,'r_roi_blk_w[132]',NULL,'Administrator'),
('AEC_L','roi_blk_w',133,'r_roi_blk_w[133]',NULL,'Administrator'),
('AEC_L','roi_blk_w',134,'r_roi_blk_w[134]',NULL,'Administrator'),
('AEC_L','roi_blk_w',135,'r_roi_blk_w[135]',NULL,'Administrator'),
('AEC_L','roi_blk_w',136,'r_roi_blk_w[136]',NULL,'Administrator'),
('AEC_L','roi_blk_w',137,'r_roi_blk_w[137]',NULL,'Administrator'),
('AEC_L','roi_blk_w',138,'r_roi_blk_w[138]',NULL,'Administrator'),
('AEC_L','roi_blk_w',139,'r_roi_blk_w[139]',NULL,'Administrator'),
('AEC_L','roi_blk_w',140,'r_roi_blk_w[140]',NULL,'Administrator'),
('AEC_L','roi_blk_w',141,'r_roi_blk_w[141]',NULL,'Administrator'),
('AEC_L','roi_blk_w',142,'r_roi_blk_w[142]',NULL,'Administrator'),
('AEC_L','roi_blk_w',143,'r_roi_blk_w[143]',NULL,'Administrator'),
('AEC_L','roi_blk_w',144,'r_roi_blk_w[144]',NULL,'Administrator'),
('AEC_L','roi_blk_w',145,'r_roi_blk_w[145]',NULL,'Administrator'),
('AEC_L','roi_blk_w',146,'r_roi_blk_w[146]',NULL,'Administrator'),
('AEC_L','roi_blk_w',147,'r_roi_blk_w[147]',NULL,'Administrator'),
('AEC_L','roi_blk_w',148,'r_roi_blk_w[148]',NULL,'Administrator'),
('AEC_L','roi_blk_w',149,'r_roi_blk_w[149]',NULL,'Administrator'),
('AEC_L','roi_blk_w',150,'r_roi_blk_w[150]',NULL,'Administrator'),
('AEC_L','roi_blk_w',151,'r_roi_blk_w[151]',NULL,'Administrator'),
('AEC_L','roi_blk_w',152,'r_roi_blk_w[152]',NULL,'Administrator'),
('AEC_L','roi_blk_w',153,'r_roi_blk_w[153]',NULL,'Administrator'),
('AEC_L','roi_blk_w',154,'r_roi_blk_w[154]',NULL,'Administrator'),
('AEC_L','roi_blk_w',155,'r_roi_blk_w[155]',NULL,'Administrator'),
('AEC_L','roi_blk_w',156,'r_roi_blk_w[156]',NULL,'Administrator'),
('AEC_L','roi_blk_w',157,'r_roi_blk_w[157]',NULL,'Administrator'),
('AEC_L','roi_blk_w',158,'r_roi_blk_w[158]',NULL,'Administrator'),
('AEC_L','roi_blk_w',159,'r_roi_blk_w[159]',NULL,'Administrator'),
('AEC_L','roi_blk_w',160,'r_roi_blk_w[160]',NULL,'Administrator'),
('AEC_L','roi_blk_w',161,'r_roi_blk_w[161]',NULL,'Administrator'),
('AEC_L','roi_blk_w',162,'r_roi_blk_w[162]',NULL,'Administrator'),
('AEC_L','roi_blk_w',163,'r_roi_blk_w[163]',NULL,'Administrator'),
('AEC_L','roi_blk_w',164,'r_roi_blk_w[164]',NULL,'Administrator'),
('AEC_L','roi_blk_w',165,'r_roi_blk_w[165]',NULL,'Administrator'),
('AEC_L','roi_blk_w',166,'r_roi_blk_w[166]',NULL,'Administrator'),
('AEC_L','roi_blk_w',167,'r_roi_blk_w[167]',NULL,'Administrator'),
('AEC_L','roi_blk_w',168,'r_roi_blk_w[168]',NULL,'Administrator'),
('AEC_L','roi_blk_w',169,'r_roi_blk_w[169]',NULL,'Administrator'),
('AEC_L','roi_blk_w',170,'r_roi_blk_w[170]',NULL,'Administrator'),
('AEC_L','roi_blk_w',171,'r_roi_blk_w[171]',NULL,'Administrator'),
('AEC_L','roi_blk_w',172,'r_roi_blk_w[172]',NULL,'Administrator'),
('AEC_L','roi_blk_w',173,'r_roi_blk_w[173]',NULL,'Administrator'),
('AEC_L','roi_blk_w',174,'r_roi_blk_w[174]',NULL,'Administrator'),
('AEC_L','roi_blk_w',175,'r_roi_blk_w[175]',NULL,'Administrator'),
('AEC_L','roi_blk_w',176,'r_roi_blk_w[176]',NULL,'Administrator'),
('AEC_L','roi_blk_w',177,'r_roi_blk_w[177]',NULL,'Administrator'),
('AEC_L','roi_blk_w',178,'r_roi_blk_w[178]',NULL,'Administrator'),
('AEC_L','roi_blk_w',179,'r_roi_blk_w[179]',NULL,'Administrator'),
('AEC_L','roi_blk_w',180,'r_roi_blk_w[180]',NULL,'Administrator'),
('AEC_L','roi_blk_w',181,'r_roi_blk_w[181]',NULL,'Administrator'),
('AEC_L','roi_blk_w',182,'r_roi_blk_w[182]',NULL,'Administrator'),
('AEC_L','roi_blk_w',183,'r_roi_blk_w[183]',NULL,'Administrator'),
('AEC_L','roi_blk_w',184,'r_roi_blk_w[184]',NULL,'Administrator'),
('AEC_L','roi_blk_w',185,'r_roi_blk_w[185]',NULL,'Administrator'),
('AEC_L','roi_blk_w',186,'r_roi_blk_w[186]',NULL,'Administrator'),
('AEC_L','roi_blk_w',187,'r_roi_blk_w[187]',NULL,'Administrator'),
('AEC_L','roi_blk_w',188,'r_roi_blk_w[188]',NULL,'Administrator'),
('AEC_L','roi_blk_w',189,'r_roi_blk_w[189]',NULL,'Administrator'),
('AEC_L','roi_blk_w',190,'r_roi_blk_w[190]',NULL,'Administrator'),
('AEC_L','roi_blk_w',191,'r_roi_blk_w[191]',NULL,'Administrator'),
('AEC_M','roi_weight_en',0,'r_roi_weight_en',NULL,'Administrator'),
('AEC_M','Left',0,'r_left',NULL,'Administrator'),
('AEC_M','Top',0,'r_top',NULL,'Administrator'),
('AEC_M','Right',0,'r_right',NULL,'Administrator'),
('AEC_M','Bottom',0,'r_bottom',NULL,'Administrator'),
('AEC_M','roi_width',0,'r_roi_width',NULL,'Administrator'),
('AEC_M','roi_height',0,'r_roi_height',NULL,'Administrator'),
('AEC_M','sclh',0,'r_sclh',NULL,'Administrator'),
('AEC_M','sclv',0,'r_sclv',NULL,'Administrator'),
('AEC_M','roi_blk_w',0,'r_roi_blk_w[0]',NULL,'Administrator'),
('AEC_M','roi_blk_w',1,'r_roi_blk_w[1]',NULL,'Administrator'),
('AEC_M','roi_blk_w',2,'r_roi_blk_w[2]',NULL,'Administrator'),
('AEC_M','roi_blk_w',3,'r_roi_blk_w[3]',NULL,'Administrator'),
('AEC_M','roi_blk_w',4,'r_roi_blk_w[4]',NULL,'Administrator'),
('AEC_M','roi_blk_w',5,'r_roi_blk_w[5]',NULL,'Administrator'),
('AEC_M','roi_blk_w',6,'r_roi_blk_w[6]',NULL,'Administrator'),
('AEC_M','roi_blk_w',7,'r_roi_blk_w[7]',NULL,'Administrator'),
('AEC_M','roi_blk_w',8,'r_roi_blk_w[8]',NULL,'Administrator'),
('AEC_M','roi_blk_w',9,'r_roi_blk_w[9]',NULL,'Administrator'),
('AEC_M','roi_blk_w',10,'r_roi_blk_w[10]',NULL,'Administrator'),
('AEC_M','roi_blk_w',11,'r_roi_blk_w[11]',NULL,'Administrator'),
('AEC_M','roi_blk_w',12,'r_roi_blk_w[12]',NULL,'Administrator'),
('AEC_M','roi_blk_w',13,'r_roi_blk_w[13]',NULL,'Administrator'),
('AEC_M','roi_blk_w',14,'r_roi_blk_w[14]',NULL,'Administrator'),
('AEC_M','roi_blk_w',15,'r_roi_blk_w[15]',NULL,'Administrator'),
('AEC_M','roi_blk_w',16,'r_roi_blk_w[16]',NULL,'Administrator'),
('AEC_M','roi_blk_w',17,'r_roi_blk_w[17]',NULL,'Administrator'),
('AEC_M','roi_blk_w',18,'r_roi_blk_w[18]',NULL,'Administrator'),
('AEC_M','roi_blk_w',19,'r_roi_blk_w[19]',NULL,'Administrator'),
('AEC_M','roi_blk_w',20,'r_roi_blk_w[20]',NULL,'Administrator'),
('AEC_M','roi_blk_w',21,'r_roi_blk_w[21]',NULL,'Administrator'),
('AEC_M','roi_blk_w',22,'r_roi_blk_w[22]',NULL,'Administrator'),
('AEC_M','roi_blk_w',23,'r_roi_blk_w[23]',NULL,'Administrator'),
('AEC_M','roi_blk_w',24,'r_roi_blk_w[24]',NULL,'Administrator'),
('AEC_M','roi_blk_w',25,'r_roi_blk_w[25]',NULL,'Administrator'),
('AEC_M','roi_blk_w',26,'r_roi_blk_w[26]',NULL,'Administrator'),
('AEC_M','roi_blk_w',27,'r_roi_blk_w[27]',NULL,'Administrator'),
('AEC_M','roi_blk_w',28,'r_roi_blk_w[28]',NULL,'Administrator'),
('AEC_M','roi_blk_w',29,'r_roi_blk_w[29]',NULL,'Administrator'),
('AEC_M','roi_blk_w',30,'r_roi_blk_w[30]',NULL,'Administrator'),
('AEC_M','roi_blk_w',31,'r_roi_blk_w[31]',NULL,'Administrator'),
('AEC_M','roi_blk_w',32,'r_roi_blk_w[32]',NULL,'Administrator'),
('AEC_M','roi_blk_w',33,'r_roi_blk_w[33]',NULL,'Administrator'),
('AEC_M','roi_blk_w',34,'r_roi_blk_w[34]',NULL,'Administrator'),
('AEC_M','roi_blk_w',35,'r_roi_blk_w[35]',NULL,'Administrator'),
('AEC_M','roi_blk_w',36,'r_roi_blk_w[36]',NULL,'Administrator'),
('AEC_M','roi_blk_w',37,'r_roi_blk_w[37]',NULL,'Administrator'),
('AEC_M','roi_blk_w',38,'r_roi_blk_w[38]',NULL,'Administrator'),
('AEC_M','roi_blk_w',39,'r_roi_blk_w[39]',NULL,'Administrator'),
('AEC_M','roi_blk_w',40,'r_roi_blk_w[40]',NULL,'Administrator'),
('AEC_M','roi_blk_w',41,'r_roi_blk_w[41]',NULL,'Administrator'),
('AEC_M','roi_blk_w',42,'r_roi_blk_w[42]',NULL,'Administrator'),
('AEC_M','roi_blk_w',43,'r_roi_blk_w[43]',NULL,'Administrator'),
('AEC_M','roi_blk_w',44,'r_roi_blk_w[44]',NULL,'Administrator'),
('AEC_M','roi_blk_w',45,'r_roi_blk_w[45]',NULL,'Administrator'),
('AEC_M','roi_blk_w',46,'r_roi_blk_w[46]',NULL,'Administrator'),
('AEC_M','roi_blk_w',47,'r_roi_blk_w[47]',NULL,'Administrator'),
('AEC_M','roi_blk_w',48,'r_roi_blk_w[48]',NULL,'Administrator'),
('AEC_M','roi_blk_w',49,'r_roi_blk_w[49]',NULL,'Administrator'),
('AEC_M','roi_blk_w',50,'r_roi_blk_w[50]',NULL,'Administrator'),
('AEC_M','roi_blk_w',51,'r_roi_blk_w[51]',NULL,'Administrator'),
('AEC_M','roi_blk_w',52,'r_roi_blk_w[52]',NULL,'Administrator'),
('AEC_M','roi_blk_w',53,'r_roi_blk_w[53]',NULL,'Administrator'),
('AEC_M','roi_blk_w',54,'r_roi_blk_w[54]',NULL,'Administrator'),
('AEC_M','roi_blk_w',55,'r_roi_blk_w[55]',NULL,'Administrator'),
('AEC_M','roi_blk_w',56,'r_roi_blk_w[56]',NULL,'Administrator'),
('AEC_M','roi_blk_w',57,'r_roi_blk_w[57]',NULL,'Administrator'),
('AEC_M','roi_blk_w',58,'r_roi_blk_w[58]',NULL,'Administrator'),
('AEC_M','roi_blk_w',59,'r_roi_blk_w[59]',NULL,'Administrator'),
('AEC_M','roi_blk_w',60,'r_roi_blk_w[60]',NULL,'Administrator'),
('AEC_M','roi_blk_w',61,'r_roi_blk_w[61]',NULL,'Administrator'),
('AEC_M','roi_blk_w',62,'r_roi_blk_w[62]',NULL,'Administrator'),
('AEC_M','roi_blk_w',63,'r_roi_blk_w[63]',NULL,'Administrator'),
('AEC_M','roi_blk_w',64,'r_roi_blk_w[64]',NULL,'Administrator'),
('AEC_M','roi_blk_w',65,'r_roi_blk_w[65]',NULL,'Administrator'),
('AEC_M','roi_blk_w',66,'r_roi_blk_w[66]',NULL,'Administrator'),
('AEC_M','roi_blk_w',67,'r_roi_blk_w[67]',NULL,'Administrator'),
('AEC_M','roi_blk_w',68,'r_roi_blk_w[68]',NULL,'Administrator'),
('AEC_M','roi_blk_w',69,'r_roi_blk_w[69]',NULL,'Administrator'),
('AEC_M','roi_blk_w',70,'r_roi_blk_w[70]',NULL,'Administrator'),
('AEC_M','roi_blk_w',71,'r_roi_blk_w[71]',NULL,'Administrator'),
('AEC_M','roi_blk_w',72,'r_roi_blk_w[72]',NULL,'Administrator'),
('AEC_M','roi_blk_w',73,'r_roi_blk_w[73]',NULL,'Administrator'),
('AEC_M','roi_blk_w',74,'r_roi_blk_w[74]',NULL,'Administrator'),
('AEC_M','roi_blk_w',75,'r_roi_blk_w[75]',NULL,'Administrator'),
('AEC_M','roi_blk_w',76,'r_roi_blk_w[76]',NULL,'Administrator'),
('AEC_M','roi_blk_w',77,'r_roi_blk_w[77]',NULL,'Administrator'),
('AEC_M','roi_blk_w',78,'r_roi_blk_w[78]',NULL,'Administrator'),
('AEC_M','roi_blk_w',79,'r_roi_blk_w[79]',NULL,'Administrator'),
('AEC_M','roi_blk_w',80,'r_roi_blk_w[80]',NULL,'Administrator'),
('AEC_M','roi_blk_w',81,'r_roi_blk_w[81]',NULL,'Administrator'),
('AEC_M','roi_blk_w',82,'r_roi_blk_w[82]',NULL,'Administrator'),
('AEC_M','roi_blk_w',83,'r_roi_blk_w[83]',NULL,'Administrator'),
('AEC_M','roi_blk_w',84,'r_roi_blk_w[84]',NULL,'Administrator'),
('AEC_M','roi_blk_w',85,'r_roi_blk_w[85]',NULL,'Administrator'),
('AEC_M','roi_blk_w',86,'r_roi_blk_w[86]',NULL,'Administrator'),
('AEC_M','roi_blk_w',87,'r_roi_blk_w[87]',NULL,'Administrator'),
('AEC_M','roi_blk_w',88,'r_roi_blk_w[88]',NULL,'Administrator'),
('AEC_M','roi_blk_w',89,'r_roi_blk_w[89]',NULL,'Administrator'),
('AEC_M','roi_blk_w',90,'r_roi_blk_w[90]',NULL,'Administrator'),
('AEC_M','roi_blk_w',91,'r_roi_blk_w[91]',NULL,'Administrator'),
('AEC_M','roi_blk_w',92,'r_roi_blk_w[92]',NULL,'Administrator'),
('AEC_M','roi_blk_w',93,'r_roi_blk_w[93]',NULL,'Administrator'),
('AEC_M','roi_blk_w',94,'r_roi_blk_w[94]',NULL,'Administrator'),
('AEC_M','roi_blk_w',95,'r_roi_blk_w[95]',NULL,'Administrator'),
('AEC_M','roi_blk_w',96,'r_roi_blk_w[96]',NULL,'Administrator'),
('AEC_M','roi_blk_w',97,'r_roi_blk_w[97]',NULL,'Administrator'),
('AEC_M','roi_blk_w',98,'r_roi_blk_w[98]',NULL,'Administrator'),
('AEC_M','roi_blk_w',99,'r_roi_blk_w[99]',NULL,'Administrator'),
('AEC_M','roi_blk_w',100,'r_roi_blk_w[100]',NULL,'Administrator'),
('AEC_M','roi_blk_w',101,'r_roi_blk_w[101]',NULL,'Administrator'),
('AEC_M','roi_blk_w',102,'r_roi_blk_w[102]',NULL,'Administrator'),
('AEC_M','roi_blk_w',103,'r_roi_blk_w[103]',NULL,'Administrator'),
('AEC_M','roi_blk_w',104,'r_roi_blk_w[104]',NULL,'Administrator'),
('AEC_M','roi_blk_w',105,'r_roi_blk_w[105]',NULL,'Administrator'),
('AEC_M','roi_blk_w',106,'r_roi_blk_w[106]',NULL,'Administrator'),
('AEC_M','roi_blk_w',107,'r_roi_blk_w[107]',NULL,'Administrator'),
('AEC_M','roi_blk_w',108,'r_roi_blk_w[108]',NULL,'Administrator'),
('AEC_M','roi_blk_w',109,'r_roi_blk_w[109]',NULL,'Administrator'),
('AEC_M','roi_blk_w',110,'r_roi_blk_w[110]',NULL,'Administrator'),
('AEC_M','roi_blk_w',111,'r_roi_blk_w[111]',NULL,'Administrator'),
('AEC_M','roi_blk_w',112,'r_roi_blk_w[112]',NULL,'Administrator'),
('AEC_M','roi_blk_w',113,'r_roi_blk_w[113]',NULL,'Administrator'),
('AEC_M','roi_blk_w',114,'r_roi_blk_w[114]',NULL,'Administrator'),
('AEC_M','roi_blk_w',115,'r_roi_blk_w[115]',NULL,'Administrator'),
('AEC_M','roi_blk_w',116,'r_roi_blk_w[116]',NULL,'Administrator'),
('AEC_M','roi_blk_w',117,'r_roi_blk_w[117]',NULL,'Administrator'),
('AEC_M','roi_blk_w',118,'r_roi_blk_w[118]',NULL,'Administrator'),
('AEC_M','roi_blk_w',119,'r_roi_blk_w[119]',NULL,'Administrator'),
('AEC_M','roi_blk_w',120,'r_roi_blk_w[120]',NULL,'Administrator'),
('AEC_M','roi_blk_w',121,'r_roi_blk_w[121]',NULL,'Administrator'),
('AEC_M','roi_blk_w',122,'r_roi_blk_w[122]',NULL,'Administrator'),
('AEC_M','roi_blk_w',123,'r_roi_blk_w[123]',NULL,'Administrator'),
('AEC_M','roi_blk_w',124,'r_roi_blk_w[124]',NULL,'Administrator'),
('AEC_M','roi_blk_w',125,'r_roi_blk_w[125]',NULL,'Administrator'),
('AEC_M','roi_blk_w',126,'r_roi_blk_w[126]',NULL,'Administrator'),
('AEC_M','roi_blk_w',127,'r_roi_blk_w[127]',NULL,'Administrator'),
('AEC_M','roi_blk_w',128,'r_roi_blk_w[128]',NULL,'Administrator'),
('AEC_M','roi_blk_w',129,'r_roi_blk_w[129]',NULL,'Administrator'),
('AEC_M','roi_blk_w',130,'r_roi_blk_w[130]',NULL,'Administrator'),
('AEC_M','roi_blk_w',131,'r_roi_blk_w[131]',NULL,'Administrator'),
('AEC_M','roi_blk_w',132,'r_roi_blk_w[132]',NULL,'Administrator'),
('AEC_M','roi_blk_w',133,'r_roi_blk_w[133]',NULL,'Administrator'),
('AEC_M','roi_blk_w',134,'r_roi_blk_w[134]',NULL,'Administrator'),
('AEC_M','roi_blk_w',135,'r_roi_blk_w[135]',NULL,'Administrator'),
('AEC_M','roi_blk_w',136,'r_roi_blk_w[136]',NULL,'Administrator'),
('AEC_M','roi_blk_w',137,'r_roi_blk_w[137]',NULL,'Administrator'),
('AEC_M','roi_blk_w',138,'r_roi_blk_w[138]',NULL,'Administrator'),
('AEC_M','roi_blk_w',139,'r_roi_blk_w[139]',NULL,'Administrator'),
('AEC_M','roi_blk_w',140,'r_roi_blk_w[140]',NULL,'Administrator'),
('AEC_M','roi_blk_w',141,'r_roi_blk_w[141]',NULL,'Administrator'),
('AEC_M','roi_blk_w',142,'r_roi_blk_w[142]',NULL,'Administrator'),
('AEC_M','roi_blk_w',143,'r_roi_blk_w[143]',NULL,'Administrator'),
('AEC_M','roi_blk_w',144,'r_roi_blk_w[144]',NULL,'Administrator'),
('AEC_M','roi_blk_w',145,'r_roi_blk_w[145]',NULL,'Administrator'),
('AEC_M','roi_blk_w',146,'r_roi_blk_w[146]',NULL,'Administrator'),
('AEC_M','roi_blk_w',147,'r_roi_blk_w[147]',NULL,'Administrator'),
('AEC_M','roi_blk_w',148,'r_roi_blk_w[148]',NULL,'Administrator'),
('AEC_M','roi_blk_w',149,'r_roi_blk_w[149]',NULL,'Administrator'),
('AEC_M','roi_blk_w',150,'r_roi_blk_w[150]',NULL,'Administrator'),
('AEC_M','roi_blk_w',151,'r_roi_blk_w[151]',NULL,'Administrator'),
('AEC_M','roi_blk_w',152,'r_roi_blk_w[152]',NULL,'Administrator'),
('AEC_M','roi_blk_w',153,'r_roi_blk_w[153]',NULL,'Administrator'),
('AEC_M','roi_blk_w',154,'r_roi_blk_w[154]',NULL,'Administrator'),
('AEC_M','roi_blk_w',155,'r_roi_blk_w[155]',NULL,'Administrator'),
('AEC_M','roi_blk_w',156,'r_roi_blk_w[156]',NULL,'Administrator'),
('AEC_M','roi_blk_w',157,'r_roi_blk_w[157]',NULL,'Administrator'),
('AEC_M','roi_blk_w',158,'r_roi_blk_w[158]',NULL,'Administrator'),
('AEC_M','roi_blk_w',159,'r_roi_blk_w[159]',NULL,'Administrator'),
('AEC_M','roi_blk_w',160,'r_roi_blk_w[160]',NULL,'Administrator'),
('AEC_M','roi_blk_w',161,'r_roi_blk_w[161]',NULL,'Administrator'),
('AEC_M','roi_blk_w',162,'r_roi_blk_w[162]',NULL,'Administrator'),
('AEC_M','roi_blk_w',163,'r_roi_blk_w[163]',NULL,'Administrator'),
('AEC_M','roi_blk_w',164,'r_roi_blk_w[164]',NULL,'Administrator'),
('AEC_M','roi_blk_w',165,'r_roi_blk_w[165]',NULL,'Administrator'),
('AEC_M','roi_blk_w',166,'r_roi_blk_w[166]',NULL,'Administrator'),
('AEC_M','roi_blk_w',167,'r_roi_blk_w[167]',NULL,'Administrator'),
('AEC_M','roi_blk_w',168,'r_roi_blk_w[168]',NULL,'Administrator'),
('AEC_M','roi_blk_w',169,'r_roi_blk_w[169]',NULL,'Administrator'),
('AEC_M','roi_blk_w',170,'r_roi_blk_w[170]',NULL,'Administrator'),
('AEC_M','roi_blk_w',171,'r_roi_blk_w[171]',NULL,'Administrator'),
('AEC_M','roi_blk_w',172,'r_roi_blk_w[172]',NULL,'Administrator'),
('AEC_M','roi_blk_w',173,'r_roi_blk_w[173]',NULL,'Administrator'),
('AEC_M','roi_blk_w',174,'r_roi_blk_w[174]',NULL,'Administrator'),
('AEC_M','roi_blk_w',175,'r_roi_blk_w[175]',NULL,'Administrator'),
('AEC_M','roi_blk_w',176,'r_roi_blk_w[176]',NULL,'Administrator'),
('AEC_M','roi_blk_w',177,'r_roi_blk_w[177]',NULL,'Administrator'),
('AEC_M','roi_blk_w',178,'r_roi_blk_w[178]',NULL,'Administrator'),
('AEC_M','roi_blk_w',179,'r_roi_blk_w[179]',NULL,'Administrator'),
('AEC_M','roi_blk_w',180,'r_roi_blk_w[180]',NULL,'Administrator'),
('AEC_M','roi_blk_w',181,'r_roi_blk_w[181]',NULL,'Administrator'),
('AEC_M','roi_blk_w',182,'r_roi_blk_w[182]',NULL,'Administrator'),
('AEC_M','roi_blk_w',183,'r_roi_blk_w[183]',NULL,'Administrator'),
('AEC_M','roi_blk_w',184,'r_roi_blk_w[184]',NULL,'Administrator'),
('AEC_M','roi_blk_w',185,'r_roi_blk_w[185]',NULL,'Administrator'),
('AEC_M','roi_blk_w',186,'r_roi_blk_w[186]',NULL,'Administrator'),
('AEC_M','roi_blk_w',187,'r_roi_blk_w[187]',NULL,'Administrator'),
('AEC_M','roi_blk_w',188,'r_roi_blk_w[188]',NULL,'Administrator'),
('AEC_M','roi_blk_w',189,'r_roi_blk_w[189]',NULL,'Administrator'),
('AEC_M','roi_blk_w',190,'r_roi_blk_w[190]',NULL,'Administrator'),
('AEC_M','roi_blk_w',191,'r_roi_blk_w[191]',NULL,'Administrator'),
('AEC_S','roi_weight_en',0,'r_roi_weight_en',NULL,'Administrator'),
('AEC_S','Left',0,'r_left',NULL,'Administrator'),
('AEC_S','Top',0,'r_top',NULL,'Administrator'),
('AEC_S','Right',0,'r_right',NULL,'Administrator'),
('AEC_S','Bottom',0,'r_bottom',NULL,'Administrator'),
('AEC_S','roi_width',0,'r_roi_width',NULL,'Administrator'),
('AEC_S','roi_height',0,'r_roi_height',NULL,'Administrator'),
('AEC_S','sclh',0,'r_sclh',NULL,'Administrator'),
('AEC_S','sclv',0,'r_sclv',NULL,'Administrator'),
('AEC_S','roi_blk_w',0,'r_roi_blk_w[0]',NULL,'Administrator'),
('AEC_S','roi_blk_w',1,'r_roi_blk_w[1]',NULL,'Administrator'),
('AEC_S','roi_blk_w',2,'r_roi_blk_w[2]',NULL,'Administrator'),
('AEC_S','roi_blk_w',3,'r_roi_blk_w[3]',NULL,'Administrator'),
('AEC_S','roi_blk_w',4,'r_roi_blk_w[4]',NULL,'Administrator'),
('AEC_S','roi_blk_w',5,'r_roi_blk_w[5]',NULL,'Administrator'),
('AEC_S','roi_blk_w',6,'r_roi_blk_w[6]',NULL,'Administrator'),
('AEC_S','roi_blk_w',7,'r_roi_blk_w[7]',NULL,'Administrator'),
('AEC_S','roi_blk_w',8,'r_roi_blk_w[8]',NULL,'Administrator'),
('AEC_S','roi_blk_w',9,'r_roi_blk_w[9]',NULL,'Administrator'),
('AEC_S','roi_blk_w',10,'r_roi_blk_w[10]',NULL,'Administrator'),
('AEC_S','roi_blk_w',11,'r_roi_blk_w[11]',NULL,'Administrator'),
('AEC_S','roi_blk_w',12,'r_roi_blk_w[12]',NULL,'Administrator'),
('AEC_S','roi_blk_w',13,'r_roi_blk_w[13]',NULL,'Administrator'),
('AEC_S','roi_blk_w',14,'r_roi_blk_w[14]',NULL,'Administrator'),
('AEC_S','roi_blk_w',15,'r_roi_blk_w[15]',NULL,'Administrator'),
('AEC_S','roi_blk_w',16,'r_roi_blk_w[16]',NULL,'Administrator'),
('AEC_S','roi_blk_w',17,'r_roi_blk_w[17]',NULL,'Administrator'),
('AEC_S','roi_blk_w',18,'r_roi_blk_w[18]',NULL,'Administrator'),
('AEC_S','roi_blk_w',19,'r_roi_blk_w[19]',NULL,'Administrator'),
('AEC_S','roi_blk_w',20,'r_roi_blk_w[20]',NULL,'Administrator'),
('AEC_S','roi_blk_w',21,'r_roi_blk_w[21]',NULL,'Administrator'),
('AEC_S','roi_blk_w',22,'r_roi_blk_w[22]',NULL,'Administrator'),
('AEC_S','roi_blk_w',23,'r_roi_blk_w[23]',NULL,'Administrator'),
('AEC_S','roi_blk_w',24,'r_roi_blk_w[24]',NULL,'Administrator'),
('AEC_S','roi_blk_w',25,'r_roi_blk_w[25]',NULL,'Administrator'),
('AEC_S','roi_blk_w',26,'r_roi_blk_w[26]',NULL,'Administrator'),
('AEC_S','roi_blk_w',27,'r_roi_blk_w[27]',NULL,'Administrator'),
('AEC_S','roi_blk_w',28,'r_roi_blk_w[28]',NULL,'Administrator'),
('AEC_S','roi_blk_w',29,'r_roi_blk_w[29]',NULL,'Administrator'),
('AEC_S','roi_blk_w',30,'r_roi_blk_w[30]',NULL,'Administrator'),
('AEC_S','roi_blk_w',31,'r_roi_blk_w[31]',NULL,'Administrator'),
('AEC_S','roi_blk_w',32,'r_roi_blk_w[32]',NULL,'Administrator'),
('AEC_S','roi_blk_w',33,'r_roi_blk_w[33]',NULL,'Administrator'),
('AEC_S','roi_blk_w',34,'r_roi_blk_w[34]',NULL,'Administrator'),
('AEC_S','roi_blk_w',35,'r_roi_blk_w[35]',NULL,'Administrator'),
('AEC_S','roi_blk_w',36,'r_roi_blk_w[36]',NULL,'Administrator'),
('AEC_S','roi_blk_w',37,'r_roi_blk_w[37]',NULL,'Administrator'),
('AEC_S','roi_blk_w',38,'r_roi_blk_w[38]',NULL,'Administrator'),
('AEC_S','roi_blk_w',39,'r_roi_blk_w[39]',NULL,'Administrator'),
('AEC_S','roi_blk_w',40,'r_roi_blk_w[40]',NULL,'Administrator'),
('AEC_S','roi_blk_w',41,'r_roi_blk_w[41]',NULL,'Administrator'),
('AEC_S','roi_blk_w',42,'r_roi_blk_w[42]',NULL,'Administrator'),
('AEC_S','roi_blk_w',43,'r_roi_blk_w[43]',NULL,'Administrator'),
('AEC_S','roi_blk_w',44,'r_roi_blk_w[44]',NULL,'Administrator'),
('AEC_S','roi_blk_w',45,'r_roi_blk_w[45]',NULL,'Administrator'),
('AEC_S','roi_blk_w',46,'r_roi_blk_w[46]',NULL,'Administrator'),
('AEC_S','roi_blk_w',47,'r_roi_blk_w[47]',NULL,'Administrator'),
('AEC_S','roi_blk_w',48,'r_roi_blk_w[48]',NULL,'Administrator'),
('AEC_S','roi_blk_w',49,'r_roi_blk_w[49]',NULL,'Administrator'),
('AEC_S','roi_blk_w',50,'r_roi_blk_w[50]',NULL,'Administrator'),
('AEC_S','roi_blk_w',51,'r_roi_blk_w[51]',NULL,'Administrator'),
('AEC_S','roi_blk_w',52,'r_roi_blk_w[52]',NULL,'Administrator'),
('AEC_S','roi_blk_w',53,'r_roi_blk_w[53]',NULL,'Administrator'),
('AEC_S','roi_blk_w',54,'r_roi_blk_w[54]',NULL,'Administrator'),
('AEC_S','roi_blk_w',55,'r_roi_blk_w[55]',NULL,'Administrator'),
('AEC_S','roi_blk_w',56,'r_roi_blk_w[56]',NULL,'Administrator'),
('AEC_S','roi_blk_w',57,'r_roi_blk_w[57]',NULL,'Administrator'),
('AEC_S','roi_blk_w',58,'r_roi_blk_w[58]',NULL,'Administrator'),
('AEC_S','roi_blk_w',59,'r_roi_blk_w[59]',NULL,'Administrator'),
('AEC_S','roi_blk_w',60,'r_roi_blk_w[60]',NULL,'Administrator'),
('AEC_S','roi_blk_w',61,'r_roi_blk_w[61]',NULL,'Administrator'),
('AEC_S','roi_blk_w',62,'r_roi_blk_w[62]',NULL,'Administrator'),
('AEC_S','roi_blk_w',63,'r_roi_blk_w[63]',NULL,'Administrator'),
('AEC_S','roi_blk_w',64,'r_roi_blk_w[64]',NULL,'Administrator'),
('AEC_S','roi_blk_w',65,'r_roi_blk_w[65]',NULL,'Administrator'),
('AEC_S','roi_blk_w',66,'r_roi_blk_w[66]',NULL,'Administrator'),
('AEC_S','roi_blk_w',67,'r_roi_blk_w[67]',NULL,'Administrator'),
('AEC_S','roi_blk_w',68,'r_roi_blk_w[68]',NULL,'Administrator'),
('AEC_S','roi_blk_w',69,'r_roi_blk_w[69]',NULL,'Administrator'),
('AEC_S','roi_blk_w',70,'r_roi_blk_w[70]',NULL,'Administrator'),
('AEC_S','roi_blk_w',71,'r_roi_blk_w[71]',NULL,'Administrator'),
('AEC_S','roi_blk_w',72,'r_roi_blk_w[72]',NULL,'Administrator'),
('AEC_S','roi_blk_w',73,'r_roi_blk_w[73]',NULL,'Administrator'),
('AEC_S','roi_blk_w',74,'r_roi_blk_w[74]',NULL,'Administrator'),
('AEC_S','roi_blk_w',75,'r_roi_blk_w[75]',NULL,'Administrator'),
('AEC_S','roi_blk_w',76,'r_roi_blk_w[76]',NULL,'Administrator'),
('AEC_S','roi_blk_w',77,'r_roi_blk_w[77]',NULL,'Administrator'),
('AEC_S','roi_blk_w',78,'r_roi_blk_w[78]',NULL,'Administrator'),
('AEC_S','roi_blk_w',79,'r_roi_blk_w[79]',NULL,'Administrator'),
('AEC_S','roi_blk_w',80,'r_roi_blk_w[80]',NULL,'Administrator'),
('AEC_S','roi_blk_w',81,'r_roi_blk_w[81]',NULL,'Administrator'),
('AEC_S','roi_blk_w',82,'r_roi_blk_w[82]',NULL,'Administrator'),
('AEC_S','roi_blk_w',83,'r_roi_blk_w[83]',NULL,'Administrator'),
('AEC_S','roi_blk_w',84,'r_roi_blk_w[84]',NULL,'Administrator'),
('AEC_S','roi_blk_w',85,'r_roi_blk_w[85]',NULL,'Administrator'),
('AEC_S','roi_blk_w',86,'r_roi_blk_w[86]',NULL,'Administrator'),
('AEC_S','roi_blk_w',87,'r_roi_blk_w[87]',NULL,'Administrator'),
('AEC_S','roi_blk_w',88,'r_roi_blk_w[88]',NULL,'Administrator'),
('AEC_S','roi_blk_w',89,'r_roi_blk_w[89]',NULL,'Administrator'),
('AEC_S','roi_blk_w',90,'r_roi_blk_w[90]',NULL,'Administrator'),
('AEC_S','roi_blk_w',91,'r_roi_blk_w[91]',NULL,'Administrator'),
('AEC_S','roi_blk_w',92,'r_roi_blk_w[92]',NULL,'Administrator'),
('AEC_S','roi_blk_w',93,'r_roi_blk_w[93]',NULL,'Administrator'),
('AEC_S','roi_blk_w',94,'r_roi_blk_w[94]',NULL,'Administrator'),
('AEC_S','roi_blk_w',95,'r_roi_blk_w[95]',NULL,'Administrator'),
('AEC_S','roi_blk_w',96,'r_roi_blk_w[96]',NULL,'Administrator'),
('AEC_S','roi_blk_w',97,'r_roi_blk_w[97]',NULL,'Administrator'),
('AEC_S','roi_blk_w',98,'r_roi_blk_w[98]',NULL,'Administrator'),
('AEC_S','roi_blk_w',99,'r_roi_blk_w[99]',NULL,'Administrator'),
('AEC_S','roi_blk_w',100,'r_roi_blk_w[100]',NULL,'Administrator'),
('AEC_S','roi_blk_w',101,'r_roi_blk_w[101]',NULL,'Administrator'),
('AEC_S','roi_blk_w',102,'r_roi_blk_w[102]',NULL,'Administrator'),
('AEC_S','roi_blk_w',103,'r_roi_blk_w[103]',NULL,'Administrator'),
('AEC_S','roi_blk_w',104,'r_roi_blk_w[104]',NULL,'Administrator'),
('AEC_S','roi_blk_w',105,'r_roi_blk_w[105]',NULL,'Administrator'),
('AEC_S','roi_blk_w',106,'r_roi_blk_w[106]',NULL,'Administrator'),
('AEC_S','roi_blk_w',107,'r_roi_blk_w[107]',NULL,'Administrator'),
('AEC_S','roi_blk_w',108,'r_roi_blk_w[108]',NULL,'Administrator'),
('AEC_S','roi_blk_w',109,'r_roi_blk_w[109]',NULL,'Administrator'),
('AEC_S','roi_blk_w',110,'r_roi_blk_w[110]',NULL,'Administrator'),
('AEC_S','roi_blk_w',111,'r_roi_blk_w[111]',NULL,'Administrator'),
('AEC_S','roi_blk_w',112,'r_roi_blk_w[112]',NULL,'Administrator'),
('AEC_S','roi_blk_w',113,'r_roi_blk_w[113]',NULL,'Administrator'),
('AEC_S','roi_blk_w',114,'r_roi_blk_w[114]',NULL,'Administrator'),
('AEC_S','roi_blk_w',115,'r_roi_blk_w[115]',NULL,'Administrator'),
('AEC_S','roi_blk_w',116,'r_roi_blk_w[116]',NULL,'Administrator'),
('AEC_S','roi_blk_w',117,'r_roi_blk_w[117]',NULL,'Administrator'),
('AEC_S','roi_blk_w',118,'r_roi_blk_w[118]',NULL,'Administrator'),
('AEC_S','roi_blk_w',119,'r_roi_blk_w[119]',NULL,'Administrator'),
('AEC_S','roi_blk_w',120,'r_roi_blk_w[120]',NULL,'Administrator'),
('AEC_S','roi_blk_w',121,'r_roi_blk_w[121]',NULL,'Administrator'),
('AEC_S','roi_blk_w',122,'r_roi_blk_w[122]',NULL,'Administrator'),
('AEC_S','roi_blk_w',123,'r_roi_blk_w[123]',NULL,'Administrator'),
('AEC_S','roi_blk_w',124,'r_roi_blk_w[124]',NULL,'Administrator'),
('AEC_S','roi_blk_w',125,'r_roi_blk_w[125]',NULL,'Administrator'),
('AEC_S','roi_blk_w',126,'r_roi_blk_w[126]',NULL,'Administrator'),
('AEC_S','roi_blk_w',127,'r_roi_blk_w[127]',NULL,'Administrator'),
('AEC_S','roi_blk_w',128,'r_roi_blk_w[128]',NULL,'Administrator'),
('AEC_S','roi_blk_w',129,'r_roi_blk_w[129]',NULL,'Administrator'),
('AEC_S','roi_blk_w',130,'r_roi_blk_w[130]',NULL,'Administrator'),
('AEC_S','roi_blk_w',131,'r_roi_blk_w[131]',NULL,'Administrator'),
('AEC_S','roi_blk_w',132,'r_roi_blk_w[132]',NULL,'Administrator'),
('AEC_S','roi_blk_w',133,'r_roi_blk_w[133]',NULL,'Administrator'),
('AEC_S','roi_blk_w',134,'r_roi_blk_w[134]',NULL,'Administrator'),
('AEC_S','roi_blk_w',135,'r_roi_blk_w[135]',NULL,'Administrator'),
('AEC_S','roi_blk_w',136,'r_roi_blk_w[136]',NULL,'Administrator'),
('AEC_S','roi_blk_w',137,'r_roi_blk_w[137]',NULL,'Administrator'),
('AEC_S','roi_blk_w',138,'r_roi_blk_w[138]',NULL,'Administrator'),
('AEC_S','roi_blk_w',139,'r_roi_blk_w[139]',NULL,'Administrator'),
('AEC_S','roi_blk_w',140,'r_roi_blk_w[140]',NULL,'Administrator'),
('AEC_S','roi_blk_w',141,'r_roi_blk_w[141]',NULL,'Administrator'),
('AEC_S','roi_blk_w',142,'r_roi_blk_w[142]',NULL,'Administrator'),
('AEC_S','roi_blk_w',143,'r_roi_blk_w[143]',NULL,'Administrator'),
('AEC_S','roi_blk_w',144,'r_roi_blk_w[144]',NULL,'Administrator'),
('AEC_S','roi_blk_w',145,'r_roi_blk_w[145]',NULL,'Administrator'),
('AEC_S','roi_blk_w',146,'r_roi_blk_w[146]',NULL,'Administrator'),
('AEC_S','roi_blk_w',147,'r_roi_blk_w[147]',NULL,'Administrator'),
('AEC_S','roi_blk_w',148,'r_roi_blk_w[148]',NULL,'Administrator'),
('AEC_S','roi_blk_w',149,'r_roi_blk_w[149]',NULL,'Administrator'),
('AEC_S','roi_blk_w',150,'r_roi_blk_w[150]',NULL,'Administrator'),
('AEC_S','roi_blk_w',151,'r_roi_blk_w[151]',NULL,'Administrator'),
('AEC_S','roi_blk_w',152,'r_roi_blk_w[152]',NULL,'Administrator'),
('AEC_S','roi_blk_w',153,'r_roi_blk_w[153]',NULL,'Administrator'),
('AEC_S','roi_blk_w',154,'r_roi_blk_w[154]',NULL,'Administrator'),
('AEC_S','roi_blk_w',155,'r_roi_blk_w[155]',NULL,'Administrator'),
('AEC_S','roi_blk_w',156,'r_roi_blk_w[156]',NULL,'Administrator'),
('AEC_S','roi_blk_w',157,'r_roi_blk_w[157]',NULL,'Administrator'),
('AEC_S','roi_blk_w',158,'r_roi_blk_w[158]',NULL,'Administrator'),
('AEC_S','roi_blk_w',159,'r_roi_blk_w[159]',NULL,'Administrator'),
('AEC_S','roi_blk_w',160,'r_roi_blk_w[160]',NULL,'Administrator'),
('AEC_S','roi_blk_w',161,'r_roi_blk_w[161]',NULL,'Administrator'),
('AEC_S','roi_blk_w',162,'r_roi_blk_w[162]',NULL,'Administrator'),
('AEC_S','roi_blk_w',163,'r_roi_blk_w[163]',NULL,'Administrator'),
('AEC_S','roi_blk_w',164,'r_roi_blk_w[164]',NULL,'Administrator'),
('AEC_S','roi_blk_w',165,'r_roi_blk_w[165]',NULL,'Administrator'),
('AEC_S','roi_blk_w',166,'r_roi_blk_w[166]',NULL,'Administrator'),
('AEC_S','roi_blk_w',167,'r_roi_blk_w[167]',NULL,'Administrator'),
('AEC_S','roi_blk_w',168,'r_roi_blk_w[168]',NULL,'Administrator'),
('AEC_S','roi_blk_w',169,'r_roi_blk_w[169]',NULL,'Administrator'),
('AEC_S','roi_blk_w',170,'r_roi_blk_w[170]',NULL,'Administrator'),
('AEC_S','roi_blk_w',171,'r_roi_blk_w[171]',NULL,'Administrator'),
('AEC_S','roi_blk_w',172,'r_roi_blk_w[172]',NULL,'Administrator'),
('AEC_S','roi_blk_w',173,'r_roi_blk_w[173]',NULL,'Administrator'),
('AEC_S','roi_blk_w',174,'r_roi_blk_w[174]',NULL,'Administrator'),
('AEC_S','roi_blk_w',175,'r_roi_blk_w[175]',NULL,'Administrator'),
('AEC_S','roi_blk_w',176,'r_roi_blk_w[176]',NULL,'Administrator'),
('AEC_S','roi_blk_w',177,'r_roi_blk_w[177]',NULL,'Administrator'),
('AEC_S','roi_blk_w',178,'r_roi_blk_w[178]',NULL,'Administrator'),
('AEC_S','roi_blk_w',179,'r_roi_blk_w[179]',NULL,'Administrator'),
('AEC_S','roi_blk_w',180,'r_roi_blk_w[180]',NULL,'Administrator'),
('AEC_S','roi_blk_w',181,'r_roi_blk_w[181]',NULL,'Administrator'),
('AEC_S','roi_blk_w',182,'r_roi_blk_w[182]',NULL,'Administrator'),
('AEC_S','roi_blk_w',183,'r_roi_blk_w[183]',NULL,'Administrator'),
('AEC_S','roi_blk_w',184,'r_roi_blk_w[184]',NULL,'Administrator'),
('AEC_S','roi_blk_w',185,'r_roi_blk_w[185]',NULL,'Administrator'),
('AEC_S','roi_blk_w',186,'r_roi_blk_w[186]',NULL,'Administrator'),
('AEC_S','roi_blk_w',187,'r_roi_blk_w[187]',NULL,'Administrator'),
('AEC_S','roi_blk_w',188,'r_roi_blk_w[188]',NULL,'Administrator'),
('AEC_S','roi_blk_w',189,'r_roi_blk_w[189]',NULL,'Administrator'),
('AEC_S','roi_blk_w',190,'r_roi_blk_w[190]',NULL,'Administrator'),
('AEC_S','roi_blk_w',191,'r_roi_blk_w[191]',NULL,'Administrator'),
('AEC_V','roi_weight_en',0,'r_roi_weight_en',NULL,'Administrator'),
('AEC_V','Left',0,'r_left',NULL,'Administrator'),
('AEC_V','Top',0,'r_top',NULL,'Administrator'),
('AEC_V','Right',0,'r_right',NULL,'Administrator'),
('AEC_V','Bottom',0,'r_bottom',NULL,'Administrator'),
('AEC_V','roi_width',0,'r_roi_width',NULL,'Administrator'),
('AEC_V','roi_height',0,'r_roi_height',NULL,'Administrator'),
('AEC_V','sclh',0,'r_sclh',NULL,'Administrator'),
('AEC_V','sclv',0,'r_sclv',NULL,'Administrator'),
('AEC_V','roi_blk_w',0,'r_roi_blk_w[0]',NULL,'Administrator'),
('AEC_V','roi_blk_w',1,'r_roi_blk_w[1]',NULL,'Administrator'),
('AEC_V','roi_blk_w',2,'r_roi_blk_w[2]',NULL,'Administrator'),
('AEC_V','roi_blk_w',3,'r_roi_blk_w[3]',NULL,'Administrator'),
('AEC_V','roi_blk_w',4,'r_roi_blk_w[4]',NULL,'Administrator'),
('AEC_V','roi_blk_w',5,'r_roi_blk_w[5]',NULL,'Administrator'),
('AEC_V','roi_blk_w',6,'r_roi_blk_w[6]',NULL,'Administrator'),
('AEC_V','roi_blk_w',7,'r_roi_blk_w[7]',NULL,'Administrator'),
('AEC_V','roi_blk_w',8,'r_roi_blk_w[8]',NULL,'Administrator'),
('AEC_V','roi_blk_w',9,'r_roi_blk_w[9]',NULL,'Administrator'),
('AEC_V','roi_blk_w',10,'r_roi_blk_w[10]',NULL,'Administrator'),
('AEC_V','roi_blk_w',11,'r_roi_blk_w[11]',NULL,'Administrator'),
('AEC_V','roi_blk_w',12,'r_roi_blk_w[12]',NULL,'Administrator'),
('AEC_V','roi_blk_w',13,'r_roi_blk_w[13]',NULL,'Administrator'),
('AEC_V','roi_blk_w',14,'r_roi_blk_w[14]',NULL,'Administrator'),
('AEC_V','roi_blk_w',15,'r_roi_blk_w[15]',NULL,'Administrator'),
('AEC_V','roi_blk_w',16,'r_roi_blk_w[16]',NULL,'Administrator'),
('AEC_V','roi_blk_w',17,'r_roi_blk_w[17]',NULL,'Administrator'),
('AEC_V','roi_blk_w',18,'r_roi_blk_w[18]',NULL,'Administrator'),
('AEC_V','roi_blk_w',19,'r_roi_blk_w[19]',NULL,'Administrator'),
('AEC_V','roi_blk_w',20,'r_roi_blk_w[20]',NULL,'Administrator'),
('AEC_V','roi_blk_w',21,'r_roi_blk_w[21]',NULL,'Administrator'),
('AEC_V','roi_blk_w',22,'r_roi_blk_w[22]',NULL,'Administrator'),
('AEC_V','roi_blk_w',23,'r_roi_blk_w[23]',NULL,'Administrator'),
('AEC_V','roi_blk_w',24,'r_roi_blk_w[24]',NULL,'Administrator'),
('AEC_V','roi_blk_w',25,'r_roi_blk_w[25]',NULL,'Administrator'),
('AEC_V','roi_blk_w',26,'r_roi_blk_w[26]',NULL,'Administrator'),
('AEC_V','roi_blk_w',27,'r_roi_blk_w[27]',NULL,'Administrator'),
('AEC_V','roi_blk_w',28,'r_roi_blk_w[28]',NULL,'Administrator'),
('AEC_V','roi_blk_w',29,'r_roi_blk_w[29]',NULL,'Administrator'),
('AEC_V','roi_blk_w',30,'r_roi_blk_w[30]',NULL,'Administrator'),
('AEC_V','roi_blk_w',31,'r_roi_blk_w[31]',NULL,'Administrator'),
('AEC_V','roi_blk_w',32,'r_roi_blk_w[32]',NULL,'Administrator'),
('AEC_V','roi_blk_w',33,'r_roi_blk_w[33]',NULL,'Administrator'),
('AEC_V','roi_blk_w',34,'r_roi_blk_w[34]',NULL,'Administrator'),
('AEC_V','roi_blk_w',35,'r_roi_blk_w[35]',NULL,'Administrator'),
('AEC_V','roi_blk_w',36,'r_roi_blk_w[36]',NULL,'Administrator'),
('AEC_V','roi_blk_w',37,'r_roi_blk_w[37]',NULL,'Administrator'),
('AEC_V','roi_blk_w',38,'r_roi_blk_w[38]',NULL,'Administrator'),
('AEC_V','roi_blk_w',39,'r_roi_blk_w[39]',NULL,'Administrator'),
('AEC_V','roi_blk_w',40,'r_roi_blk_w[40]',NULL,'Administrator'),
('AEC_V','roi_blk_w',41,'r_roi_blk_w[41]',NULL,'Administrator'),
('AEC_V','roi_blk_w',42,'r_roi_blk_w[42]',NULL,'Administrator'),
('AEC_V','roi_blk_w',43,'r_roi_blk_w[43]',NULL,'Administrator'),
('AEC_V','roi_blk_w',44,'r_roi_blk_w[44]',NULL,'Administrator'),
('AEC_V','roi_blk_w',45,'r_roi_blk_w[45]',NULL,'Administrator'),
('AEC_V','roi_blk_w',46,'r_roi_blk_w[46]',NULL,'Administrator'),
('AEC_V','roi_blk_w',47,'r_roi_blk_w[47]',NULL,'Administrator'),
('AEC_V','roi_blk_w',48,'r_roi_blk_w[48]',NULL,'Administrator'),
('AEC_V','roi_blk_w',49,'r_roi_blk_w[49]',NULL,'Administrator'),
('AEC_V','roi_blk_w',50,'r_roi_blk_w[50]',NULL,'Administrator'),
('AEC_V','roi_blk_w',51,'r_roi_blk_w[51]',NULL,'Administrator'),
('AEC_V','roi_blk_w',52,'r_roi_blk_w[52]',NULL,'Administrator'),
('AEC_V','roi_blk_w',53,'r_roi_blk_w[53]',NULL,'Administrator'),
('AEC_V','roi_blk_w',54,'r_roi_blk_w[54]',NULL,'Administrator'),
('AEC_V','roi_blk_w',55,'r_roi_blk_w[55]',NULL,'Administrator'),
('AEC_V','roi_blk_w',56,'r_roi_blk_w[56]',NULL,'Administrator'),
('AEC_V','roi_blk_w',57,'r_roi_blk_w[57]',NULL,'Administrator'),
('AEC_V','roi_blk_w',58,'r_roi_blk_w[58]',NULL,'Administrator'),
('AEC_V','roi_blk_w',59,'r_roi_blk_w[59]',NULL,'Administrator'),
('AEC_V','roi_blk_w',60,'r_roi_blk_w[60]',NULL,'Administrator'),
('AEC_V','roi_blk_w',61,'r_roi_blk_w[61]',NULL,'Administrator'),
('AEC_V','roi_blk_w',62,'r_roi_blk_w[62]',NULL,'Administrator'),
('AEC_V','roi_blk_w',63,'r_roi_blk_w[63]',NULL,'Administrator'),
('AEC_V','roi_blk_w',64,'r_roi_blk_w[64]',NULL,'Administrator'),
('AEC_V','roi_blk_w',65,'r_roi_blk_w[65]',NULL,'Administrator'),
('AEC_V','roi_blk_w',66,'r_roi_blk_w[66]',NULL,'Administrator'),
('AEC_V','roi_blk_w',67,'r_roi_blk_w[67]',NULL,'Administrator'),
('AEC_V','roi_blk_w',68,'r_roi_blk_w[68]',NULL,'Administrator'),
('AEC_V','roi_blk_w',69,'r_roi_blk_w[69]',NULL,'Administrator'),
('AEC_V','roi_blk_w',70,'r_roi_blk_w[70]',NULL,'Administrator'),
('AEC_V','roi_blk_w',71,'r_roi_blk_w[71]',NULL,'Administrator'),
('AEC_V','roi_blk_w',72,'r_roi_blk_w[72]',NULL,'Administrator'),
('AEC_V','roi_blk_w',73,'r_roi_blk_w[73]',NULL,'Administrator'),
('AEC_V','roi_blk_w',74,'r_roi_blk_w[74]',NULL,'Administrator'),
('AEC_V','roi_blk_w',75,'r_roi_blk_w[75]',NULL,'Administrator'),
('AEC_V','roi_blk_w',76,'r_roi_blk_w[76]',NULL,'Administrator'),
('AEC_V','roi_blk_w',77,'r_roi_blk_w[77]',NULL,'Administrator'),
('AEC_V','roi_blk_w',78,'r_roi_blk_w[78]',NULL,'Administrator'),
('AEC_V','roi_blk_w',79,'r_roi_blk_w[79]',NULL,'Administrator'),
('AEC_V','roi_blk_w',80,'r_roi_blk_w[80]',NULL,'Administrator'),
('AEC_V','roi_blk_w',81,'r_roi_blk_w[81]',NULL,'Administrator'),
('AEC_V','roi_blk_w',82,'r_roi_blk_w[82]',NULL,'Administrator'),
('AEC_V','roi_blk_w',83,'r_roi_blk_w[83]',NULL,'Administrator'),
('AEC_V','roi_blk_w',84,'r_roi_blk_w[84]',NULL,'Administrator'),
('AEC_V','roi_blk_w',85,'r_roi_blk_w[85]',NULL,'Administrator'),
('AEC_V','roi_blk_w',86,'r_roi_blk_w[86]',NULL,'Administrator'),
('AEC_V','roi_blk_w',87,'r_roi_blk_w[87]',NULL,'Administrator'),
('AEC_V','roi_blk_w',88,'r_roi_blk_w[88]',NULL,'Administrator'),
('AEC_V','roi_blk_w',89,'r_roi_blk_w[89]',NULL,'Administrator'),
('AEC_V','roi_blk_w',90,'r_roi_blk_w[90]',NULL,'Administrator'),
('AEC_V','roi_blk_w',91,'r_roi_blk_w[91]',NULL,'Administrator'),
('AEC_V','roi_blk_w',92,'r_roi_blk_w[92]',NULL,'Administrator'),
('AEC_V','roi_blk_w',93,'r_roi_blk_w[93]',NULL,'Administrator'),
('AEC_V','roi_blk_w',94,'r_roi_blk_w[94]',NULL,'Administrator'),
('AEC_V','roi_blk_w',95,'r_roi_blk_w[95]',NULL,'Administrator'),
('AEC_V','roi_blk_w',96,'r_roi_blk_w[96]',NULL,'Administrator'),
('AEC_V','roi_blk_w',97,'r_roi_blk_w[97]',NULL,'Administrator'),
('AEC_V','roi_blk_w',98,'r_roi_blk_w[98]',NULL,'Administrator'),
('AEC_V','roi_blk_w',99,'r_roi_blk_w[99]',NULL,'Administrator'),
('AEC_V','roi_blk_w',100,'r_roi_blk_w[100]',NULL,'Administrator'),
('AEC_V','roi_blk_w',101,'r_roi_blk_w[101]',NULL,'Administrator'),
('AEC_V','roi_blk_w',102,'r_roi_blk_w[102]',NULL,'Administrator'),
('AEC_V','roi_blk_w',103,'r_roi_blk_w[103]',NULL,'Administrator'),
('AEC_V','roi_blk_w',104,'r_roi_blk_w[104]',NULL,'Administrator'),
('AEC_V','roi_blk_w',105,'r_roi_blk_w[105]',NULL,'Administrator'),
('AEC_V','roi_blk_w',106,'r_roi_blk_w[106]',NULL,'Administrator'),
('AEC_V','roi_blk_w',107,'r_roi_blk_w[107]',NULL,'Administrator'),
('AEC_V','roi_blk_w',108,'r_roi_blk_w[108]',NULL,'Administrator'),
('AEC_V','roi_blk_w',109,'r_roi_blk_w[109]',NULL,'Administrator'),
('AEC_V','roi_blk_w',110,'r_roi_blk_w[110]',NULL,'Administrator'),
('AEC_V','roi_blk_w',111,'r_roi_blk_w[111]',NULL,'Administrator'),
('AEC_V','roi_blk_w',112,'r_roi_blk_w[112]',NULL,'Administrator'),
('AEC_V','roi_blk_w',113,'r_roi_blk_w[113]',NULL,'Administrator'),
('AEC_V','roi_blk_w',114,'r_roi_blk_w[114]',NULL,'Administrator'),
('AEC_V','roi_blk_w',115,'r_roi_blk_w[115]',NULL,'Administrator'),
('AEC_V','roi_blk_w',116,'r_roi_blk_w[116]',NULL,'Administrator'),
('AEC_V','roi_blk_w',117,'r_roi_blk_w[117]',NULL,'Administrator'),
('AEC_V','roi_blk_w',118,'r_roi_blk_w[118]',NULL,'Administrator'),
('AEC_V','roi_blk_w',119,'r_roi_blk_w[119]',NULL,'Administrator'),
('AEC_V','roi_blk_w',120,'r_roi_blk_w[120]',NULL,'Administrator'),
('AEC_V','roi_blk_w',121,'r_roi_blk_w[121]',NULL,'Administrator'),
('AEC_V','roi_blk_w',122,'r_roi_blk_w[122]',NULL,'Administrator'),
('AEC_V','roi_blk_w',123,'r_roi_blk_w[123]',NULL,'Administrator'),
('AEC_V','roi_blk_w',124,'r_roi_blk_w[124]',NULL,'Administrator'),
('AEC_V','roi_blk_w',125,'r_roi_blk_w[125]',NULL,'Administrator'),
('AEC_V','roi_blk_w',126,'r_roi_blk_w[126]',NULL,'Administrator'),
('AEC_V','roi_blk_w',127,'r_roi_blk_w[127]',NULL,'Administrator'),
('AEC_V','roi_blk_w',128,'r_roi_blk_w[128]',NULL,'Administrator'),
('AEC_V','roi_blk_w',129,'r_roi_blk_w[129]',NULL,'Administrator'),
('AEC_V','roi_blk_w',130,'r_roi_blk_w[130]',NULL,'Administrator'),
('AEC_V','roi_blk_w',131,'r_roi_blk_w[131]',NULL,'Administrator'),
('AEC_V','roi_blk_w',132,'r_roi_blk_w[132]',NULL,'Administrator'),
('AEC_V','roi_blk_w',133,'r_roi_blk_w[133]',NULL,'Administrator'),
('AEC_V','roi_blk_w',134,'r_roi_blk_w[134]',NULL,'Administrator'),
('AEC_V','roi_blk_w',135,'r_roi_blk_w[135]',NULL,'Administrator'),
('AEC_V','roi_blk_w',136,'r_roi_blk_w[136]',NULL,'Administrator'),
('AEC_V','roi_blk_w',137,'r_roi_blk_w[137]',NULL,'Administrator'),
('AEC_V','roi_blk_w',138,'r_roi_blk_w[138]',NULL,'Administrator'),
('AEC_V','roi_blk_w',139,'r_roi_blk_w[139]',NULL,'Administrator'),
('AEC_V','roi_blk_w',140,'r_roi_blk_w[140]',NULL,'Administrator'),
('AEC_V','roi_blk_w',141,'r_roi_blk_w[141]',NULL,'Administrator'),
('AEC_V','roi_blk_w',142,'r_roi_blk_w[142]',NULL,'Administrator'),
('AEC_V','roi_blk_w',143,'r_roi_blk_w[143]',NULL,'Administrator'),
('AEC_V','roi_blk_w',144,'r_roi_blk_w[144]',NULL,'Administrator'),
('AEC_V','roi_blk_w',145,'r_roi_blk_w[145]',NULL,'Administrator'),
('AEC_V','roi_blk_w',146,'r_roi_blk_w[146]',NULL,'Administrator'),
('AEC_V','roi_blk_w',147,'r_roi_blk_w[147]',NULL,'Administrator'),
('AEC_V','roi_blk_w',148,'r_roi_blk_w[148]',NULL,'Administrator'),
('AEC_V','roi_blk_w',149,'r_roi_blk_w[149]',NULL,'Administrator'),
('AEC_V','roi_blk_w',150,'r_roi_blk_w[150]',NULL,'Administrator'),
('AEC_V','roi_blk_w',151,'r_roi_blk_w[151]',NULL,'Administrator'),
('AEC_V','roi_blk_w',152,'r_roi_blk_w[152]',NULL,'Administrator'),
('AEC_V','roi_blk_w',153,'r_roi_blk_w[153]',NULL,'Administrator'),
('AEC_V','roi_blk_w',154,'r_roi_blk_w[154]',NULL,'Administrator'),
('AEC_V','roi_blk_w',155,'r_roi_blk_w[155]',NULL,'Administrator'),
('AEC_V','roi_blk_w',156,'r_roi_blk_w[156]',NULL,'Administrator'),
('AEC_V','roi_blk_w',157,'r_roi_blk_w[157]',NULL,'Administrator'),
('AEC_V','roi_blk_w',158,'r_roi_blk_w[158]',NULL,'Administrator'),
('AEC_V','roi_blk_w',159,'r_roi_blk_w[159]',NULL,'Administrator'),
('AEC_V','roi_blk_w',160,'r_roi_blk_w[160]',NULL,'Administrator'),
('AEC_V','roi_blk_w',161,'r_roi_blk_w[161]',NULL,'Administrator'),
('AEC_V','roi_blk_w',162,'r_roi_blk_w[162]',NULL,'Administrator'),
('AEC_V','roi_blk_w',163,'r_roi_blk_w[163]',NULL,'Administrator'),
('AEC_V','roi_blk_w',164,'r_roi_blk_w[164]',NULL,'Administrator'),
('AEC_V','roi_blk_w',165,'r_roi_blk_w[165]',NULL,'Administrator'),
('AEC_V','roi_blk_w',166,'r_roi_blk_w[166]',NULL,'Administrator'),
('AEC_V','roi_blk_w',167,'r_roi_blk_w[167]',NULL,'Administrator'),
('AEC_V','roi_blk_w',168,'r_roi_blk_w[168]',NULL,'Administrator'),
('AEC_V','roi_blk_w',169,'r_roi_blk_w[169]',NULL,'Administrator'),
('AEC_V','roi_blk_w',170,'r_roi_blk_w[170]',NULL,'Administrator'),
('AEC_V','roi_blk_w',171,'r_roi_blk_w[171]',NULL,'Administrator'),
('AEC_V','roi_blk_w',172,'r_roi_blk_w[172]',NULL,'Administrator'),
('AEC_V','roi_blk_w',173,'r_roi_blk_w[173]',NULL,'Administrator'),
('AEC_V','roi_blk_w',174,'r_roi_blk_w[174]',NULL,'Administrator'),
('AEC_V','roi_blk_w',175,'r_roi_blk_w[175]',NULL,'Administrator'),
('AEC_V','roi_blk_w',176,'r_roi_blk_w[176]',NULL,'Administrator'),
('AEC_V','roi_blk_w',177,'r_roi_blk_w[177]',NULL,'Administrator'),
('AEC_V','roi_blk_w',178,'r_roi_blk_w[178]',NULL,'Administrator'),
('AEC_V','roi_blk_w',179,'r_roi_blk_w[179]',NULL,'Administrator'),
('AEC_V','roi_blk_w',180,'r_roi_blk_w[180]',NULL,'Administrator'),
('AEC_V','roi_blk_w',181,'r_roi_blk_w[181]',NULL,'Administrator'),
('AEC_V','roi_blk_w',182,'r_roi_blk_w[182]',NULL,'Administrator'),
('AEC_V','roi_blk_w',183,'r_roi_blk_w[183]',NULL,'Administrator'),
('AEC_V','roi_blk_w',184,'r_roi_blk_w[184]',NULL,'Administrator'),
('AEC_V','roi_blk_w',185,'r_roi_blk_w[185]',NULL,'Administrator'),
('AEC_V','roi_blk_w',186,'r_roi_blk_w[186]',NULL,'Administrator'),
('AEC_V','roi_blk_w',187,'r_roi_blk_w[187]',NULL,'Administrator'),
('AEC_V','roi_blk_w',188,'r_roi_blk_w[188]',NULL,'Administrator'),
('AEC_V','roi_blk_w',189,'r_roi_blk_w[189]',NULL,'Administrator'),
('AEC_V','roi_blk_w',190,'r_roi_blk_w[190]',NULL,'Administrator'),
('AEC_V','roi_blk_w',191,'r_roi_blk_w[191]',NULL,'Administrator');



INSERT INTO ui_info_regmodule VALUES
('AEC','BandEnable L','AEC',1),
('AEC','BandEnable M','AEC',1),
('AEC','OneBandLim L','AEC',1),
('AEC','OneBandLim M','AEC',1),
('AEC','Enable','AEC',1),
('AEC','ExpoLimNode','AEC',1),
('AEC','GainLimNode','AEC',1),
('AEC','TargetL 0','AEC',1),
('AEC','TargetL 0 IR_AB','AEC_IR_AB',1),
('AEC','TargetL 0 RGB_AB','AEC_RGB_AB',1),
('AEC','TargetL 1','AEC',1),
('AEC','TargetL 1 IR_AB','AEC_IR_AB',1),
('AEC','TargetL 1 RGB_AB','AEC_RGB_AB',1),
('AEC','TargetL 2','AEC',1),
('AEC','TargetL 2 IR_AB','AEC_IR_AB',1),
('AEC','TargetL 2 RGB_AB','AEC_RGB_AB',1),
('AEC','TargetL 3','AEC',1),
('AEC','TargetL 3 IR_AB','AEC_IR_AB',1),
('AEC','TargetL 3 RGB_AB','AEC_RGB_AB',1),
('AEC','TargetL 4','AEC',1),
('AEC','TargetL 4 IR_AB','AEC_IR_AB',1),
('AEC','TargetL 4 RGB_AB','AEC_RGB_AB',1),
('AEC','TargetL 5','AEC',1),
('AEC','TargetL 5 IR_AB','AEC_IR_AB',1),
('AEC','TargetL 5 RGB_AB','AEC_RGB_AB',1),
('AEC','TargetL 6','AEC',1),
('AEC','TargetL 6 IR_AB','AEC_IR_AB',1),
('AEC','TargetL 6 RGB_AB','AEC_RGB_AB',1),
('AEC','TargetL 7','AEC',1),
('AEC','TargetL 7 IR_AB','AEC_IR_AB',1),
('AEC','TargetL 7 RGB_AB','AEC_RGB_AB',1),
('AEC','Gain L','PipeCtrl',1),
('AEC','Gain M','PipeCtrl',1),
('AEC','Gain S','PipeCtrl',1),
('AEC','Gain LFS','PipeCtrl',1),
('AEC','Expo L','PipeCtrl',1),
('AEC','Expo M','PipeCtrl',1),
('AEC','Expo S','PipeCtrl',1),
('AEC','Expo LFS','PipeCtrl',1),
('AEC','EVThreL 0','AEC',1),
('AEC','EVThreL 0 IR_AB','AEC_IR_AB',1),
('AEC','EVThreL 0 RGB_AB','AEC_RGB_AB',1),
('AEC','EVThreL 1','AEC',1),
('AEC','EVThreL 1 IR_AB','AEC_IR_AB',1),
('AEC','EVThreL 1 RGB_AB','AEC_RGB_AB',1),
('AEC','EVThreL 2','AEC',1),
('AEC','EVThreL 2 IR_AB','AEC_IR_AB',1),
('AEC','EVThreL 2 RGB_AB','AEC_RGB_AB',1),
('AEC','EVThreL 3','AEC',1),
('AEC','EVThreL 3 IR_AB','AEC_IR_AB',1),
('AEC','EVThreL 3 RGB_AB','AEC_RGB_AB',1),
('AEC','EVThreL 4','AEC',1),
('AEC','EVThreL 4 IR_AB','AEC_IR_AB',1),
('AEC','EVThreL 4 RGB_AB','AEC_RGB_AB',1),
('AEC','EVThreL 5','AEC',1),
('AEC','EVThreL 5 IR_AB','AEC_IR_AB',1),
('AEC','EVThreL 5 RGB_AB','AEC_RGB_AB',1),
('AEC','EVThreL 6','AEC',1),
('AEC','EVThreL 6 IR_AB','AEC_IR_AB',1),
('AEC','EVThreL 6 RGB_AB','AEC_RGB_AB',1),
('AEC','EVThreL 7','AEC',1),
('AEC','EVThreL 7 IR_AB','AEC_IR_AB',1),
('AEC','EVThreL 7 RGB_AB','AEC_RGB_AB',1),
('AEC','TargetL M','AEC',1),
('AEC','MaxFastRatio 0','AEC',1),
('AEC','MaxFastRatio 1','AEC',1),
('AEC','MaxSlowRatio 0','AEC',1),
('AEC','MaxSlowRatio 1','AEC',1),
('AEC','FastStep 0','AEC',1),
('AEC','FastStep 1','AEC',1),
('AEC','SlowStep 0','AEC',1),
('AEC','SlowStep 1','AEC',1),
('AEC','SlowRange 0','AEC',1),
('AEC','SlowRange 1','AEC',1),
('AEC','StableRange 0-0','AEC',1),
('AEC','StableRange 0-1','AEC',1),
('AEC','StableRange 1-0','AEC',1),
('AEC','StableRange 1-1','AEC',1),
('AEC','PresetUp 0','AEC',1),
('AEC','PresetDown 0','AEC',1),
('AEC','PresetUp 1','AEC',1),
('AEC','PresetDown 1','AEC',1),
('AEC','MinExpo 0','AEC',1),
('AEC','MinExpo 0 IR_AB', 'AEC_IR_AB', 1),
('AEC','MinExpo 0 RGB_AB', 'AEC_RGB_AB', 1),
('AEC','MinExpo 1','AEC',1),
('AEC','MinExpo 2','AEC',1),
('AEC','MinExpo 3','AEC',1),
('AEC','MaxExpo 0','AEC',1),
('AEC','MaxExpo 0 IR_AB', 'AEC_IR_AB', 1),
('AEC','MaxExpo 0 RGB_AB', 'AEC_RGB_AB', 1),
('AEC','MaxExpo 1','AEC',1),
('AEC','MaxExpo 2','AEC',1),
('AEC','MaxExpo 3','AEC',1),
('AEC','MinGain 0','AEC',1),
('AEC','MinGain 0 IR_AB', 'AEC_IR_AB', 1),
('AEC','MinGain 0 RGB_AB', 'AEC_RGB_AB', 1),
('AEC','MinGain 1','AEC',1),
('AEC','MinGain 2','AEC',1),
('AEC','MinGain 3','AEC',1),
('AEC','MaxGain 0','AEC',1),
('AEC','MaxGain 0 IR_AB', 'AEC_IR_AB', 1),
('AEC','MaxGain 0 RGB_AB', 'AEC_RGB_AB', 1),
('AEC','MaxGain 1','AEC',1),
('AEC','MaxGain 2','AEC',1),
('AEC','MaxGain 3','AEC',1),
('AEC','AECManEnable','AEC',1),
('AEC','Expo 0','AEC',1),
('AEC','Expo 1','AEC',1),
('AEC','Expo 2','AEC',1),
('AEC','Expo 3','AEC',1),
('AEC','Gain 0','AEC',1),
('AEC','Gain 1','AEC',1),
('AEC','Gain 2','AEC',1),
('AEC','Gain 3','AEC',1),
('AEC','PresetExp','AEC',1),
('AEC','PresetGain','AEC',1),
('AEC_L','roi_weight_en','CAECStatistic_V60_L',0),
('AEC_L','Left','CAECStatistic_V60_L',0),
('AEC_L','Top','CAECStatistic_V60_L',0),
('AEC_L','Right','CAECStatistic_V60_L',0),
('AEC_L','Bottom','CAECStatistic_V60_L',0),
('AEC_L','roi_width','CAECStatistic_V60_L',0),
('AEC_L','roi_height','CAECStatistic_V60_L',0),
('AEC_L','sclh','CAECStatistic_V60_L',0),
('AEC_L','sclv','CAECStatistic_V60_L',0),
('AEC_L','roi_blk_w','CAECStatistic_V60_L',0),
('AEC_M','roi_weight_en','CAECStatistic_V60_M',0),
('AEC_M','Left','CAECStatistic_V60_M',0),
('AEC_M','Top','CAECStatistic_V60_M',0),
('AEC_M','Right','CAECStatistic_V60_M',0),
('AEC_M','Bottom','CAECStatistic_V60_M',0),
('AEC_M','roi_width','CAECStatistic_V60_M',0),
('AEC_M','roi_height','CAECStatistic_V60_M',0),
('AEC_M','sclh','CAECStatistic_V60_M',0),
('AEC_M','sclv','CAECStatistic_V60_M',0),
('AEC_M','roi_blk_w','CAECStatistic_V60_M',0),
('AEC_S','roi_weight_en','CAECStatistic_V60_S',0),
('AEC_S','Left','CAECStatistic_V60_S',0),
('AEC_S','Top','CAECStatistic_V60_S',0),
('AEC_S','Right','CAECStatistic_V60_S',0),
('AEC_S','Bottom','CAECStatistic_V60_S',0),
('AEC_S','roi_width','CAECStatistic_V60_S',0),
('AEC_S','roi_height','CAECStatistic_V60_S',0),
('AEC_S','sclh','CAECStatistic_V60_S',0),
('AEC_S','sclv','CAECStatistic_V60_S',0),
('AEC_S','roi_blk_w','CAECStatistic_V60_S',0),
('AEC_V','roi_weight_en','CAECStatistic_V60_V',0),
('AEC_V','Left','CAECStatistic_V60_V',0),
('AEC_V','Top','CAECStatistic_V60_V',0),
('AEC_V','Right','CAECStatistic_V60_V',0),
('AEC_V','Bottom','CAECStatistic_V60_V',0),
('AEC_V','roi_width','CAECStatistic_V60_V',0),
('AEC_V','roi_height','CAECStatistic_V60_V',0),
('AEC_V','sclh','CAECStatistic_V60_V',0),
('AEC_V','sclv','CAECStatistic_V60_V',0),
('AEC_V','roi_blk_w','CAECStatistic_V60_V',0);

