DELETE FROM ui_info WHERE module_name='Contrast';
DELETE FROM ui_info_regmodule WHERE ui_module_name='Contrast';
INSERT INTO ui_info VALUES 
('Contrast', 'AdjCurveEnable', 0, 'r_bAdjCurveEnable', NULL, 'Administrator'),
('Contrast', 'ContrastEnable', 0, 'r_bSCurveEnable', NULL, 'Administrator'),
('Contrast', 'ContrastEnable_IR_AB', 0, 'r_bSCurveEnable', NULL, 'Administrator'),
('Contrast', 'ContrastEnable_RGB_AB', 0, 'r_bSCurveEnable', NULL, 'Administrator'),
('Contrast', 'SPoint', 0, 'r_nSPoint', NULL, 'Administrator'),
('Contrast', 'Intensity', 0, 'r_nIntensity', NULL, 'Administrator'),
('Contrast', 'ManStretchEnable', 0, 'r_bManStretchEnable', NULL, 'Administrator'),
('Contrast', 'ManLowLevel', 0, 'r_nManLowLevel', NULL, 'Administrator'),
('Contrast', 'ManStretchGain', 0, 'r_nManStretchGain', NULL, 'Administrator'),
('Contrast', 'Mode', 0, 'r_nScurvePage', NULL, 'Administrator'),
('Contrast', 'Mode_IR_AB', 0, 'r_nScurvePage', NULL, 'Administrator'),
('Contrast', 'Mode_RGB_AB', 0, 'r_nScurvePage', NULL, 'Administrator'),
('Contrast', 'Manual', 0, 'r_nManual', NULL, 'Administrator'),
('Contrast', 'Manual_IR_AB', 0, 'r_nManual', NULL, 'Administrator'),
('Contrast', 'Manual_RGB_AB', 0, 'r_nManual', NULL, 'Administrator'),
('Contrast', 'ISO Node[0]', 0, 'r_nISONode[0]', NULL, 'Administrator'),
('Contrast', 'ISO Node[0]_IR_AB', 0, 'r_nISONode[0]', NULL, 'Administrator'),
('Contrast', 'ISO Node[0]_RGB_AB', 0, 'r_nISONode[0]', NULL, 'Administrator'),
('Contrast', 'ISO Node[1]', 0, 'r_nISONode[1]', NULL, 'Administrator'),
('Contrast', 'ISO Node[1]_IR_AB', 0, 'r_nISONode[1]', NULL, 'Administrator'),
('Contrast', 'ISO Node[1]_RGB_AB', 0, 'r_nISONode[1]', NULL, 'Administrator'),
('Contrast', 'ISO Node[2]', 0, 'r_nISONode[2]', NULL, 'Administrator'),
('Contrast', 'ISO Node[2]_IR_AB', 0, 'r_nISONode[2]', NULL, 'Administrator'),
('Contrast', 'ISO Node[2]_RGB_AB', 0, 'r_nISONode[2]', NULL, 'Administrator'),
('Contrast', 'ISO Node[3]', 0, 'r_nISONode[3]', NULL, 'Administrator'),
('Contrast', 'ISO Node[3]_IR_AB', 0, 'r_nISONode[3]', NULL, 'Administrator'),
('Contrast', 'ISO Node[3]_RGB_AB', 0, 'r_nISONode[3]', NULL, 'Administrator'),
('Contrast', 'ISO Node[4]', 0, 'r_nISONode[4]', NULL, 'Administrator'),
('Contrast', 'ISO Node[4]_IR_AB', 0, 'r_nISONode[4]', NULL, 'Administrator'),
('Contrast', 'ISO Node[4]_RGB_AB', 0, 'r_nISONode[4]', NULL, 'Administrator'),
('Contrast', 'Low Point[0]', 0, 'r_nLowPoint[0]', NULL, 'Administrator'),
('Contrast', 'Low Point[0]_IR_AB', 0, 'r_nLowPoint[0]', NULL, 'Administrator'),
('Contrast', 'Low Point[0]_RGB_AB', 0, 'r_nLowPoint[0]', NULL, 'Administrator'),
('Contrast', 'Low Point[1]', 0, 'r_nLowPoint[1]', NULL, 'Administrator'),
('Contrast', 'Low Point[1]_IR_AB', 0, 'r_nLowPoint[1]', NULL, 'Administrator'),
('Contrast', 'Low Point[1]_RGB_AB', 0, 'r_nLowPoint[1]', NULL, 'Administrator'),
('Contrast', 'Low Point[2]', 0, 'r_nLowPoint[2]', NULL, 'Administrator'),
('Contrast', 'Low Point[2]_IR_AB', 0, 'r_nLowPoint[2]', NULL, 'Administrator'),
('Contrast', 'Low Point[2]_RGB_AB', 0, 'r_nLowPoint[2]', NULL, 'Administrator'),
('Contrast', 'Low Point[3]', 0, 'r_nLowPoint[3]', NULL, 'Administrator'),
('Contrast', 'Low Point[3]_IR_AB', 0, 'r_nLowPoint[3]', NULL, 'Administrator'),
('Contrast', 'Low Point[3]_RGB_AB', 0, 'r_nLowPoint[3]', NULL, 'Administrator'),
('Contrast', 'Low Point[4]', 0, 'r_nLowPoint[4]', NULL, 'Administrator'),
('Contrast', 'Low Point[4]_IR_AB', 0, 'r_nLowPoint[4]', NULL, 'Administrator'),
('Contrast', 'Low Point[4]_RGB_AB', 0, 'r_nLowPoint[4]', NULL, 'Administrator'),
('Contrast', 'High Point[0]', 0, 'r_nHighPoint[0]', NULL, 'Administrator'),
('Contrast', 'High Point[0]_IR_AB', 0, 'r_nHighPoint[0]', NULL, 'Administrator'),
('Contrast', 'High Point[0]_RGB_AB', 0, 'r_nHighPoint[0]', NULL, 'Administrator'),
('Contrast', 'High Point[1]', 0, 'r_nHighPoint[1]', NULL, 'Administrator'),
('Contrast', 'High Point[1]_IR_AB', 0, 'r_nHighPoint[1]', NULL, 'Administrator'),
('Contrast', 'High Point[1]_RGB_AB', 0, 'r_nHighPoint[1]', NULL, 'Administrator'),
('Contrast', 'High Point[2]', 0, 'r_nHighPoint[2]', NULL, 'Administrator'),
('Contrast', 'High Point[2]_IR_AB', 0, 'r_nHighPoint[2]', NULL, 'Administrator'),
('Contrast', 'High Point[2]_RGB_AB', 0, 'r_nHighPoint[2]', NULL, 'Administrator'),
('Contrast', 'High Point[3]', 0, 'r_nHighPoint[3]', NULL, 'Administrator'),
('Contrast', 'High Point[3]_IR_AB', 0, 'r_nHighPoint[3]', NULL, 'Administrator'),
('Contrast', 'High Point[3]_RGB_AB', 0, 'r_nHighPoint[3]', NULL, 'Administrator'),
('Contrast', 'High Point[4]', 0, 'r_nHighPoint[4]', NULL, 'Administrator'),
('Contrast', 'High Point[4]_IR_AB', 0, 'r_nHighPoint[4]', NULL, 'Administrator'),
('Contrast', 'High Point[4]_RGB_AB', 0, 'r_nHighPoint[4]', NULL, 'Administrator'),
('Contrast', 'Low Str[0]', 0, 'r_nLowStrength[0]', NULL, 'Administrator'),
('Contrast', 'Low Str[0]_IR_AB', 0, 'r_nLowStrength[0]', NULL, 'Administrator'),
('Contrast', 'Low Str[0]_RGB_AB', 0, 'r_nLowStrength[0]', NULL, 'Administrator'),
('Contrast', 'Low Str[1]', 0, 'r_nLowStrength[1]', NULL, 'Administrator'),
('Contrast', 'Low Str[1]_IR_AB', 0, 'r_nLowStrength[1]', NULL, 'Administrator'),
('Contrast', 'Low Str[1]_RGB_AB', 0, 'r_nLowStrength[1]', NULL, 'Administrator'),
('Contrast', 'Low Str[2]', 0, 'r_nLowStrength[2]', NULL, 'Administrator'),
('Contrast', 'Low Str[2]_IR_AB', 0, 'r_nLowStrength[2]', NULL, 'Administrator'),
('Contrast', 'Low Str[2]_RGB_AB', 0, 'r_nLowStrength[2]', NULL, 'Administrator'),
('Contrast', 'Low Str[3]', 0, 'r_nLowStrength[3]', NULL, 'Administrator'),
('Contrast', 'Low Str[3]_IR_AB', 0, 'r_nLowStrength[3]', NULL, 'Administrator'),
('Contrast', 'Low Str[3]_RGB_AB', 0, 'r_nLowStrength[3]', NULL, 'Administrator'),
('Contrast', 'Low Str[4]', 0, 'r_nLowStrength[4]', NULL, 'Administrator'),
('Contrast', 'Low Str[4]_IR_AB', 0, 'r_nLowStrength[4]', NULL, 'Administrator'),
('Contrast', 'Low Str[4]_RGB_AB', 0, 'r_nLowStrength[4]', NULL, 'Administrator'),
('Contrast', 'High Str[0]', 0, 'r_nHighStrength[0]', NULL, 'Administrator'),
('Contrast', 'High Str[0]_IR_AB', 0, 'r_nHighStrength[0]', NULL, 'Administrator'),
('Contrast', 'High Str[0]_RGB_AB', 0, 'r_nHighStrength[0]', NULL, 'Administrator'),
('Contrast', 'High Str[1]', 0, 'r_nHighStrength[1]', NULL, 'Administrator'),
('Contrast', 'High Str[1]_IR_AB', 0, 'r_nHighStrength[1]', NULL, 'Administrator'),
('Contrast', 'High Str[1]_RGB_AB', 0, 'r_nHighStrength[1]', NULL, 'Administrator'),
('Contrast', 'High Str[2]', 0, 'r_nHighStrength[2]', NULL, 'Administrator'),
('Contrast', 'High Str[2]_IR_AB', 0, 'r_nHighStrength[2]', NULL, 'Administrator'),
('Contrast', 'High Str[2]_RGB_AB', 0, 'r_nHighStrength[2]', NULL, 'Administrator'),
('Contrast', 'High Str[3]', 0, 'r_nHighStrength[3]', NULL, 'Administrator'),
('Contrast', 'High Str[3]_IR_AB', 0, 'r_nHighStrength[3]', NULL, 'Administrator'),
('Contrast', 'High Str[3]_RGB_AB', 0, 'r_nHighStrength[3]', NULL, 'Administrator'),
('Contrast', 'High Str[4]', 0, 'r_nHighStrength[4]', NULL, 'Administrator'),
('Contrast', 'High Str[4]_IR_AB', 0, 'r_nHighStrength[4]', NULL, 'Administrator'),
('Contrast', 'High Str[4]_RGB_AB', 0, 'r_nHighStrength[4]', NULL, 'Administrator'),
('Contrast', 'AdjustLuma', 0, 'r_bAdjustLuma', NULL, 'Administrator'),
('Contrast', 'AdjustLuma_IR_AB', 0, 'r_bAdjustLuma', NULL, 'Administrator'),
('Contrast', 'AdjustLuma_RGB_AB', 0, 'r_bAdjustLuma', NULL, 'Administrator'),
('Contrast', 'StretchISOList[0]', 0, 'r_pStretchISOList[0]', NULL, 'Administrator'),
('Contrast', 'StretchISOList[0]_IR_AB', 0, 'r_pStretchISOList[0]', NULL, 'Administrator'),
('Contrast', 'StretchISOList[0]_RGB_AB', 0, 'r_pStretchISOList[0]', NULL, 'Administrator'),
('Contrast', 'StretchISOList[1]', 0, 'r_pStretchISOList[1]', NULL, 'Administrator'),
('Contrast', 'StretchISOList[1]_IR_AB', 0, 'r_pStretchISOList[1]', NULL, 'Administrator'),
('Contrast', 'StretchISOList[1]_RGB_AB', 0, 'r_pStretchISOList[1]', NULL, 'Administrator'),
('Contrast', 'StretchISOList[2]', 0, 'r_pStretchISOList[2]', NULL, 'Administrator'),
('Contrast', 'StretchISOList[2]_IR_AB', 0, 'r_pStretchISOList[2]', NULL, 'Administrator'),
('Contrast', 'StretchISOList[2]_RGB_AB', 0, 'r_pStretchISOList[2]', NULL, 'Administrator'),
('Contrast', 'StretchISOList[3]', 0, 'r_pStretchISOList[3]', NULL, 'Administrator'),
('Contrast', 'StretchISOList[3]_IR_AB', 0, 'r_pStretchISOList[3]', NULL, 'Administrator'),
('Contrast', 'StretchISOList[3]_RGB_AB', 0, 'r_pStretchISOList[3]', NULL, 'Administrator'),
('Contrast', 'StretchISOList[4]', 0, 'r_pStretchISOList[4]', NULL, 'Administrator'),
('Contrast', 'StretchISOList[4]_IR_AB', 0, 'r_pStretchISOList[4]', NULL, 'Administrator'),
('Contrast', 'StretchISOList[4]_RGB_AB', 0, 'r_pStretchISOList[4]', NULL, 'Administrator'),
('Contrast', 'LowLevelOffset[0]', 0, 'r_pLowLevelOffset[0]', NULL, 'Administrator'),
('Contrast', 'LowLevelOffset[0]_IR_AB', 0, 'r_pLowLevelOffset[0]', NULL, 'Administrator'),
('Contrast', 'LowLevelOffset[0]_RGB_AB', 0, 'r_pLowLevelOffset[0]', NULL, 'Administrator'),
('Contrast', 'LowLevelOffset[1]', 0, 'r_pLowLevelOffset[1]', NULL, 'Administrator'),
('Contrast', 'LowLevelOffset[1]_IR_AB', 0, 'r_pLowLevelOffset[1]', NULL, 'Administrator'),
('Contrast', 'LowLevelOffset[1]_RGB_AB', 0, 'r_pLowLevelOffset[1]', NULL, 'Administrator'),
('Contrast', 'LowLevelOffset[2]', 0, 'r_pLowLevelOffset[2]', NULL, 'Administrator'),
('Contrast', 'LowLevelOffset[2]_IR_AB', 0, 'r_pLowLevelOffset[2]', NULL, 'Administrator'),
('Contrast', 'LowLevelOffset[2]_RGB_AB', 0, 'r_pLowLevelOffset[2]', NULL, 'Administrator'),
('Contrast', 'LowLevelOffset[3]', 0, 'r_pLowLevelOffset[3]', NULL, 'Administrator'),
('Contrast', 'LowLevelOffset[3]_IR_AB', 0, 'r_pLowLevelOffset[3]', NULL, 'Administrator'),
('Contrast', 'LowLevelOffset[3]_RGB_AB', 0, 'r_pLowLevelOffset[3]', NULL, 'Administrator'),
('Contrast', 'LowLevelOffset[4]', 0, 'r_pLowLevelOffset[4]', NULL, 'Administrator'),
('Contrast', 'LowLevelOffset[4]_IR_AB', 0, 'r_pLowLevelOffset[4]', NULL, 'Administrator'),
('Contrast', 'LowLevelOffset[4]_RGB_AB', 0, 'r_pLowLevelOffset[4]', NULL, 'Administrator'),
('Contrast', 'StretchRat[0]', 0, 'r_pStretchRat[0]', NULL, 'Administrator'),
('Contrast', 'StretchRat[0]_IR_AB', 0, 'r_pStretchRat[0]', NULL, 'Administrator'),
('Contrast', 'StretchRat[0]_RGB_AB', 0, 'r_pStretchRat[0]', NULL, 'Administrator'),
('Contrast', 'StretchRat[1]', 0, 'r_pStretchRat[1]', NULL, 'Administrator'),
('Contrast', 'StretchRat[1]_IR_AB', 0, 'r_pStretchRat[1]', NULL, 'Administrator'),
('Contrast', 'StretchRat[1]_RGB_AB', 0, 'r_pStretchRat[1]', NULL, 'Administrator'),
('Contrast', 'StretchRat[2]', 0, 'r_pStretchRat[2]', NULL, 'Administrator'),
('Contrast', 'StretchRat[2]_IR_AB', 0, 'r_pStretchRat[2]', NULL, 'Administrator'),
('Contrast', 'StretchRat[2]_RGB_AB', 0, 'r_pStretchRat[2]', NULL, 'Administrator'),
('Contrast', 'StretchRat[3]', 0, 'r_pStretchRat[3]', NULL, 'Administrator'),
('Contrast', 'StretchRat[3]_IR_AB', 0, 'r_pStretchRat[3]', NULL, 'Administrator'),
('Contrast', 'StretchRat[3]_RGB_AB', 0, 'r_pStretchRat[3]', NULL, 'Administrator'),
('Contrast', 'StretchRat[4]', 0, 'r_pStretchRat[4]', NULL, 'Administrator'),
('Contrast', 'StretchRat[4]_IR_AB', 0, 'r_pStretchRat[4]', NULL, 'Administrator'),
('Contrast', 'StretchRat[4]_RGB_AB', 0, 'r_pStretchRat[4]', NULL, 'Administrator'),
('Contrast', 'LowPoints', 0, 'r_nLowPoints', NULL, 'Administrator'),
('Contrast', 'LowPoints_IR_AB', 0, 'r_nLowPoints', NULL, 'Administrator'),
('Contrast', 'LowPoints_RGB_AB', 0, 'r_nLowPoints', NULL, 'Administrator'),
('Contrast', 'HighPoints', 0, 'r_nHighPoints', NULL, 'Administrator'),
('Contrast', 'HighPoints_IR_AB', 0, 'r_nHighPoints', NULL, 'Administrator'),
('Contrast', 'HighPoints_RGB_AB', 0, 'r_nHighPoints', NULL, 'Administrator'),
('Contrast', 'LowStep', 0, 'r_nLowStep', NULL, 'Administrator'),
('Contrast', 'LowStep_IR_AB', 0, 'r_nLowStep', NULL, 'Administrator'),
('Contrast', 'LowStep_RGB_AB', 0, 'r_nLowStep', NULL, 'Administrator'),
('Contrast', 'HighStep', 0, 'r_nHighStep', NULL, 'Administrator'),
('Contrast', 'HighStep_IR_AB', 0, 'r_nHighStep', NULL, 'Administrator'),
('Contrast', 'HighStep_RGB_AB', 0, 'r_nHighStep', NULL, 'Administrator'),
('Contrast', 'MinLowLevelA', 0, 'r_nMinLowLevelA', NULL, 'Administrator'),
('Contrast', 'MinLowLevelA_IR_AB', 0, 'r_nMinLowLevelA', NULL, 'Administrator'),
('Contrast', 'MinLowLevelA_RGB_AB', 0, 'r_nMinLowLevelA', NULL, 'Administrator'),
('Contrast', 'MinLowLevelB', 0, 'r_nMinLowLevelB', NULL, 'Administrator'),
('Contrast', 'MinLowLevelB_IR_AB', 0, 'r_nMinLowLevelB', NULL, 'Administrator'),
('Contrast', 'MinLowLevelB_RGB_AB', 0, 'r_nMinLowLevelB', NULL, 'Administrator'),
('Contrast', 'MaxLowLevelA', 0, 'r_nMaxLowLevelA', NULL, 'Administrator'),
('Contrast', 'MaxLowLevelA_IR_AB', 0, 'r_nMaxLowLevelA', NULL, 'Administrator'),
('Contrast', 'MaxLowLevelA_RGB_AB', 0, 'r_nMaxLowLevelA', NULL, 'Administrator'),
('Contrast', 'MaxLowLevelB', 0, 'r_nMaxLowLevelB', NULL, 'Administrator'),
('Contrast', 'MaxLowLevelB_IR_AB', 0, 'r_nMaxLowLevelB', NULL, 'Administrator'),
('Contrast', 'MaxLowLevelB_RGB_AB', 0, 'r_nMaxLowLevelB', NULL, 'Administrator'),
('Contrast', 'MinHighLevelA', 0, 'r_nMinHighLevelA', NULL, 'Administrator'),
('Contrast', 'MinHighLevelA_IR_AB', 0, 'r_nMinHighLevelA', NULL, 'Administrator'),
('Contrast', 'MinHighLevelA_RGB_AB', 0, 'r_nMinHighLevelA', NULL, 'Administrator'),
('Contrast', 'MinHighLevelB', 0, 'r_nMinHighLevelB', NULL, 'Administrator'),
('Contrast', 'MinHighLevelB_IR_AB', 0, 'r_nMinHighLevelB', NULL, 'Administrator'),
('Contrast', 'MinHighLevelB_RGB_AB', 0, 'r_nMinHighLevelB', NULL, 'Administrator'),
('Contrast', 'CurveThre1', 0, 'r_nCurveThre1', NULL, 'Administrator'),
('Contrast', 'CurveThre1_IR_AB', 0, 'r_nCurveThre1', NULL, 'Administrator'),
('Contrast', 'CurveThre1_RGB_AB', 0, 'r_nCurveThre1', NULL, 'Administrator'),
('Contrast', 'CurveThre2', 0, 'r_nCurveThre2', NULL, 'Administrator'),
('Contrast', 'CurveThre2_IR_AB', 0, 'r_nCurveThre2', NULL, 'Administrator'),
('Contrast', 'CurveThre2_RGB_AB', 0, 'r_nCurveThre2', NULL, 'Administrator'),
('Contrast','Current Gain L',0,'current L Gain',NULL,'Administrator'),
('Contrast','Current Expo L',0,'current L Expo',NULL,'Administrator');

INSERT INTO ui_info_regmodule VALUES
('Contrast', 'AdjCurveEnable', 'CURVE', 1),
('Contrast', 'ContrastEnable', 'CURVE', 1),
('Contrast', 'ContrastEnable_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'ContrastEnable_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast', 'SPoint', 'CURVE', 1),
('Contrast', 'Intensity', 'CURVE', 1),
('Contrast', 'ManStretchEnable', 'CURVE', 1),
('Contrast', 'ManLowLevel', 'CURVE', 1),
('Contrast', 'ManStretchGain', 'CURVE', 1),
('Contrast', 'Mode', 'NewFunctionPatch', 1),
('Contrast', 'Mode_IR_AB', 'NewFunctionPatch_IR_AB', 1),
('Contrast', 'Mode_RGB_AB', 'NewFunctionPatch_RGB_AB', 1),
('Contrast', 'Manual', 'NewFunctionPatch', 1),
('Contrast', 'Manual_IR_AB', 'NewFunctionPatch_IR_AB', 1),
('Contrast', 'Manual_RGB_AB', 'NewFunctionPatch_RGB_AB', 1),
('Contrast', 'ISO Node[0]', 'NewFunctionPatch', 1),
('Contrast', 'ISO Node[0]_IR_AB', 'NewFunctionPatch_IR_AB', 1),
('Contrast', 'ISO Node[0]_RGB_AB', 'NewFunctionPatch_RGB_AB', 1),
('Contrast', 'ISO Node[1]', 'NewFunctionPatch', 1),
('Contrast', 'ISO Node[1]_IR_AB', 'NewFunctionPatch_IR_AB', 1),
('Contrast', 'ISO Node[1]_RGB_AB', 'NewFunctionPatch_RGB_AB', 1),
('Contrast', 'ISO Node[2]', 'NewFunctionPatch', 1),
('Contrast', 'ISO Node[2]_IR_AB', 'NewFunctionPatch_IR_AB', 1),
('Contrast', 'ISO Node[2]_RGB_AB', 'NewFunctionPatch_RGB_AB', 1),
('Contrast', 'ISO Node[3]', 'NewFunctionPatch', 1),
('Contrast', 'ISO Node[3]_IR_AB', 'NewFunctionPatch_IR_AB', 1),
('Contrast', 'ISO Node[3]_RGB_AB', 'NewFunctionPatch_RGB_AB', 1),
('Contrast', 'ISO Node[4]', 'NewFunctionPatch', 1),
('Contrast', 'ISO Node[4]_IR_AB', 'NewFunctionPatch_IR_AB', 1),
('Contrast', 'ISO Node[4]_RGB_AB', 'NewFunctionPatch_RGB_AB', 1),
('Contrast', 'Low Point[0]', 'NewFunctionPatch', 1),
('Contrast', 'Low Point[0]_IR_AB', 'NewFunctionPatch_IR_AB', 1),
('Contrast', 'Low Point[0]_RGB_AB', 'NewFunctionPatch_RGB_AB', 1),
('Contrast', 'Low Point[1]', 'NewFunctionPatch', 1),
('Contrast', 'Low Point[1]_IR_AB', 'NewFunctionPatch_IR_AB', 1),
('Contrast', 'Low Point[1]_RGB_AB', 'NewFunctionPatch_RGB_AB', 1),
('Contrast', 'Low Point[2]', 'NewFunctionPatch', 1),
('Contrast', 'Low Point[2]_IR_AB', 'NewFunctionPatch_IR_AB', 1),
('Contrast', 'Low Point[2]_RGB_AB', 'NewFunctionPatch_RGB_AB', 1),
('Contrast', 'Low Point[3]', 'NewFunctionPatch', 1),
('Contrast', 'Low Point[3]_IR_AB', 'NewFunctionPatch_IR_AB', 1),
('Contrast', 'Low Point[3]_RGB_AB', 'NewFunctionPatch_RGB_AB', 1),
('Contrast', 'Low Point[4]', 'NewFunctionPatch', 1),
('Contrast', 'Low Point[4]_IR_AB', 'NewFunctionPatch_IR_AB', 1),
('Contrast', 'Low Point[4]_RGB_AB', 'NewFunctionPatch_RGB_AB', 1),
('Contrast', 'High Point[0]', 'NewFunctionPatch', 1),
('Contrast', 'High Point[0]_IR_AB', 'NewFunctionPatch_IR_AB', 1),
('Contrast', 'High Point[0]_RGB_AB', 'NewFunctionPatch_RGB_AB', 1),
('Contrast', 'High Point[1]', 'NewFunctionPatch', 1),
('Contrast', 'High Point[1]_IR_AB', 'NewFunctionPatch_IR_AB', 1),
('Contrast', 'High Point[1]_RGB_AB', 'NewFunctionPatch_RGB_AB', 1),
('Contrast', 'High Point[2]', 'NewFunctionPatch', 1),
('Contrast', 'High Point[2]_IR_AB', 'NewFunctionPatch_IR_AB', 1),
('Contrast', 'High Point[2]_RGB_AB', 'NewFunctionPatch_RGB_AB', 1),
('Contrast', 'High Point[3]', 'NewFunctionPatch', 1),
('Contrast', 'High Point[3]_IR_AB', 'NewFunctionPatch_IR_AB', 1),
('Contrast', 'High Point[3]_RGB_AB', 'NewFunctionPatch_RGB_AB', 1),
('Contrast', 'High Point[4]', 'NewFunctionPatch', 1),
('Contrast', 'High Point[4]_IR_AB', 'NewFunctionPatch_IR_AB', 1),
('Contrast', 'High Point[4]_RGB_AB', 'NewFunctionPatch_RGB_AB', 1),
('Contrast', 'Low Str[0]', 'NewFunctionPatch', 1),
('Contrast', 'Low Str[0]_IR_AB', 'NewFunctionPatch_IR_AB', 1),
('Contrast', 'Low Str[0]_RGB_AB', 'NewFunctionPatch_RGB_AB', 1),
('Contrast', 'Low Str[1]', 'NewFunctionPatch', 1),
('Contrast', 'Low Str[1]_IR_AB', 'NewFunctionPatch_IR_AB', 1),
('Contrast', 'Low Str[1]_RGB_AB', 'NewFunctionPatch_RGB_AB', 1),
('Contrast', 'Low Str[2]', 'NewFunctionPatch', 1),
('Contrast', 'Low Str[2]_IR_AB', 'NewFunctionPatch_IR_AB', 1),
('Contrast', 'Low Str[2]_RGB_AB', 'NewFunctionPatch_RGB_AB', 1),
('Contrast', 'Low Str[3]', 'NewFunctionPatch', 1),
('Contrast', 'Low Str[3]_IR_AB', 'NewFunctionPatch_IR_AB', 1),
('Contrast', 'Low Str[3]_RGB_AB', 'NewFunctionPatch_RGB_AB', 1),
('Contrast', 'Low Str[4]', 'NewFunctionPatch', 1),
('Contrast', 'Low Str[4]_IR_AB', 'NewFunctionPatch_IR_AB', 1),
('Contrast', 'Low Str[4]_RGB_AB', 'NewFunctionPatch_RGB_AB', 1),
('Contrast', 'High Str[0]', 'NewFunctionPatch', 1),
('Contrast', 'High Str[0]_IR_AB', 'NewFunctionPatch_IR_AB', 1),
('Contrast', 'High Str[0]_RGB_AB', 'NewFunctionPatch_RGB_AB', 1),
('Contrast', 'High Str[1]', 'NewFunctionPatch', 1),
('Contrast', 'High Str[1]_IR_AB', 'NewFunctionPatch_IR_AB', 1),
('Contrast', 'High Str[1]_RGB_AB', 'NewFunctionPatch_RGB_AB', 1),
('Contrast', 'High Str[2]', 'NewFunctionPatch', 1),
('Contrast', 'High Str[2]_IR_AB', 'NewFunctionPatch_IR_AB', 1),
('Contrast', 'High Str[2]_RGB_AB', 'NewFunctionPatch_RGB_AB', 1),
('Contrast', 'High Str[3]', 'NewFunctionPatch', 1),
('Contrast', 'High Str[3]_IR_AB', 'NewFunctionPatch_IR_AB', 1),
('Contrast', 'High Str[3]_RGB_AB', 'NewFunctionPatch_RGB_AB', 1),
('Contrast', 'High Str[4]', 'NewFunctionPatch', 1),
('Contrast', 'High Str[4]_IR_AB', 'NewFunctionPatch_IR_AB', 1),
('Contrast', 'High Str[4]_RGB_AB', 'NewFunctionPatch_RGB_AB', 1),
('Contrast', 'AdjustLuma', 'CURVE', 1),
('Contrast', 'AdjustLuma_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'AdjustLuma_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast', 'StretchISOList[0]', 'CURVE', 1),
('Contrast', 'StretchISOList[0]_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'StretchISOList[0]_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast', 'StretchISOList[1]', 'CURVE', 1),
('Contrast', 'StretchISOList[1]_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'StretchISOList[1]_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast', 'StretchISOList[2]', 'CURVE', 1),
('Contrast', 'StretchISOList[2]_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'StretchISOList[2]_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast', 'StretchISOList[3]', 'CURVE', 1),
('Contrast', 'StretchISOList[3]_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'StretchISOList[3]_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast', 'StretchISOList[4]', 'CURVE', 1),
('Contrast', 'StretchISOList[4]_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'StretchISOList[4]_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast', 'LowLevelOffset[0]', 'CURVE', 1),
('Contrast', 'LowLevelOffset[0]_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'LowLevelOffset[0]_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast', 'LowLevelOffset[1]', 'CURVE', 1),
('Contrast', 'LowLevelOffset[1]_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'LowLevelOffset[1]_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast', 'LowLevelOffset[2]', 'CURVE', 1),
('Contrast', 'LowLevelOffset[2]_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'LowLevelOffset[2]_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast', 'LowLevelOffset[3]', 'CURVE', 1),
('Contrast', 'LowLevelOffset[3]_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'LowLevelOffset[3]_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast', 'LowLevelOffset[4]', 'CURVE', 1),
('Contrast', 'LowLevelOffset[4]_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'LowLevelOffset[4]_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast', 'StretchRat[0]', 'CURVE', 1),
('Contrast', 'StretchRat[0]_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'StretchRat[0]_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast', 'StretchRat[1]', 'CURVE', 1),
('Contrast', 'StretchRat[1]_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'StretchRat[1]_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast', 'StretchRat[2]', 'CURVE', 1),
('Contrast', 'StretchRat[2]_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'StretchRat[2]_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast', 'StretchRat[3]', 'CURVE', 1),
('Contrast', 'StretchRat[3]_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'StretchRat[3]_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast', 'StretchRat[4]', 'CURVE', 1),
('Contrast', 'StretchRat[4]_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'StretchRat[4]_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast', 'LowPoints', 'CURVE', 1),
('Contrast', 'LowPoints_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'LowPoints_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast', 'HighPoints', 'CURVE', 1),
('Contrast', 'HighPoints_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'HighPoints_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast', 'LowStep', 'CURVE', 1),
('Contrast', 'LowStep_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'LowStep_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast', 'HighStep', 'CURVE', 1),
('Contrast', 'HighStep_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'HighStep_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast', 'MinLowLevelA', 'CURVE', 1),
('Contrast', 'MinLowLevelA_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'MinLowLevelA_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast', 'MinLowLevelB', 'CURVE', 1),
('Contrast', 'MinLowLevelB_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'MinLowLevelB_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast', 'MaxLowLevelA', 'CURVE', 1),
('Contrast', 'MaxLowLevelA_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'MaxLowLevelA_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast', 'MaxLowLevelB', 'CURVE', 1),
('Contrast', 'MaxLowLevelB_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'MaxLowLevelB_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast', 'MinHighLevelA', 'CURVE', 1),
('Contrast', 'MinHighLevelA_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'MinHighLevelA_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast', 'MinHighLevelB', 'CURVE', 1),
('Contrast', 'MinHighLevelB_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'MinHighLevelB_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast', 'CurveThre1', 'CURVE', 1),
('Contrast', 'CurveThre1_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'CurveThre1_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast', 'CurveThre2', 'CURVE', 1),
('Contrast', 'CurveThre2_IR_AB', 'CURVE_IR_AB', 1),
('Contrast', 'CurveThre2_RGB_AB', 'CURVE_RGB_AB', 1),
('Contrast','Current Gain L','PipeCtrl',1),
('Contrast','Current Expo L','PipeCtrl',1);
