DELETE FROM ui_info WHERE module_name='CCM';
DELETE FROM ui_info_regmodule WHERE ui_module_name='CCM';
INSERT INTO ui_info VALUES 
('CCM', 'CCMEnable', 0, 'r_ccm_en', NULL, 'Administrator'),
('CCM', 'ManCCMEnable', 0, 'r_bManCCMEnable', NULL, 'Administrator'),
('CCM', 'ManCCM', 0, 'r_pManCCM[0][0]', NULL, 'Administrator'),
('CCM', 'ManCCM', 1, 'r_pManCCM[0][1]', NULL, 'Administrator'),
('CCM', 'ManCCM', 2, 'r_pManCCM[0][2]', NULL, 'Administrator'),
('CCM', 'ManCCM', 3, 'r_pManCCM[1][0]', NULL, 'Administrator'),
('CCM', 'ManCCM', 4, 'r_pManCCM[1][1]', NULL, 'Administrator'),
('CCM', 'ManCCM', 5, 'r_pManCCM[1][2]', NULL, 'Administrator'),
('CCM', 'ManCCM', 6, 'r_pManCCM[2][0]', NULL, 'Administrator'),
('CCM', 'ManCCM', 7, 'r_pManCCM[2][1]', NULL, 'Administrator'),
('CCM', 'ManCCM', 8, 'r_pManCCM[2][2]', NULL, 'Administrator'),
('CCM', 'CCMD', 0, 'r_pCCMD[0][0]', NULL, 'Administrator'),
('CCM', 'CCMD', 1, 'r_pCCMD[0][1]', NULL, 'Administrator'),
('CCM', 'CCMD', 2, 'r_pCCMD[0][2]', NULL, 'Administrator'),
('CCM', 'CCMD', 3, 'r_pCCMD[1][0]', NULL, 'Administrator'),
('CCM', 'CCMD', 4, 'r_pCCMD[1][1]', NULL, 'Administrator'),
('CCM', 'CCMD', 5, 'r_pCCMD[1][2]', NULL, 'Administrator'),
('CCM', 'CCMD', 6, 'r_pCCMD[2][0]', NULL, 'Administrator'),
('CCM', 'CCMD', 7, 'r_pCCMD[2][1]', NULL, 'Administrator'),
('CCM', 'CCMD', 8, 'r_pCCMD[2][2]', NULL, 'Administrator'),
('CCM', 'CCMT', 0, 'r_pCCMT[0][0]', NULL, 'Administrator'),
('CCM', 'CCMT', 1, 'r_pCCMT[0][1]', NULL, 'Administrator'),
('CCM', 'CCMT', 2, 'r_pCCMT[0][2]', NULL, 'Administrator'),
('CCM', 'CCMT', 3, 'r_pCCMT[1][0]', NULL, 'Administrator'),
('CCM', 'CCMT', 4, 'r_pCCMT[1][1]', NULL, 'Administrator'),
('CCM', 'CCMT', 5, 'r_pCCMT[1][2]', NULL, 'Administrator'),
('CCM', 'CCMT', 6, 'r_pCCMT[2][0]', NULL, 'Administrator'),
('CCM', 'CCMT', 7, 'r_pCCMT[2][1]', NULL, 'Administrator'),
('CCM', 'CCMT', 8, 'r_pCCMT[2][2]', NULL, 'Administrator'),
('CCM', 'CCMA', 0, 'r_pCCMA[0][0]', NULL, 'Administrator'),
('CCM', 'CCMA', 1, 'r_pCCMA[0][1]', NULL, 'Administrator'),
('CCM', 'CCMA', 2, 'r_pCCMA[0][2]', NULL, 'Administrator'),
('CCM', 'CCMA', 3, 'r_pCCMA[1][0]', NULL, 'Administrator'),
('CCM', 'CCMA', 4, 'r_pCCMA[1][1]', NULL, 'Administrator'),
('CCM', 'CCMA', 5, 'r_pCCMA[1][2]', NULL, 'Administrator'),
('CCM', 'CCMA', 6, 'r_pCCMA[2][0]', NULL, 'Administrator'),
('CCM', 'CCMA', 7, 'r_pCCMA[2][1]', NULL, 'Administrator'),
('CCM', 'CCMA', 8, 'r_pCCMA[2][2]', NULL, 'Administrator'),
('CCM', 'CTD', 0, 'r_nCTD', NULL, 'Administrator'),
('CCM', 'CTM1', 0, 'r_nCTM1', NULL, 'Administrator'),
('CCM', 'CTM2', 0, 'r_nCTM2', NULL, 'Administrator'),
('CCM', 'ManCCM22', 0, 'r_pManCCM[0][0]', NULL, 'Administrator'),
('CCM', 'ManCCM21', 0, 'r_pManCCM[0][1]', NULL, 'Administrator'),
('CCM', 'ManCCM20', 0, 'r_pManCCM[0][2]', NULL, 'Administrator'),
('CCM', 'ManCCM12', 0, 'r_pManCCM[1][0]', NULL, 'Administrator'),
('CCM', 'ManCCM11', 0, 'r_pManCCM[1][1]', NULL, 'Administrator'),
('CCM', 'ManCCM10', 0, 'r_pManCCM[1][2]', NULL, 'Administrator'),
('CCM', 'ManCCM02', 0, 'r_pManCCM[2][0]', NULL, 'Administrator'),
('CCM', 'ManCCM01', 0, 'r_pManCCM[2][1]', NULL, 'Administrator'),
('CCM', 'ManCCM00', 0, 'r_pManCCM[2][2]', NULL, 'Administrator'),
('CCM', 'CCMD22', 0, 'r_pCCMD[0][0]', NULL, 'Administrator'),
('CCM', 'CCMD21', 0, 'r_pCCMD[0][1]', NULL, 'Administrator'),
('CCM', 'CCMD20', 0, 'r_pCCMD[0][2]', NULL, 'Administrator'),
('CCM', 'CCMD12', 0, 'r_pCCMD[1][0]', NULL, 'Administrator'),
('CCM', 'CCMD11', 0, 'r_pCCMD[1][1]', NULL, 'Administrator'),
('CCM', 'CCMD10', 0, 'r_pCCMD[1][2]', NULL, 'Administrator'),
('CCM', 'CCMD02', 0, 'r_pCCMD[2][0]', NULL, 'Administrator'),
('CCM', 'CCMD01', 0, 'r_pCCMD[2][1]', NULL, 'Administrator'),
('CCM', 'CCMD00', 0, 'r_pCCMD[2][2]', NULL, 'Administrator'),
('CCM', 'CCMT22', 0, 'r_pCCMT[0][0]', NULL, 'Administrator'),
('CCM', 'CCMT21', 0, 'r_pCCMT[0][1]', NULL, 'Administrator'),
('CCM', 'CCMT20', 0, 'r_pCCMT[0][2]', NULL, 'Administrator'),
('CCM', 'CCMT12', 0, 'r_pCCMT[1][0]', NULL, 'Administrator'),
('CCM', 'CCMT11', 0, 'r_pCCMT[1][1]', NULL, 'Administrator'),
('CCM', 'CCMT10', 0, 'r_pCCMT[1][2]', NULL, 'Administrator'),
('CCM', 'CCMT02', 0, 'r_pCCMT[2][0]', NULL, 'Administrator'),
('CCM', 'CCMT01', 0, 'r_pCCMT[2][1]', NULL, 'Administrator'),
('CCM', 'CCMT00', 0, 'r_pCCMT[2][2]', NULL, 'Administrator'),
('CCM', 'CCMA22', 0, 'r_pCCMA[0][0]', NULL, 'Administrator'),
('CCM', 'CCMA21', 0, 'r_pCCMA[0][1]', NULL, 'Administrator'),
('CCM', 'CCMA20', 0, 'r_pCCMA[0][2]', NULL, 'Administrator'),
('CCM', 'CCMA12', 0, 'r_pCCMA[1][0]', NULL, 'Administrator'),
('CCM', 'CCMA11', 0, 'r_pCCMA[1][1]', NULL, 'Administrator'),
('CCM', 'CCMA10', 0, 'r_pCCMA[1][2]', NULL, 'Administrator'),
('CCM', 'CCMA02', 0, 'r_pCCMA[2][0]', NULL, 'Administrator'),
('CCM', 'CCMA01', 0, 'r_pCCMA[2][1]', NULL, 'Administrator'),
('CCM', 'CCMA00', 0, 'r_pCCMA[2][2]', NULL, 'Administrator'),
('CCM', 'CTA', 0, 'r_nCTA', NULL, 'Administrator'),
('CCM','Current Gain B',0,'current B Gain',NULL,'Administrator'),
('CCM','Current Gain R',0,'current R Gain',NULL,'Administrator');
INSERT INTO ui_info_regmodule VALUES
('CCM','Current Gain B','PipeCtrl',1),
('CCM','Current Gain R','PipeCtrl',1);