FROM ubuntu:22.04

RUN sed -i "s@http://.*archive.ubuntu.com@https://mirrors.bfsu.edu.cn@g" /etc/apt/sources.list && \
    sed -i "s@http://.*security.ubuntu.com@https://mirrors.bfsu.edu.cn@g" /etc/apt/sources.list && \
    apt -o "Acquire::https::Verify-Peer=false" update && \
    apt -o "Acquire::https::Verify-Peer=false" install -y ca-certificates

RUN DEBIAN_FRONTEND=noninteractive apt update && \
    DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends \
                cmake \
                git \
                zip \
                build-essential \
                software-properties-common \
                libpcl-dev \
                libpcap-dev \
                libyaml-cpp-dev \
                && \
    rm -rf /var/lib/apt/lists/*

RUN DEBIAN_FRONTEND=noninteractive apt update && \
    DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends \
                sudo \
                gdb \
                qtcreator \
                && \
    rm -rf /var/lib/apt/lists/*
