(cl:in-package arbe_msgs-msg)
(cl:export '(CORRESPCTIME-VAL
          CORRESPCTIME
          FRAMENUMBER-VAL
          FRAMENUMBER
          HOSTHEADING-VAL
          HOSTHEADING
          HOSTHEADINGUNC-VAL
          HOSTHEADINGUNC
          HOSTVELOCITY-VAL
          HOSTVELOCITY
          HOSTVELOCITYUNC-VAL
          HOSTVELOCITYUNC
          HOSTOMEGA-VAL
          HOSTOMEGA
          HOSTOMEGAUNC-VAL
          HOSTOMEGAUNC
          NUMBEROFOBJECTS-VAL
          NUMBEROFOBJECTS
          LOCAL_CATR_X-VAL
          LOCAL_CATR_X
          LOCAL_CATR_Y-VAL
          LOCAL_CATR_Y
          LOCATION_VALID-VAL
          LOCATION_VALID
          IS_RESET_GEO_LOCATION-VAL
          IS_RESET_GEO_LOCATION
))