(cl:in-package arbe_msgs-msg)
(cl:export '(VALID-VAL
          VALID
          OBJ_ID-VAL
          OBJ_ID
          QUERY_ID-VAL
          QUERY_ID
          FUSIONCLASS-VAL
          FUSIONCLASS
          OBJ_INDEX-VAL
          OBJ_INDEX
          QUERYTIME-VAL
          QUERYTIME
          CONF-VAL
          CONF
          TTA_COUNT-VAL
          TTA_COUNT
          TTA_SCORES-VAL
          TTA_SCORES
          CLASS_STR-VAL
          CLASS_STR
          FUSIONCLASSES-VAL
          FUSIONCLASSES
          TOP-VAL
          TOP
          LEFT-VAL
          LEFT
          BOTTOM-VAL
          BOTTOM
          RIGHT-VAL
          RIGHT
))