// Generated by gencpp from file arbe_msgs/arbePcWithValid.msg
// DO NOT EDIT!


#ifndef ARBE_MSGS_MESSAGE_ARBEPCWITHVALID_H
#define ARBE_MSGS_MESSAGE_ARBEPCWITHVALID_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <arbe_msgs/arbeNewPcMsg.h>

namespace arbe_msgs
{
template <class ContainerAllocator>
struct arbePcWithValid_
{
  typedef arbePcWithValid_<ContainerAllocator> Type;

  arbePcWithValid_()
    : pc()
    , valid()  {
    }
  arbePcWithValid_(const ContainerAllocator& _alloc)
    : pc(_alloc)
    , valid(_alloc)  {
  (void)_alloc;
    }



   typedef  ::arbe_msgs::arbeNewPcMsg_<ContainerAllocator>  _pc_type;
  _pc_type pc;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _valid_type;
  _valid_type valid;





  typedef boost::shared_ptr< ::arbe_msgs::arbePcWithValid_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arbe_msgs::arbePcWithValid_<ContainerAllocator> const> ConstPtr;

}; // struct arbePcWithValid_

typedef ::arbe_msgs::arbePcWithValid_<std::allocator<void> > arbePcWithValid;

typedef boost::shared_ptr< ::arbe_msgs::arbePcWithValid > arbePcWithValidPtr;
typedef boost::shared_ptr< ::arbe_msgs::arbePcWithValid const> arbePcWithValidConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arbe_msgs::arbePcWithValid_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arbe_msgs::arbePcWithValid_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arbe_msgs::arbePcWithValid_<ContainerAllocator1> & lhs, const ::arbe_msgs::arbePcWithValid_<ContainerAllocator2> & rhs)
{
  return lhs.pc == rhs.pc &&
    lhs.valid == rhs.valid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arbe_msgs::arbePcWithValid_<ContainerAllocator1> & lhs, const ::arbe_msgs::arbePcWithValid_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arbe_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::arbe_msgs::arbePcWithValid_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arbe_msgs::arbePcWithValid_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arbe_msgs::arbePcWithValid_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arbe_msgs::arbePcWithValid_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arbe_msgs::arbePcWithValid_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arbe_msgs::arbePcWithValid_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arbe_msgs::arbePcWithValid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e4ea8e0ece0df084b29db472b924eebf";
  }

  static const char* value(const ::arbe_msgs::arbePcWithValid_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe4ea8e0ece0df084ULL;
  static const uint64_t static_value2 = 0xb29db472b924eebfULL;
};

template<class ContainerAllocator>
struct DataType< ::arbe_msgs::arbePcWithValid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arbe_msgs/arbePcWithValid";
  }

  static const char* value(const ::arbe_msgs::arbePcWithValid_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arbe_msgs::arbePcWithValid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arbeNewPcMsg pc\n"
"bool[] valid\n"
"\n"
"================================================================================\n"
"MSG: arbe_msgs/arbeNewPcMsg\n"
"std_msgs/Header RosHeader\n"
"arbePcFrameHeader PcHeader\n"
"arbePcMetadata PcMetadata\n"
"arbePcBins Points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: arbe_msgs/arbePcFrameHeader\n"
"uint64 time\n"
"uint16 frame_counter\n"
"uint8  is_4d\n"
"uint8  frame_type\n"
"uint16 udp_lost_packages\n"
"uint32 number_of_points\n"
"uint16 crd_count\n"
"arbeFrameTypes frame_types\n"
"\n"
"================================================================================\n"
"MSG: arbe_msgs/arbeFrameTypes\n"
"uint8 Frame_Type_3d_short = 1\n"
"uint8 Frame_Type_3d_mid = 2\n"
"uint8 Frame_Type_3d_long = 3\n"
"uint8 Frame_Type_3d_ultra_long = 13\n"
"uint8 Frame_Type_4d_short = 4\n"
"uint8 Frame_Type_4d_mid = 5\n"
"uint8 Frame_Type_4d_long = 6\n"
"uint8 Frame_Type_4d_ultra_long = 16\n"
"\n"
"================================================================================\n"
"MSG: arbe_msgs/arbePcMetadata\n"
"arbePcRes PcResolution\n"
"float32 range_offset\n"
"float32 range_res_in_db\n"
"uint32 azimuth_fft_size\n"
"uint32 elevation_fft_size\n"
"uint32 azimuth_fft_padding\n"
"uint32 elevation_fft_padding\n"
"\n"
"\n"
"================================================================================\n"
"MSG: arbe_msgs/arbePcRes\n"
"float32 range_resolution\n"
"float32 doppler_resolution\n"
"float32 azimuth_coefficient\n"
"float32 elevation_coefficient\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: arbe_msgs/arbePcBins\n"
"uint16[] range_bin\n"
"int16[] doppler_signed_bin\n"
"int8[] azimuth_signed_bin\n"
"int8[] elevation_signed_bin\n"
"int16[] phase\n"
"int16[] power\n"
"\n"
"\n"
;
  }

  static const char* value(const ::arbe_msgs::arbePcWithValid_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arbe_msgs::arbePcWithValid_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pc);
      stream.next(m.valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arbePcWithValid_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arbe_msgs::arbePcWithValid_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arbe_msgs::arbePcWithValid_<ContainerAllocator>& v)
  {
    s << indent << "pc: ";
    s << std::endl;
    Printer< ::arbe_msgs::arbeNewPcMsg_<ContainerAllocator> >::stream(s, indent + "  ", v.pc);
    s << indent << "valid[]" << std::endl;
    for (size_t i = 0; i < v.valid.size(); ++i)
    {
      s << indent << "  valid[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.valid[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARBE_MSGS_MESSAGE_ARBEPCWITHVALID_H
