// Generated by gencpp from file arbe_msgs/arbeFusionResponse.msg
// DO NOT EDIT!


#ifndef ARBE_MSGS_MESSAGE_ARBEFUSIONRESPONSE_H
#define ARBE_MSGS_MESSAGE_ARBEFUSIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <arbe_msgs/arbeFusionClasses.h>

namespace arbe_msgs
{
template <class ContainerAllocator>
struct arbeFusionResponse_
{
  typedef arbeFusionResponse_<ContainerAllocator> Type;

  arbeFusionResponse_()
    : valid(false)
    , obj_id(0)
    , query_id(0)
    , fusionClass(0)
    , obj_index(0)
    , queryTime(0)
    , conf(0.0)
    , tta_count(0)
    , tta_scores()
    , class_str()
    , fusionClasses()
    , top(0)
    , left(0)
    , bottom(0)
    , right(0)  {
    }
  arbeFusionResponse_(const ContainerAllocator& _alloc)
    : valid(false)
    , obj_id(0)
    , query_id(0)
    , fusionClass(0)
    , obj_index(0)
    , queryTime(0)
    , conf(0.0)
    , tta_count(0)
    , tta_scores(_alloc)
    , class_str(_alloc)
    , fusionClasses(_alloc)
    , top(0)
    , left(0)
    , bottom(0)
    , right(0)  {
  (void)_alloc;
    }



   typedef uint8_t _valid_type;
  _valid_type valid;

   typedef uint16_t _obj_id_type;
  _obj_id_type obj_id;

   typedef uint32_t _query_id_type;
  _query_id_type query_id;

   typedef uint8_t _fusionClass_type;
  _fusionClass_type fusionClass;

   typedef uint16_t _obj_index_type;
  _obj_index_type obj_index;

   typedef uint64_t _queryTime_type;
  _queryTime_type queryTime;

   typedef float _conf_type;
  _conf_type conf;

   typedef uint8_t _tta_count_type;
  _tta_count_type tta_count;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _tta_scores_type;
  _tta_scores_type tta_scores;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _class_str_type;
  _class_str_type class_str;

   typedef  ::arbe_msgs::arbeFusionClasses_<ContainerAllocator>  _fusionClasses_type;
  _fusionClasses_type fusionClasses;

   typedef uint16_t _top_type;
  _top_type top;

   typedef uint16_t _left_type;
  _left_type left;

   typedef uint16_t _bottom_type;
  _bottom_type bottom;

   typedef uint16_t _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::arbe_msgs::arbeFusionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arbe_msgs::arbeFusionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct arbeFusionResponse_

typedef ::arbe_msgs::arbeFusionResponse_<std::allocator<void> > arbeFusionResponse;

typedef boost::shared_ptr< ::arbe_msgs::arbeFusionResponse > arbeFusionResponsePtr;
typedef boost::shared_ptr< ::arbe_msgs::arbeFusionResponse const> arbeFusionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arbe_msgs::arbeFusionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arbe_msgs::arbeFusionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arbe_msgs::arbeFusionResponse_<ContainerAllocator1> & lhs, const ::arbe_msgs::arbeFusionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.valid == rhs.valid &&
    lhs.obj_id == rhs.obj_id &&
    lhs.query_id == rhs.query_id &&
    lhs.fusionClass == rhs.fusionClass &&
    lhs.obj_index == rhs.obj_index &&
    lhs.queryTime == rhs.queryTime &&
    lhs.conf == rhs.conf &&
    lhs.tta_count == rhs.tta_count &&
    lhs.tta_scores == rhs.tta_scores &&
    lhs.class_str == rhs.class_str &&
    lhs.fusionClasses == rhs.fusionClasses &&
    lhs.top == rhs.top &&
    lhs.left == rhs.left &&
    lhs.bottom == rhs.bottom &&
    lhs.right == rhs.right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arbe_msgs::arbeFusionResponse_<ContainerAllocator1> & lhs, const ::arbe_msgs::arbeFusionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arbe_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::arbe_msgs::arbeFusionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arbe_msgs::arbeFusionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arbe_msgs::arbeFusionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arbe_msgs::arbeFusionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arbe_msgs::arbeFusionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arbe_msgs::arbeFusionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arbe_msgs::arbeFusionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d16e7674f130b5c070b9bc414f29ed5";
  }

  static const char* value(const ::arbe_msgs::arbeFusionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d16e7674f130b5cULL;
  static const uint64_t static_value2 = 0x070b9bc414f29ed5ULL;
};

template<class ContainerAllocator>
struct DataType< ::arbe_msgs::arbeFusionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arbe_msgs/arbeFusionResponse";
  }

  static const char* value(const ::arbe_msgs::arbeFusionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arbe_msgs::arbeFusionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool valid\n"
"uint16 obj_id\n"
"uint32 query_id\n"
"uint8 fusionClass\n"
"uint16 obj_index\n"
"uint64 queryTime\n"
"float32 conf\n"
"uint8 tta_count\n"
"float32[] tta_scores\n"
"string class_str\n"
"arbeFusionClasses fusionClasses\n"
"\n"
"uint16  top\n"
"uint16  left\n"
"uint16  bottom\n"
"uint16  right\n"
"\n"
"================================================================================\n"
"MSG: arbe_msgs/arbeFusionClasses\n"
"uint16 FC_BIKE = 0\n"
"uint16 FC_TRUCK_BUS = 1\n"
"uint16 FC_VRU = 2\n"
"uint16 FC_CAR = 3\n"
"uint16 FC_NOT_CLASSIFIED = 4\n"
"uint16 NUM_CLASSES = 4\n"
;
  }

  static const char* value(const ::arbe_msgs::arbeFusionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arbe_msgs::arbeFusionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.valid);
      stream.next(m.obj_id);
      stream.next(m.query_id);
      stream.next(m.fusionClass);
      stream.next(m.obj_index);
      stream.next(m.queryTime);
      stream.next(m.conf);
      stream.next(m.tta_count);
      stream.next(m.tta_scores);
      stream.next(m.class_str);
      stream.next(m.fusionClasses);
      stream.next(m.top);
      stream.next(m.left);
      stream.next(m.bottom);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arbeFusionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arbe_msgs::arbeFusionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arbe_msgs::arbeFusionResponse_<ContainerAllocator>& v)
  {
    s << indent << "valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid);
    s << indent << "obj_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.obj_id);
    s << indent << "query_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.query_id);
    s << indent << "fusionClass: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.fusionClass);
    s << indent << "obj_index: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.obj_index);
    s << indent << "queryTime: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.queryTime);
    s << indent << "conf: ";
    Printer<float>::stream(s, indent + "  ", v.conf);
    s << indent << "tta_count: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tta_count);
    s << indent << "tta_scores[]" << std::endl;
    for (size_t i = 0; i < v.tta_scores.size(); ++i)
    {
      s << indent << "  tta_scores[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.tta_scores[i]);
    }
    s << indent << "class_str: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.class_str);
    s << indent << "fusionClasses: ";
    s << std::endl;
    Printer< ::arbe_msgs::arbeFusionClasses_<ContainerAllocator> >::stream(s, indent + "  ", v.fusionClasses);
    s << indent << "top: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.top);
    s << indent << "left: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.left);
    s << indent << "bottom: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.bottom);
    s << indent << "right: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARBE_MSGS_MESSAGE_ARBEFUSIONRESPONSE_H
