// Generated by gencpp from file arbe_msgs/arbeDtExceedTh.msg
// DO NOT EDIT!


#ifndef ARBE_MSGS_MESSAGE_ARBEDTEXCEEDTH_H
#define ARBE_MSGS_MESSAGE_ARBEDTEXCEEDTH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arbe_msgs
{
template <class ContainerAllocator>
struct arbeDtExceedTh_
{
  typedef arbeDtExceedTh_<ContainerAllocator> Type;

  arbeDtExceedTh_()
    : frame_counter(0)
    , dt(0)  {
    }
  arbeDtExceedTh_(const ContainerAllocator& _alloc)
    : frame_counter(0)
    , dt(0)  {
  (void)_alloc;
    }



   typedef uint16_t _frame_counter_type;
  _frame_counter_type frame_counter;

   typedef uint64_t _dt_type;
  _dt_type dt;





  typedef boost::shared_ptr< ::arbe_msgs::arbeDtExceedTh_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arbe_msgs::arbeDtExceedTh_<ContainerAllocator> const> ConstPtr;

}; // struct arbeDtExceedTh_

typedef ::arbe_msgs::arbeDtExceedTh_<std::allocator<void> > arbeDtExceedTh;

typedef boost::shared_ptr< ::arbe_msgs::arbeDtExceedTh > arbeDtExceedThPtr;
typedef boost::shared_ptr< ::arbe_msgs::arbeDtExceedTh const> arbeDtExceedThConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arbe_msgs::arbeDtExceedTh_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arbe_msgs::arbeDtExceedTh_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arbe_msgs::arbeDtExceedTh_<ContainerAllocator1> & lhs, const ::arbe_msgs::arbeDtExceedTh_<ContainerAllocator2> & rhs)
{
  return lhs.frame_counter == rhs.frame_counter &&
    lhs.dt == rhs.dt;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arbe_msgs::arbeDtExceedTh_<ContainerAllocator1> & lhs, const ::arbe_msgs::arbeDtExceedTh_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arbe_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::arbe_msgs::arbeDtExceedTh_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arbe_msgs::arbeDtExceedTh_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arbe_msgs::arbeDtExceedTh_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arbe_msgs::arbeDtExceedTh_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arbe_msgs::arbeDtExceedTh_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arbe_msgs::arbeDtExceedTh_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arbe_msgs::arbeDtExceedTh_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3c2831d3d6ab52b0524ebb559a84899";
  }

  static const char* value(const ::arbe_msgs::arbeDtExceedTh_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3c2831d3d6ab52bULL;
  static const uint64_t static_value2 = 0x0524ebb559a84899ULL;
};

template<class ContainerAllocator>
struct DataType< ::arbe_msgs::arbeDtExceedTh_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arbe_msgs/arbeDtExceedTh";
  }

  static const char* value(const ::arbe_msgs::arbeDtExceedTh_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arbe_msgs::arbeDtExceedTh_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 frame_counter\n"
"uint64 dt\n"
;
  }

  static const char* value(const ::arbe_msgs::arbeDtExceedTh_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arbe_msgs::arbeDtExceedTh_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame_counter);
      stream.next(m.dt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arbeDtExceedTh_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arbe_msgs::arbeDtExceedTh_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arbe_msgs::arbeDtExceedTh_<ContainerAllocator>& v)
  {
    s << indent << "frame_counter: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.frame_counter);
    s << indent << "dt: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.dt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARBE_MSGS_MESSAGE_ARBEDTEXCEEDTH_H
