// Generated by gencpp from file arbe_msgs/arbeRdInclination.msg
// DO NOT EDIT!


#ifndef ARBE_MSGS_MESSAGE_ARBERDINCLINATION_H
#define ARBE_MSGS_MESSAGE_ARBERDINCLINATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace arbe_msgs
{
template <class ContainerAllocator>
struct arbeRdInclination_
{
  typedef arbeRdInclination_<ContainerAllocator> Type;

  arbeRdInclination_()
    : header()
    , ant_height(0.0)
    , ant_tilt(0.0)  {
    }
  arbeRdInclination_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ant_height(0.0)
    , ant_tilt(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _ant_height_type;
  _ant_height_type ant_height;

   typedef float _ant_tilt_type;
  _ant_tilt_type ant_tilt;





  typedef boost::shared_ptr< ::arbe_msgs::arbeRdInclination_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arbe_msgs::arbeRdInclination_<ContainerAllocator> const> ConstPtr;

}; // struct arbeRdInclination_

typedef ::arbe_msgs::arbeRdInclination_<std::allocator<void> > arbeRdInclination;

typedef boost::shared_ptr< ::arbe_msgs::arbeRdInclination > arbeRdInclinationPtr;
typedef boost::shared_ptr< ::arbe_msgs::arbeRdInclination const> arbeRdInclinationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arbe_msgs::arbeRdInclination_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arbe_msgs::arbeRdInclination_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arbe_msgs::arbeRdInclination_<ContainerAllocator1> & lhs, const ::arbe_msgs::arbeRdInclination_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ant_height == rhs.ant_height &&
    lhs.ant_tilt == rhs.ant_tilt;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arbe_msgs::arbeRdInclination_<ContainerAllocator1> & lhs, const ::arbe_msgs::arbeRdInclination_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arbe_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::arbe_msgs::arbeRdInclination_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arbe_msgs::arbeRdInclination_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arbe_msgs::arbeRdInclination_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arbe_msgs::arbeRdInclination_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arbe_msgs::arbeRdInclination_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arbe_msgs::arbeRdInclination_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arbe_msgs::arbeRdInclination_<ContainerAllocator> >
{
  static const char* value()
  {
    return "401e82b1a597051854c2fb29fdf032ba";
  }

  static const char* value(const ::arbe_msgs::arbeRdInclination_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x401e82b1a5970518ULL;
  static const uint64_t static_value2 = 0x54c2fb29fdf032baULL;
};

template<class ContainerAllocator>
struct DataType< ::arbe_msgs::arbeRdInclination_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arbe_msgs/arbeRdInclination";
  }

  static const char* value(const ::arbe_msgs::arbeRdInclination_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arbe_msgs::arbeRdInclination_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float32 ant_height\n"
"float32 ant_tilt\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::arbe_msgs::arbeRdInclination_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arbe_msgs::arbeRdInclination_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ant_height);
      stream.next(m.ant_tilt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arbeRdInclination_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arbe_msgs::arbeRdInclination_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arbe_msgs::arbeRdInclination_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ant_height: ";
    Printer<float>::stream(s, indent + "  ", v.ant_height);
    s << indent << "ant_tilt: ";
    Printer<float>::stream(s, indent + "  ", v.ant_tilt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARBE_MSGS_MESSAGE_ARBERDINCLINATION_H
