// Generated by gencpp from file arbe_msgs/arbeBuildNumber.msg
// DO NOT EDIT!


#ifndef ARBE_MSGS_MESSAGE_ARBEBUILDNUMBER_H
#define ARBE_MSGS_MESSAGE_ARBEBUILDNUMBER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace arbe_msgs
{
template <class ContainerAllocator>
struct arbeBuildNumber_
{
  typedef arbeBuildNumber_<ContainerAllocator> Type;

  arbeBuildNumber_()
    : header()
    , slam(0)
    , arbe_gui(0)
    , arbe_api_common(0)
    , arbe_msgs(0)
    , radar(0)  {
    }
  arbeBuildNumber_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , slam(0)
    , arbe_gui(0)
    , arbe_api_common(0)
    , arbe_msgs(0)
    , radar(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _slam_type;
  _slam_type slam;

   typedef int32_t _arbe_gui_type;
  _arbe_gui_type arbe_gui;

   typedef int32_t _arbe_api_common_type;
  _arbe_api_common_type arbe_api_common;

   typedef int32_t _arbe_msgs_type;
  _arbe_msgs_type arbe_msgs;

   typedef int32_t _radar_type;
  _radar_type radar;





  typedef boost::shared_ptr< ::arbe_msgs::arbeBuildNumber_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arbe_msgs::arbeBuildNumber_<ContainerAllocator> const> ConstPtr;

}; // struct arbeBuildNumber_

typedef ::arbe_msgs::arbeBuildNumber_<std::allocator<void> > arbeBuildNumber;

typedef boost::shared_ptr< ::arbe_msgs::arbeBuildNumber > arbeBuildNumberPtr;
typedef boost::shared_ptr< ::arbe_msgs::arbeBuildNumber const> arbeBuildNumberConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arbe_msgs::arbeBuildNumber_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arbe_msgs::arbeBuildNumber_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arbe_msgs::arbeBuildNumber_<ContainerAllocator1> & lhs, const ::arbe_msgs::arbeBuildNumber_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.slam == rhs.slam &&
    lhs.arbe_gui == rhs.arbe_gui &&
    lhs.arbe_api_common == rhs.arbe_api_common &&
    lhs.arbe_msgs == rhs.arbe_msgs &&
    lhs.radar == rhs.radar;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arbe_msgs::arbeBuildNumber_<ContainerAllocator1> & lhs, const ::arbe_msgs::arbeBuildNumber_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arbe_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::arbe_msgs::arbeBuildNumber_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arbe_msgs::arbeBuildNumber_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arbe_msgs::arbeBuildNumber_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arbe_msgs::arbeBuildNumber_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arbe_msgs::arbeBuildNumber_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arbe_msgs::arbeBuildNumber_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arbe_msgs::arbeBuildNumber_<ContainerAllocator> >
{
  static const char* value()
  {
    return "45c45703c45e662d3433cd39dca68964";
  }

  static const char* value(const ::arbe_msgs::arbeBuildNumber_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x45c45703c45e662dULL;
  static const uint64_t static_value2 = 0x3433cd39dca68964ULL;
};

template<class ContainerAllocator>
struct DataType< ::arbe_msgs::arbeBuildNumber_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arbe_msgs/arbeBuildNumber";
  }

  static const char* value(const ::arbe_msgs::arbeBuildNumber_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arbe_msgs::arbeBuildNumber_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"int32 slam\n"
"int32 arbe_gui\n"
"int32 arbe_api_common\n"
"int32 arbe_msgs\n"
"int32 radar\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::arbe_msgs::arbeBuildNumber_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arbe_msgs::arbeBuildNumber_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.slam);
      stream.next(m.arbe_gui);
      stream.next(m.arbe_api_common);
      stream.next(m.arbe_msgs);
      stream.next(m.radar);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arbeBuildNumber_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arbe_msgs::arbeBuildNumber_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arbe_msgs::arbeBuildNumber_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "slam: ";
    Printer<int32_t>::stream(s, indent + "  ", v.slam);
    s << indent << "arbe_gui: ";
    Printer<int32_t>::stream(s, indent + "  ", v.arbe_gui);
    s << indent << "arbe_api_common: ";
    Printer<int32_t>::stream(s, indent + "  ", v.arbe_api_common);
    s << indent << "arbe_msgs: ";
    Printer<int32_t>::stream(s, indent + "  ", v.arbe_msgs);
    s << indent << "radar: ";
    Printer<int32_t>::stream(s, indent + "  ", v.radar);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARBE_MSGS_MESSAGE_ARBEBUILDNUMBER_H
