// Generated by gencpp from file arbe_msgs/arbeBoolWithTime.msg
// DO NOT EDIT!


#ifndef ARBE_MSGS_MESSAGE_ARBEBOOLWITHTIME_H
#define ARBE_MSGS_MESSAGE_ARBEBOOLWITHTIME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace arbe_msgs
{
template <class ContainerAllocator>
struct arbeBoolWithTime_
{
  typedef arbeBoolWithTime_<ContainerAllocator> Type;

  arbeBoolWithTime_()
    : header()
    , flag(false)  {
    }
  arbeBoolWithTime_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , flag(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _flag_type;
  _flag_type flag;





  typedef boost::shared_ptr< ::arbe_msgs::arbeBoolWithTime_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arbe_msgs::arbeBoolWithTime_<ContainerAllocator> const> ConstPtr;

}; // struct arbeBoolWithTime_

typedef ::arbe_msgs::arbeBoolWithTime_<std::allocator<void> > arbeBoolWithTime;

typedef boost::shared_ptr< ::arbe_msgs::arbeBoolWithTime > arbeBoolWithTimePtr;
typedef boost::shared_ptr< ::arbe_msgs::arbeBoolWithTime const> arbeBoolWithTimeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arbe_msgs::arbeBoolWithTime_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arbe_msgs::arbeBoolWithTime_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arbe_msgs::arbeBoolWithTime_<ContainerAllocator1> & lhs, const ::arbe_msgs::arbeBoolWithTime_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.flag == rhs.flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arbe_msgs::arbeBoolWithTime_<ContainerAllocator1> & lhs, const ::arbe_msgs::arbeBoolWithTime_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arbe_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::arbe_msgs::arbeBoolWithTime_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arbe_msgs::arbeBoolWithTime_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arbe_msgs::arbeBoolWithTime_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arbe_msgs::arbeBoolWithTime_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arbe_msgs::arbeBoolWithTime_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arbe_msgs::arbeBoolWithTime_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arbe_msgs::arbeBoolWithTime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1faeb665af69705369ce1bafa748a16c";
  }

  static const char* value(const ::arbe_msgs::arbeBoolWithTime_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1faeb665af697053ULL;
  static const uint64_t static_value2 = 0x69ce1bafa748a16cULL;
};

template<class ContainerAllocator>
struct DataType< ::arbe_msgs::arbeBoolWithTime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arbe_msgs/arbeBoolWithTime";
  }

  static const char* value(const ::arbe_msgs::arbeBoolWithTime_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arbe_msgs::arbeBoolWithTime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"bool flag\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::arbe_msgs::arbeBoolWithTime_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arbe_msgs::arbeBoolWithTime_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arbeBoolWithTime_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arbe_msgs::arbeBoolWithTime_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arbe_msgs::arbeBoolWithTime_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARBE_MSGS_MESSAGE_ARBEBOOLWITHTIME_H
