// Generated by gencpp from file arbe_msgs/arbeTSlamPos.msg
// DO NOT EDIT!


#ifndef ARBE_MSGS_MESSAGE_ARBETSLAMPOS_H
#define ARBE_MSGS_MESSAGE_ARBETSLAMPOS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arbe_msgs
{
template <class ContainerAllocator>
struct arbeTSlamPos_
{
  typedef arbeTSlamPos_<ContainerAllocator> Type;

  arbeTSlamPos_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , dx(0.0)
    , dy(0.0)
    , dz(0.0)  {
    }
  arbeTSlamPos_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , dx(0.0)
    , dy(0.0)
    , dz(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _dx_type;
  _dx_type dx;

   typedef float _dy_type;
  _dy_type dy;

   typedef float _dz_type;
  _dz_type dz;





  typedef boost::shared_ptr< ::arbe_msgs::arbeTSlamPos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arbe_msgs::arbeTSlamPos_<ContainerAllocator> const> ConstPtr;

}; // struct arbeTSlamPos_

typedef ::arbe_msgs::arbeTSlamPos_<std::allocator<void> > arbeTSlamPos;

typedef boost::shared_ptr< ::arbe_msgs::arbeTSlamPos > arbeTSlamPosPtr;
typedef boost::shared_ptr< ::arbe_msgs::arbeTSlamPos const> arbeTSlamPosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arbe_msgs::arbeTSlamPos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arbe_msgs::arbeTSlamPos_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arbe_msgs::arbeTSlamPos_<ContainerAllocator1> & lhs, const ::arbe_msgs::arbeTSlamPos_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.dx == rhs.dx &&
    lhs.dy == rhs.dy &&
    lhs.dz == rhs.dz;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arbe_msgs::arbeTSlamPos_<ContainerAllocator1> & lhs, const ::arbe_msgs::arbeTSlamPos_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arbe_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::arbe_msgs::arbeTSlamPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arbe_msgs::arbeTSlamPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arbe_msgs::arbeTSlamPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arbe_msgs::arbeTSlamPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arbe_msgs::arbeTSlamPos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arbe_msgs::arbeTSlamPos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arbe_msgs::arbeTSlamPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7ebdf4fc16c563585927be0d949cdc5a";
  }

  static const char* value(const ::arbe_msgs::arbeTSlamPos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7ebdf4fc16c56358ULL;
  static const uint64_t static_value2 = 0x5927be0d949cdc5aULL;
};

template<class ContainerAllocator>
struct DataType< ::arbe_msgs::arbeTSlamPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arbe_msgs/arbeTSlamPos";
  }

  static const char* value(const ::arbe_msgs::arbeTSlamPos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arbe_msgs::arbeTSlamPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x \n"
"float32 y \n"
"float32 z \n"
"float32  dx \n"
"float32  dy \n"
"float32  dz\n"
;
  }

  static const char* value(const ::arbe_msgs::arbeTSlamPos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arbe_msgs::arbeTSlamPos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.dx);
      stream.next(m.dy);
      stream.next(m.dz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arbeTSlamPos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arbe_msgs::arbeTSlamPos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arbe_msgs::arbeTSlamPos_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "dx: ";
    Printer<float>::stream(s, indent + "  ", v.dx);
    s << indent << "dy: ";
    Printer<float>::stream(s, indent + "  ", v.dy);
    s << indent << "dz: ";
    Printer<float>::stream(s, indent + "  ", v.dz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARBE_MSGS_MESSAGE_ARBETSLAMPOS_H
